export const ALTRU_CODER_BUILTIN_MODELS = {
  "altru-coder-auto/free": {
    id: "altru-coder-auto/free",
    name: "Altru Coder Auto Free",
    family: "altru-coder-auto",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2026-03-15",
    last_updated: "2026-03-15",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: false,
    cost: { input: 0, output: 0 },
    limit: { context: 204_800, output: 131_072 },
  },
  "openai/gpt-oss-120b": {
    id: "openai/gpt-oss-120b",
    name: "OpenAI: gpt-oss-120b",
    family: "gpt-oss",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2025-08-05",
    last_updated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    cost: { input: 0, output: 0 },
    limit: { context: 131_072, output: 26_215 },
  },
} as const
