const context = 1_000_000
const reasoning = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((effort) => [effort, { reasoning: { effort } }]),
)

export const ALTRU_CODER_REMOVED_MODEL_IDS = new Set(["altru-coder/hy3-preview-free", "openai/gpt-oss-120b"])

export const ALTRU_CODER_BUILTIN_MODELS = {
  "altru-coder-auto/free": {
    id: "altru-coder-auto/free",
    name: "Altru Coder Auto Free",
    family: "altru-coder-auto",
    prompt: "gpt55",
    attachment: false,
    reasoning: false,
    tool_call: true,
    temperature: true,
    release_date: "2026-03-15",
    last_updated: "2026-03-15",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: false,
    isFree: true,
    cost: { input: 0, output: 0 },
    limit: { context, output: 128_000 },
  },
  "altru-coder/big-pickle-free": {
    id: "altru-coder/big-pickle-free",
    name: "Altru Coder Big Pickle Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: false,
    tool_call: true,
    temperature: true,
    release_date: "2025-10-17",
    last_updated: "2025-10-17",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: false,
    isFree: true,
    cost: { input: 0, output: 0 },
    limit: { context, output: 128_000 },
  },
  "altru-coder/minimax-m2.5-free": {
    id: "altru-coder/minimax-m2.5-free",
    name: "Altru Coder MiniMax M2.5 Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    variants: reasoning,
    release_date: "2026-02-12",
    last_updated: "2026-02-12",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    isFree: true,
    cost: { input: 0, output: 0 },
    limit: { context, output: 131_072 },
  },
  "altru-coder/nemotron-3-super-free": {
    id: "altru-coder/nemotron-3-super-free",
    name: "Altru Coder Nemotron 3 Super Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    variants: reasoning,
    release_date: "2026-03-11",
    last_updated: "2026-03-11",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    isFree: true,
    cost: { input: 0, output: 0 },
    limit: { context, output: 128_000 },
  },
} as const
