const high = {
  reasoning: { effort: "high" },
  verbosity: "high",
} as const
const context = 1_000_000

export const ALTRU_CODER_BUILTIN_MODELS = {
  "altru-coder-auto/free": {
    id: "altru-coder-auto/free",
    name: "Altru Coder Auto Free",
    family: "altru-coder-auto",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2026-03-15",
    last_updated: "2026-03-15",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: false,
    cost: { input: 0, output: 0 },
    limit: { context, output: 128_000 },
    options: high,
  },
  "altru-coder/big-pickle-free": {
    id: "altru-coder/big-pickle-free",
    name: "Altru Coder Big Pickle Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2025-10-17",
    last_updated: "2025-10-17",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: false,
    cost: { input: 0, output: 0 },
    limit: { context: 200_000, output: 128_000 },
    options: high,
  },
  "altru-coder/hy3-preview-free": {
    id: "altru-coder/hy3-preview-free",
    name: "Altru Coder Hy3 Preview Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2026-03-15",
    last_updated: "2026-03-15",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    cost: { input: 0, output: 0 },
    limit: { context: 200_000, output: 64_000 },
    options: high,
  },
  "altru-coder/minimax-m2.5-free": {
    id: "altru-coder/minimax-m2.5-free",
    name: "Altru Coder MiniMax M2.5 Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2026-02-12",
    last_updated: "2026-02-12",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    cost: { input: 0, output: 0 },
    limit: { context: 204_800, output: 131_072 },
    options: high,
  },
  "altru-coder/nemotron-3-super-free": {
    id: "altru-coder/nemotron-3-super-free",
    name: "Altru Coder Nemotron 3 Super Free",
    family: "altru-coder-free",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2026-03-11",
    last_updated: "2026-03-11",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    cost: { input: 0, output: 0 },
    limit: { context, output: 128_000 },
    options: high,
  },
  "openai/gpt-oss-120b": {
    id: "openai/gpt-oss-120b",
    name: "OpenAI: gpt-oss-120b",
    family: "gpt-oss",
    prompt: "gpt55",
    attachment: false,
    reasoning: true,
    tool_call: true,
    temperature: true,
    release_date: "2025-08-05",
    last_updated: "2025-08-05",
    modalities: { input: ["text"], output: ["text"] },
    open_weights: true,
    cost: { input: 0, output: 0 },
    limit: { context: 131_072, output: 26_215 },
    options: high,
  },
} as const
