import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const DeepinfraPreset: ProviderPreset = {
  id: "deepinfra",
  name: "DeepInfra",
  baseURL: "https://api.deepinfra.com/v1/openai",
  note: "Seeded from DeepInfra official /models catalog (151 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("anthropic/claude-3-7-sonnet-latest", "anthropic/claude-3-7-sonnet-latest", true),
    model("anthropic/claude-4-opus", "anthropic/claude-4-opus", true),
    model("anthropic/claude-4-sonnet", "anthropic/claude-4-sonnet", true),
    model("BAAI/bge-base-en-v1.5", "BAAI/bge-base-en-v1.5", false),
    model("BAAI/bge-en-icl", "BAAI/bge-en-icl", false),
    model("BAAI/bge-large-en-v1.5", "BAAI/bge-large-en-v1.5", false),
    model("BAAI/bge-m3", "BAAI/bge-m3", false),
    model("BAAI/bge-m3-multi", "BAAI/bge-m3-multi", false),
    model("black-forest-labs/FLUX-1-dev", "black-forest-labs/FLUX-1-dev", false),
    model("black-forest-labs/FLUX-1-Redux-dev", "black-forest-labs/FLUX-1-Redux-dev", false),
    model("black-forest-labs/FLUX-1-schnell", "black-forest-labs/FLUX-1-schnell", false),
    model("black-forest-labs/FLUX-1.1-pro", "black-forest-labs/FLUX-1.1-pro", false),
    model("black-forest-labs/FLUX-2-dev", "black-forest-labs/FLUX-2-dev", false),
    model("black-forest-labs/FLUX-2-klein-4b", "black-forest-labs/FLUX-2-klein-4b", false),
    model("black-forest-labs/FLUX-2-klein-9b", "black-forest-labs/FLUX-2-klein-9b", false),
    model("black-forest-labs/FLUX-2-max", "black-forest-labs/FLUX-2-max", false),
    model("black-forest-labs/FLUX-2-pro", "black-forest-labs/FLUX-2-pro", false),
    model("black-forest-labs/FLUX-pro", "black-forest-labs/FLUX-pro", false),
    model("black-forest-labs/FLUX.1-Kontext-dev", "black-forest-labs/FLUX.1-Kontext-dev", false),
    model("Bria/blur_background", "Bria/blur_background", false),
    model("Bria/Bria-3.2", "Bria/Bria-3.2", false),
    model("Bria/Bria-3.2-vector", "Bria/Bria-3.2-vector", false),
    model("Bria/enhance", "Bria/enhance", false),
    model("Bria/erase", "Bria/erase", false),
    model("Bria/erase_foreground", "Bria/erase_foreground", false),
    model("Bria/expand", "Bria/expand", false),
    model("Bria/fibo", "Bria/fibo", false),
    model("Bria/fibo_edit", "Bria/fibo_edit", false),
    model("Bria/gen_fill", "Bria/gen_fill", false),
    model("Bria/remove_background", "Bria/remove_background", false),
    model("Bria/replace_background", "Bria/replace_background", false),
    model("ByteDance/Seed-1.8", "ByteDance/Seed-1.8", false),
    model("ByteDance/Seed-2.0-code", "ByteDance/Seed-2.0-code", false),
    model("ByteDance/Seed-2.0-mini", "ByteDance/Seed-2.0-mini", false),
    model("ByteDance/Seed-2.0-pro", "ByteDance/Seed-2.0-pro", false),
    model("ByteDance/Seedream-4", "ByteDance/Seedream-4", false),
    model("ByteDance/Seedream-4.5", "ByteDance/Seedream-4.5", false),
    model("ClarityAI/creative", "ClarityAI/creative", false),
    model("ClarityAI/crystal", "ClarityAI/crystal", false),
    model("ClarityAI/flux", "ClarityAI/flux", false),
    model("deepseek-ai/DeepSeek-R1-0528", "deepseek-ai/DeepSeek-R1-0528", true),
    model("deepseek-ai/DeepSeek-R1-0528-Turbo", "deepseek-ai/DeepSeek-R1-0528-Turbo", true),
    model("deepseek-ai/DeepSeek-R1-Distill-Llama-70B", "deepseek-ai/DeepSeek-R1-Distill-Llama-70B", true),
    model("deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepSeek-V3", false),
    model("deepseek-ai/DeepSeek-V3-0324", "deepseek-ai/DeepSeek-V3-0324", false),
    model("deepseek-ai/DeepSeek-V3.1", "deepseek-ai/DeepSeek-V3.1", true),
    model("deepseek-ai/DeepSeek-V3.1-Terminus", "deepseek-ai/DeepSeek-V3.1-Terminus", true),
    model("deepseek-ai/DeepSeek-V3.2", "deepseek-ai/DeepSeek-V3.2", true),
    model("deepseek-ai/DeepSeek-V4-Flash", "deepseek-ai/DeepSeek-V4-Flash", true),
    model("deepseek-ai/DeepSeek-V4-Pro", "deepseek-ai/DeepSeek-V4-Pro", true),
    model("deepseek-ai/Janus-Pro-1B", "deepseek-ai/Janus-Pro-1B", false),
    model("deepseek-ai/Janus-Pro-7B", "deepseek-ai/Janus-Pro-7B", false),
    model("google/embeddinggemma-300m", "google/embeddinggemma-300m", false),
    model("google/gemini-1.5-flash", "google/gemini-1.5-flash", false),
    model("google/gemini-1.5-flash-8b", "google/gemini-1.5-flash-8b", false),
    model("google/gemini-2.5-flash", "google/gemini-2.5-flash", true),
    model("google/gemini-2.5-pro", "google/gemini-2.5-pro", true),
    model("google/gemma-3-12b-it", "google/gemma-3-12b-it", false),
    model("google/gemma-3-27b-it", "google/gemma-3-27b-it", false),
    model("google/gemma-3-4b-it", "google/gemma-3-4b-it", false),
    model("google/gemma-4-26B-A4B-it", "google/gemma-4-26B-A4B-it", false),
    model("google/gemma-4-31B-it", "google/gemma-4-31B-it", false),
    model("Gryphe/MythoMax-L2-13b", "Gryphe/MythoMax-L2-13b", false),
    model("intfloat/e5-base-v2", "intfloat/e5-base-v2", false),
    model("intfloat/e5-large-v2", "intfloat/e5-large-v2", false),
    model("intfloat/multilingual-e5-large", "intfloat/multilingual-e5-large", false),
    model("intfloat/multilingual-e5-large-instruct", "intfloat/multilingual-e5-large-instruct", false),
    model("meta-llama/Llama-3.2-11B-Vision-Instruct", "meta-llama/Llama-3.2-11B-Vision-Instruct", false),
    model("meta-llama/Llama-3.3-70B-Instruct-Turbo", "meta-llama/Llama-3.3-70B-Instruct-Turbo", false),
    model(
      "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
      "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
      false,
    ),
    model("meta-llama/Llama-4-Scout-17B-16E-Instruct", "meta-llama/Llama-4-Scout-17B-16E-Instruct", false),
    model("meta-llama/Llama-Guard-4-12B", "meta-llama/Llama-Guard-4-12B", false),
    model("meta-llama/Meta-Llama-3.1-70B-Instruct", "meta-llama/Meta-Llama-3.1-70B-Instruct", false),
    model("meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo", "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo", false),
    model("meta-llama/Meta-Llama-3.1-8B-Instruct", "meta-llama/Meta-Llama-3.1-8B-Instruct", false),
    model("meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo", "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo", false),
    model("microsoft/phi-4", "microsoft/phi-4", false),
    model("MiniMaxAI/MiniMax-M2.5", "MiniMaxAI/MiniMax-M2.5", true),
    model("mistralai/Mistral-Nemo-Instruct-2407", "mistralai/Mistral-Nemo-Instruct-2407", false),
    model("mistralai/Mistral-Small-24B-Instruct-2501", "mistralai/Mistral-Small-24B-Instruct-2501", false),
    model("mistralai/Mistral-Small-3.2-24B-Instruct-2506", "mistralai/Mistral-Small-3.2-24B-Instruct-2506", false),
    model("moonshotai/Kimi-K2.5", "moonshotai/Kimi-K2.5", true),
    model("moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.6", true),
    model("NousResearch/Hermes-3-Llama-3.1-405B", "NousResearch/Hermes-3-Llama-3.1-405B", false),
    model("NousResearch/Hermes-3-Llama-3.1-70B", "NousResearch/Hermes-3-Llama-3.1-70B", false),
    model("nvidia/Llama-3.3-Nemotron-Super-49B-v1.5", "nvidia/Llama-3.3-Nemotron-Super-49B-v1.5", false),
    model("nvidia/llama-nemotron-embed-vl-1b-v2", "nvidia/llama-nemotron-embed-vl-1b-v2", false),
    model("nvidia/Nemotron-3-Nano-30B-A3B", "nvidia/Nemotron-3-Nano-30B-A3B", true),
    model("nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning", "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning", true),
    model("nvidia/NVIDIA-Nemotron-3-Super-120B-A12B", "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B", true),
    model("nvidia/NVIDIA-Nemotron-Nano-9B-v2", "nvidia/NVIDIA-Nemotron-Nano-9B-v2", false),
    model("openai/gpt-oss-120b", "openai/gpt-oss-120b", true),
    model("openai/gpt-oss-120b-Turbo", "openai/gpt-oss-120b-Turbo", true),
    model("openai/gpt-oss-20b", "openai/gpt-oss-20b", true),
    model("PrunaAI/p-image", "PrunaAI/p-image", false),
    model("PrunaAI/p-image-Edit", "PrunaAI/p-image-Edit", false),
    model("Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit", false),
    model("Qwen/Qwen-Image-Edit-Max", "Qwen/Qwen-Image-Edit-Max", false),
    model("Qwen/Qwen-Image-Max", "Qwen/Qwen-Image-Max", false),
    model("Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-72B-Instruct", false),
    model("Qwen/Qwen3-14B", "Qwen/Qwen3-14B", false),
    model("Qwen/Qwen3-235B-A22B-Instruct-2507", "Qwen/Qwen3-235B-A22B-Instruct-2507", false),
    model("Qwen/Qwen3-235B-A22B-Thinking-2507", "Qwen/Qwen3-235B-A22B-Thinking-2507", true),
    model("Qwen/Qwen3-30B-A3B", "Qwen/Qwen3-30B-A3B", false),
    model("Qwen/Qwen3-32B", "Qwen/Qwen3-32B", false),
    model("Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo", "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo", false),
    model("Qwen/Qwen3-Embedding-0.6B", "Qwen/Qwen3-Embedding-0.6B", false),
    model("Qwen/Qwen3-Embedding-0.6B-batch", "Qwen/Qwen3-Embedding-0.6B-batch", false),
    model("Qwen/Qwen3-Embedding-4B", "Qwen/Qwen3-Embedding-4B", false),
    model("Qwen/Qwen3-Embedding-4B-batch", "Qwen/Qwen3-Embedding-4B-batch", false),
    model("Qwen/Qwen3-Embedding-8B", "Qwen/Qwen3-Embedding-8B", false),
    model("Qwen/Qwen3-Embedding-8B-batch", "Qwen/Qwen3-Embedding-8B-batch", false),
    model("Qwen/Qwen3-Max", "Qwen/Qwen3-Max", false),
    model("Qwen/Qwen3-Max-Thinking", "Qwen/Qwen3-Max-Thinking", true),
    model("Qwen/Qwen3-Next-80B-A3B-Instruct", "Qwen/Qwen3-Next-80B-A3B-Instruct", false),
    model("Qwen/Qwen3-VL-235B-A22B-Instruct", "Qwen/Qwen3-VL-235B-A22B-Instruct", false),
    model("Qwen/Qwen3-VL-30B-A3B-Instruct", "Qwen/Qwen3-VL-30B-A3B-Instruct", false),
    model("Qwen/Qwen3.5-0.8B", "Qwen/Qwen3.5-0.8B", true),
    model("Qwen/Qwen3.5-122B-A10B", "Qwen/Qwen3.5-122B-A10B", true),
    model("Qwen/Qwen3.5-27B", "Qwen/Qwen3.5-27B", true),
    model("Qwen/Qwen3.5-2B", "Qwen/Qwen3.5-2B", true),
    model("Qwen/Qwen3.5-35B-A3B", "Qwen/Qwen3.5-35B-A3B", true),
    model("Qwen/Qwen3.5-397B-A17B", "Qwen/Qwen3.5-397B-A17B", true),
    model("Qwen/Qwen3.5-4B", "Qwen/Qwen3.5-4B", true),
    model("Qwen/Qwen3.5-9B", "Qwen/Qwen3.5-9B", true),
    model("Qwen/Qwen3.6-27B", "Qwen/Qwen3.6-27B", false),
    model("Qwen/Qwen3.6-35B-A3B", "Qwen/Qwen3.6-35B-A3B", false),
    model("Sao10K/L3-8B-Lunaris-v1-Turbo", "Sao10K/L3-8B-Lunaris-v1-Turbo", false),
    model("Sao10K/L3.1-70B-Euryale-v2.2", "Sao10K/L3.1-70B-Euryale-v2.2", false),
    model("sentence-transformers/all-MiniLM-L12-v2", "sentence-transformers/all-MiniLM-L12-v2", false),
    model("sentence-transformers/all-MiniLM-L6-v2", "sentence-transformers/all-MiniLM-L6-v2", false),
    model("sentence-transformers/all-mpnet-base-v2", "sentence-transformers/all-mpnet-base-v2", false),
    model("sentence-transformers/clip-ViT-B-32", "sentence-transformers/clip-ViT-B-32", false),
    model(
      "sentence-transformers/clip-ViT-B-32-multilingual-v1",
      "sentence-transformers/clip-ViT-B-32-multilingual-v1",
      false,
    ),
    model(
      "sentence-transformers/multi-qa-mpnet-base-dot-v1",
      "sentence-transformers/multi-qa-mpnet-base-dot-v1",
      false,
    ),
    model("sentence-transformers/paraphrase-MiniLM-L6-v2", "sentence-transformers/paraphrase-MiniLM-L6-v2", false),
    model("shibing624/text2vec-base-chinese", "shibing624/text2vec-base-chinese", false),
    model("stabilityai/sdxl-turbo", "stabilityai/sdxl-turbo", false),
    model("stepfun-ai/Step-3.5-Flash", "stepfun-ai/Step-3.5-Flash", false),
    model("thenlper/gte-base", "thenlper/gte-base", false),
    model("thenlper/gte-large", "thenlper/gte-large", false),
    model("Wan-AI/Wan2.6-Image-Edit", "Wan-AI/Wan2.6-Image-Edit", false),
    model("Wan-AI/Wan2.6-T2I", "Wan-AI/Wan2.6-T2I", false),
    model("Wan-AI/Wan2.7-Image-Edit", "Wan-AI/Wan2.7-Image-Edit", false),
    model("XiaomiMiMo/MiMo-V2.5", "XiaomiMiMo/MiMo-V2.5", false),
    model("XiaomiMiMo/MiMo-V2.5-Pro", "XiaomiMiMo/MiMo-V2.5-Pro", false),
    model("zai-org/GLM-4.6", "zai-org/GLM-4.6", true),
    model("zai-org/GLM-4.7", "zai-org/GLM-4.7", true),
    model("zai-org/GLM-4.7-Flash", "zai-org/GLM-4.7-Flash", true),
    model("zai-org/GLM-5", "zai-org/GLM-5", true),
    model("zai-org/GLM-5.1", "zai-org/GLM-5.1", true),
  ],
}
