import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const HuggingfacePreset: ProviderPreset = {
  id: "huggingface",
  name: "Hugging Face Router",
  baseURL: "https://router.huggingface.co/v1",
  note: "Seeded from Hugging Face Router official /models catalog (117 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("aisingapore/Gemma-SEA-LION-v4-27B-IT", "aisingapore/Gemma-SEA-LION-v4-27B-IT", false),
    model("aisingapore/Qwen-SEA-LION-v4-32B-IT", "aisingapore/Qwen-SEA-LION-v4-32B-IT", false),
    model("allenai/Olmo-3-7B-Instruct", "allenai/Olmo-3-7B-Instruct", false),
    model("alpindale/WizardLM-2-8x22B", "alpindale/WizardLM-2-8x22B", false),
    model("baidu/ERNIE-4.5-300B-A47B-Base-PT", "baidu/ERNIE-4.5-300B-A47B-Base-PT", false),
    model("baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", false),
    model("CohereLabs/aya-expanse-32b", "CohereLabs/aya-expanse-32b", false),
    model("CohereLabs/aya-vision-32b", "CohereLabs/aya-vision-32b", false),
    model("CohereLabs/c4ai-command-a-03-2025", "CohereLabs/c4ai-command-a-03-2025", false),
    model("CohereLabs/c4ai-command-r-08-2024", "CohereLabs/c4ai-command-r-08-2024", false),
    model("CohereLabs/c4ai-command-r7b-12-2024", "CohereLabs/c4ai-command-r7b-12-2024", false),
    model("CohereLabs/c4ai-command-r7b-arabic-02-2025", "CohereLabs/c4ai-command-r7b-arabic-02-2025", false),
    model("CohereLabs/command-a-reasoning-08-2025", "CohereLabs/command-a-reasoning-08-2025", false),
    model("CohereLabs/command-a-vision-07-2025", "CohereLabs/command-a-vision-07-2025", false),
    model("CohereLabs/tiny-aya-earth", "CohereLabs/tiny-aya-earth", false),
    model("CohereLabs/tiny-aya-fire", "CohereLabs/tiny-aya-fire", false),
    model("CohereLabs/tiny-aya-global", "CohereLabs/tiny-aya-global", false),
    model("CohereLabs/tiny-aya-water", "CohereLabs/tiny-aya-water", false),
    model("deepcogito/cogito-671b-v2.1", "deepcogito/cogito-671b-v2.1", false),
    model("deepcogito/cogito-671b-v2.1-FP8", "deepcogito/cogito-671b-v2.1-FP8", false),
    model("deepseek-ai/DeepSeek-Prover-V2-671B", "deepseek-ai/DeepSeek-Prover-V2-671B", false),
    model("deepseek-ai/DeepSeek-R1", "deepseek-ai/DeepSeek-R1", true),
    model("deepseek-ai/DeepSeek-R1-0528", "deepseek-ai/DeepSeek-R1-0528", true),
    model("deepseek-ai/DeepSeek-R1-Distill-Llama-70B", "deepseek-ai/DeepSeek-R1-Distill-Llama-70B", true),
    model("deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepSeek-V3", false),
    model("deepseek-ai/DeepSeek-V3-0324", "deepseek-ai/DeepSeek-V3-0324", false),
    model("deepseek-ai/DeepSeek-V3.1", "deepseek-ai/DeepSeek-V3.1", true),
    model("deepseek-ai/DeepSeek-V3.1-Terminus", "deepseek-ai/DeepSeek-V3.1-Terminus", true),
    model("deepseek-ai/DeepSeek-V3.2", "deepseek-ai/DeepSeek-V3.2", true),
    model("deepseek-ai/DeepSeek-V3.2-Exp", "deepseek-ai/DeepSeek-V3.2-Exp", true),
    model("deepseek-ai/DeepSeek-V4-Flash", "deepseek-ai/DeepSeek-V4-Flash", true),
    model("deepseek-ai/DeepSeek-V4-Pro", "deepseek-ai/DeepSeek-V4-Pro", true),
    model("dicta-il/DictaLM-3.0-24B-Thinking", "dicta-il/DictaLM-3.0-24B-Thinking", false),
    model("EssentialAI/rnj-1-instruct", "EssentialAI/rnj-1-instruct", false),
    model("google/gemma-3-27b-it", "google/gemma-3-27b-it", false),
    model("google/gemma-3n-E4B-it", "google/gemma-3n-E4B-it", false),
    model("google/gemma-4-26B-A4B-it", "google/gemma-4-26B-A4B-it", false),
    model("google/gemma-4-31B-it", "google/gemma-4-31B-it", false),
    model("inclusionAI/Ling-2.6-1T", "inclusionAI/Ling-2.6-1T", false),
    model("katanemo/Arch-Router-1.5B", "katanemo/Arch-Router-1.5B", false),
    model("meta-llama/Llama-3.1-70B-Instruct", "meta-llama/Llama-3.1-70B-Instruct", false),
    model("meta-llama/Llama-3.1-8B-Instruct", "meta-llama/Llama-3.1-8B-Instruct", false),
    model("meta-llama/Llama-3.2-1B-Instruct", "meta-llama/Llama-3.2-1B-Instruct", false),
    model("meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Llama-3.3-70B-Instruct", false),
    model("meta-llama/Llama-4-Maverick-17B-128E-Instruct", "meta-llama/Llama-4-Maverick-17B-128E-Instruct", false),
    model(
      "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
      "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
      false,
    ),
    model("meta-llama/Llama-4-Scout-17B-16E-Instruct", "meta-llama/Llama-4-Scout-17B-16E-Instruct", false),
    model("meta-llama/Llama-Guard-4-12B", "meta-llama/Llama-Guard-4-12B", false),
    model("meta-llama/Meta-Llama-3-70B-Instruct", "meta-llama/Meta-Llama-3-70B-Instruct", false),
    model("meta-llama/Meta-Llama-3-8B-Instruct", "meta-llama/Meta-Llama-3-8B-Instruct", false),
    model("MiniMaxAI/MiniMax-M1-80k", "MiniMaxAI/MiniMax-M1-80k", false),
    model("MiniMaxAI/MiniMax-M2", "MiniMaxAI/MiniMax-M2", false),
    model("MiniMaxAI/MiniMax-M2.1", "MiniMaxAI/MiniMax-M2.1", true),
    model("MiniMaxAI/MiniMax-M2.5", "MiniMaxAI/MiniMax-M2.5", true),
    model("MiniMaxAI/MiniMax-M2.7", "MiniMaxAI/MiniMax-M2.7", true),
    model("moonshotai/Kimi-K2-Instruct", "moonshotai/Kimi-K2-Instruct", false),
    model("moonshotai/Kimi-K2-Instruct-0905", "moonshotai/Kimi-K2-Instruct-0905", false),
    model("moonshotai/Kimi-K2-Thinking", "moonshotai/Kimi-K2-Thinking", true),
    model("moonshotai/Kimi-K2.5", "moonshotai/Kimi-K2.5", true),
    model("moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.6", true),
    model("NousResearch/Hermes-2-Pro-Llama-3-8B", "NousResearch/Hermes-2-Pro-Llama-3-8B", false),
    model("openai/gpt-oss-120b", "openai/gpt-oss-120b", true),
    model("openai/gpt-oss-20b", "openai/gpt-oss-20b", true),
    model("openai/gpt-oss-safeguard-20b", "openai/gpt-oss-safeguard-20b", true),
    model("Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-72B-Instruct", false),
    model("Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-7B-Instruct", false),
    model("Qwen/Qwen2.5-Coder-32B-Instruct", "Qwen/Qwen2.5-Coder-32B-Instruct", false),
    model("Qwen/Qwen2.5-VL-72B-Instruct", "Qwen/Qwen2.5-VL-72B-Instruct", false),
    model("Qwen/Qwen3-235B-A22B", "Qwen/Qwen3-235B-A22B", false),
    model("Qwen/Qwen3-235B-A22B-Instruct-2507", "Qwen/Qwen3-235B-A22B-Instruct-2507", false),
    model("Qwen/Qwen3-235B-A22B-Thinking-2507", "Qwen/Qwen3-235B-A22B-Thinking-2507", true),
    model("Qwen/Qwen3-30B-A3B", "Qwen/Qwen3-30B-A3B", false),
    model("Qwen/Qwen3-32B", "Qwen/Qwen3-32B", false),
    model("Qwen/Qwen3-8B", "Qwen/Qwen3-8B", false),
    model("Qwen/Qwen3-Coder-30B-A3B-Instruct", "Qwen/Qwen3-Coder-30B-A3B-Instruct", false),
    model("Qwen/Qwen3-Coder-480B-A35B-Instruct", "Qwen/Qwen3-Coder-480B-A35B-Instruct", false),
    model("Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", false),
    model("Qwen/Qwen3-Coder-Next", "Qwen/Qwen3-Coder-Next", false),
    model("Qwen/Qwen3-Coder-Next-FP8", "Qwen/Qwen3-Coder-Next-FP8", false),
    model("Qwen/Qwen3-Next-80B-A3B-Instruct", "Qwen/Qwen3-Next-80B-A3B-Instruct", false),
    model("Qwen/Qwen3-Next-80B-A3B-Thinking", "Qwen/Qwen3-Next-80B-A3B-Thinking", true),
    model("Qwen/Qwen3-VL-235B-A22B-Instruct", "Qwen/Qwen3-VL-235B-A22B-Instruct", false),
    model("Qwen/Qwen3-VL-235B-A22B-Thinking", "Qwen/Qwen3-VL-235B-A22B-Thinking", true),
    model("Qwen/Qwen3-VL-30B-A3B-Instruct", "Qwen/Qwen3-VL-30B-A3B-Instruct", false),
    model("Qwen/Qwen3-VL-30B-A3B-Thinking", "Qwen/Qwen3-VL-30B-A3B-Thinking", true),
    model("Qwen/Qwen3-VL-8B-Instruct", "Qwen/Qwen3-VL-8B-Instruct", false),
    model("Qwen/Qwen3.5-122B-A10B", "Qwen/Qwen3.5-122B-A10B", true),
    model("Qwen/Qwen3.5-27B", "Qwen/Qwen3.5-27B", true),
    model("Qwen/Qwen3.5-35B-A3B", "Qwen/Qwen3.5-35B-A3B", true),
    model("Qwen/Qwen3.5-397B-A17B", "Qwen/Qwen3.5-397B-A17B", true),
    model("Qwen/Qwen3.5-9B", "Qwen/Qwen3.5-9B", true),
    model("Qwen/Qwen3.6-35B-A3B", "Qwen/Qwen3.6-35B-A3B", false),
    model("Sao10K/L3-70B-Euryale-v2.1", "Sao10K/L3-70B-Euryale-v2.1", false),
    model("Sao10K/L3-8B-Lunaris-v1", "Sao10K/L3-8B-Lunaris-v1", false),
    model("Sao10K/L3-8B-Stheno-v3.2", "Sao10K/L3-8B-Stheno-v3.2", false),
    model("stepfun-ai/Step-3.5-Flash", "stepfun-ai/Step-3.5-Flash", false),
    model("swiss-ai/Apertus-70B-Instruct-2509", "swiss-ai/Apertus-70B-Instruct-2509", false),
    model("swiss-ai/Apertus-8B-Instruct-2509", "swiss-ai/Apertus-8B-Instruct-2509", false),
    model("utter-project/EuroLLM-22B-Instruct-2512", "utter-project/EuroLLM-22B-Instruct-2512", false),
    model("XiaomiMiMo/MiMo-V2-Flash", "XiaomiMiMo/MiMo-V2-Flash", false),
    model("zai-org/AutoGLM-Phone-9B-Multilingual", "zai-org/AutoGLM-Phone-9B-Multilingual", false),
    model("zai-org/GLM-4-32B-0414", "zai-org/GLM-4-32B-0414", false),
    model("zai-org/GLM-4.5", "zai-org/GLM-4.5", true),
    model("zai-org/GLM-4.5-Air", "zai-org/GLM-4.5-Air", true),
    model("zai-org/GLM-4.5V", "zai-org/GLM-4.5V", true),
    model("zai-org/GLM-4.5V-FP8", "zai-org/GLM-4.5V-FP8", true),
    model("zai-org/GLM-4.6", "zai-org/GLM-4.6", true),
    model("zai-org/GLM-4.6-FP8", "zai-org/GLM-4.6-FP8", true),
    model("zai-org/GLM-4.6V", "zai-org/GLM-4.6V", true),
    model("zai-org/GLM-4.6V-Flash", "zai-org/GLM-4.6V-Flash", true),
    model("zai-org/GLM-4.6V-FP8", "zai-org/GLM-4.6V-FP8", true),
    model("zai-org/GLM-4.7", "zai-org/GLM-4.7", true),
    model("zai-org/GLM-4.7-Flash", "zai-org/GLM-4.7-Flash", true),
    model("zai-org/GLM-4.7-FP8", "zai-org/GLM-4.7-FP8", true),
    model("zai-org/GLM-5", "zai-org/GLM-5", true),
    model("zai-org/GLM-5.1", "zai-org/GLM-5.1", true),
    model("zai-org/GLM-5.1-FP8", "zai-org/GLM-5.1-FP8", true),
  ],
}
