import type { ProviderPreset } from "./types"

export const LitellmPreset: ProviderPreset = {
  id: "litellm",
  name: "LiteLLM",
  baseURL: "http://localhost:4000/v1",
  note: "Select routed models from Cline local LiteLLM defaults or fetch your LiteLLM server.",
  local: true,
  models: [
    { id: "openrouter/auto", name: "OpenRouter Auto" },
    { id: "anthropic/claude-sonnet-4.5", name: "Claude Sonnet 4.5", reasoning: true },
    { id: "google/gemini-3.1-pro-preview", name: "Google / Gemini 3.1 Pro Preview", reasoning: true },
    { id: "anthropic/claude-sonnet-4.6", name: "Anthropic / Claude Sonnet 4.6", reasoning: true },
    { id: "anthropic/claude-opus-4.6", name: "Anthropic / Claude Opus 4.6", reasoning: true },
    { id: "openai/gpt-5.3-codex", name: "Openai / Gpt 5.3 Codex", reasoning: true },
    { id: "kwaipilot/kat-coder-pro", name: "Kwaipilot / Kat Coder Pro" },
    { id: "arcee-ai/trinity-large-preview:free", name: "Arcee Ai / Trinity Large Preview Free" },
    { id: "moonshotai/kimi-k2:exacto", name: "Moonshotai / Kimi K2 Exacto" },
    { id: "z-ai/glm-4.6:exacto", name: "Z Ai / Glm 4.6 Exacto", reasoning: true },
    { id: "deepseek/deepseek-v3.1-terminus:exacto", name: "Deepseek / Deepseek V3.1 Terminus Exacto" },
    { id: "qwen/qwen3-coder:exacto", name: "Qwen / Qwen3 Coder Exacto", reasoning: true },
    { id: "openai/gpt-oss-120b:exacto", name: "Openai / Gpt Oss 120b Exacto", reasoning: true },
    { id: "moonshotai/kimi-k2", name: "Moonshotai / Kimi K2" },
    { id: "qwen/qwen3-coder", name: "Qwen / Qwen3 Coder", reasoning: true },
    { id: "qwen/qwen3-235b-a22b-thinking-2507", name: "Qwen / Qwen3 235b A22b Thinking 2507", reasoning: true },
    { id: "qwen/qwen3-235b-a22b-07-25", name: "Qwen / Qwen3 235b A22b 07 25", reasoning: true },
    { id: "qwen/qwen3-30b-a3b-thinking-2507", name: "Qwen / Qwen3 30b A3b Thinking 2507", reasoning: true },
    { id: "qwen/qwen3-30b-a3b-instruct-2507", name: "Qwen / Qwen3 30b A3b Instruct 2507", reasoning: true },
    { id: "qwen/qwen3-30b-a3b:free", name: "Qwen / Qwen3 30b A3b Free", reasoning: true },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "Qwen / Qwen3 Next 80b A3b Thinking", reasoning: true },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen / Qwen3 Next 80b A3b Instruct", reasoning: true },
    { id: "qwen/qwen3-max", name: "Qwen / Qwen3 Max", reasoning: true },
    { id: "deepseek/deepseek-v3.2-exp", name: "Deepseek / Deepseek V3.2 Exp" },
    { id: "z-ai/glm-4.6", name: "Z Ai / Glm 4.6", reasoning: true },
    { id: "z-ai/glm-4.5v", name: "Z Ai / Glm 4.5v", reasoning: true },
    { id: "z-ai/glm-4.5", name: "Z Ai / Glm 4.5", reasoning: true },
    { id: "z-ai/glm-4.5-air", name: "Z Ai / Glm 4.5 Air", reasoning: true },
  ],
}
