import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const NousPreset: ProviderPreset = {
  id: "nous",
  name: "Nous Research",
  baseURL: "https://inference-api.nousresearch.com/v1",
  note: "Seeded from Nous Research official /models catalog (406 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("~anthropic/claude-haiku-latest", "Anthropic Claude Haiku Latest", false),
    model("~anthropic/claude-opus-latest", "Anthropic: Claude Opus Latest", false),
    model("~anthropic/claude-sonnet-latest", "Anthropic Claude Sonnet Latest", false),
    model("~google/gemini-flash-latest", "Google Gemini Flash Latest", false),
    model("~google/gemini-pro-latest", "Google Gemini Pro Latest", false),
    model("~moonshotai/kimi-latest", "MoonshotAI Kimi Latest", false),
    model("~openai/gpt-latest", "OpenAI GPT Latest", false),
    model("~openai/gpt-mini-latest", "OpenAI GPT Mini Latest", false),
    model("ai21/jamba-large-1.7", "AI21: Jamba Large 1.7", false),
    model("aion-labs/aion-1.0", "AionLabs: Aion-1.0", false),
    model("aion-labs/aion-1.0-mini", "AionLabs: Aion-1.0-Mini", false),
    model("aion-labs/aion-2.0", "AionLabs: Aion-2.0", false),
    model("aion-labs/aion-rp-llama-3.1-8b", "AionLabs: Aion-RP 1.0 (8B)", false),
    model("alfredpros/codellama-7b-instruct-solidity", "AlfredPros: CodeLLaMa 7B Instruct Solidity", false),
    model("alibaba/tongyi-deepresearch-30b-a3b", "Tongyi DeepResearch 30B A3B", false),
    model("alibaba/wan-2.6", "Alibaba: Wan 2.6", false),
    model("alibaba/wan-2.7", "Alibaba: Wan 2.7", false),
    model("allenai/olmo-3-32b-think", "AllenAI: Olmo 3 32B Think", false),
    model("alpindale/goliath-120b", "Goliath 120B", false),
    model("amazon/nova-2-lite-v1", "Amazon: Nova 2 Lite", false),
    model("amazon/nova-lite-v1", "Amazon: Nova Lite 1.0", false),
    model("amazon/nova-micro-v1", "Amazon: Nova Micro 1.0", false),
    model("amazon/nova-premier-v1", "Amazon: Nova Premier 1.0", false),
    model("amazon/nova-pro-v1", "Amazon: Nova Pro 1.0", false),
    model("anthracite-org/magnum-v4-72b", "Magnum v4 72B", false),
    model("anthropic/claude-3-haiku", "Anthropic: Claude 3 Haiku", false),
    model("anthropic/claude-3.5-haiku", "Anthropic: Claude 3.5 Haiku", false),
    model("anthropic/claude-3.7-sonnet", "Anthropic: Claude 3.7 Sonnet", true),
    model("anthropic/claude-3.7-sonnet:thinking", "Anthropic: Claude 3.7 Sonnet (thinking)", true),
    model("anthropic/claude-haiku-4.5", "Anthropic: Claude Haiku 4.5", true),
    model("anthropic/claude-opus-4", "Anthropic: Claude Opus 4", true),
    model("anthropic/claude-opus-4.1", "Anthropic: Claude Opus 4.1", true),
    model("anthropic/claude-opus-4.5", "Anthropic: Claude Opus 4.5", true),
    model("anthropic/claude-opus-4.6", "Anthropic: Claude Opus 4.6", true),
    model("anthropic/claude-opus-4.6-fast", "Anthropic: Claude Opus 4.6 (Fast)", true),
    model("anthropic/claude-opus-4.7", "Anthropic: Claude Opus 4.7", true),
    model("anthropic/claude-sonnet-4", "Anthropic: Claude Sonnet 4", true),
    model("anthropic/claude-sonnet-4.5", "Anthropic: Claude Sonnet 4.5", true),
    model("anthropic/claude-sonnet-4.6", "Anthropic: Claude Sonnet 4.6", true),
    model("arcee-ai/coder-large", "Arcee AI: Coder Large", false),
    model("arcee-ai/maestro-reasoning", "Arcee AI: Maestro Reasoning", false),
    model("arcee-ai/spotlight", "Arcee AI: Spotlight", false),
    model("arcee-ai/trinity-large-preview", "Arcee AI: Trinity Large Preview", false),
    model("arcee-ai/trinity-large-thinking", "Arcee AI: Trinity Large Thinking", false),
    model("arcee-ai/trinity-mini", "Arcee AI: Trinity Mini", false),
    model("arcee-ai/virtuoso-large", "Arcee AI: Virtuoso Large", false),
    model("baai/bge-base-en-v1.5", "BAAI: bge-base-en-v1.5", false),
    model("baai/bge-large-en-v1.5", "BAAI: bge-large-en-v1.5", false),
    model("baai/bge-m3", "BAAI: bge-m3", false),
    model("baidu/ernie-4.5-21b-a3b", "Baidu: ERNIE 4.5 21B A3B", false),
    model("baidu/ernie-4.5-21b-a3b-thinking", "Baidu: ERNIE 4.5 21B A3B Thinking", false),
    model("baidu/ernie-4.5-300b-a47b", "Baidu: ERNIE 4.5 300B A47B", false),
    model("baidu/ernie-4.5-vl-28b-a3b", "Baidu: ERNIE 4.5 VL 28B A3B", false),
    model("baidu/ernie-4.5-vl-424b-a47b", "Baidu: ERNIE 4.5 VL 424B A47B", false),
    model("black-forest-labs/flux.2-flex", "Black Forest Labs: FLUX.2 Flex", false),
    model("black-forest-labs/flux.2-klein-4b", "Black Forest Labs: FLUX.2 Klein 4B", false),
    model("black-forest-labs/flux.2-max", "Black Forest Labs: FLUX.2 Max", false),
    model("black-forest-labs/flux.2-pro", "Black Forest Labs: FLUX.2 Pro", false),
    model("bytedance-seed/seed-1.6", "ByteDance Seed: Seed 1.6", false),
    model("bytedance-seed/seed-1.6-flash", "ByteDance Seed: Seed 1.6 Flash", false),
    model("bytedance-seed/seed-2.0-lite", "ByteDance Seed: Seed-2.0-Lite", false),
    model("bytedance-seed/seed-2.0-mini", "ByteDance Seed: Seed-2.0-Mini", false),
    model("bytedance-seed/seedream-4.5", "ByteDance Seed: Seedream 4.5", false),
    model("bytedance/seedance-1-5-pro", "ByteDance: Seedance 1.5 Pro", false),
    model("bytedance/seedance-2.0", "ByteDance: Seedance 2.0", false),
    model("bytedance/seedance-2.0-fast", "ByteDance: Seedance 2.0 Fast", false),
    model("bytedance/ui-tars-1.5-7b", "ByteDance: UI-TARS 7B", false),
    model("canopylabs/orpheus-3b-0.1-ft", "Canopy Labs: Orpheus 3B", false),
    model("cohere/command-a", "Cohere: Command A", false),
    model("cohere/command-r-08-2024", "Cohere: Command R (08-2024)", false),
    model("cohere/command-r-plus-08-2024", "Cohere: Command R+ (08-2024)", false),
    model("cohere/command-r7b-12-2024", "Cohere: Command R7B (12-2024)", false),
    model("cohere/rerank-4-fast", "Cohere: Rerank 4 Fast", false),
    model("cohere/rerank-4-pro", "Cohere: Rerank 4 Pro", false),
    model("cohere/rerank-v3.5", "Cohere: Rerank v3.5", false),
    model("deepcogito/cogito-v2.1-671b", "Deep Cogito: Cogito v2.1 671B", false),
    model("deepseek/deepseek-chat", "DeepSeek: DeepSeek V3", false),
    model("deepseek/deepseek-chat-v3-0324", "DeepSeek: DeepSeek V3 0324", false),
    model("deepseek/deepseek-chat-v3.1", "DeepSeek: DeepSeek V3.1", true),
    model("deepseek/deepseek-r1", "DeepSeek: R1", true),
    model("deepseek/deepseek-r1-0528", "DeepSeek: R1 0528", true),
    model("deepseek/deepseek-r1-distill-llama-70b", "DeepSeek: R1 Distill Llama 70B", true),
    model("deepseek/deepseek-r1-distill-qwen-32b", "DeepSeek: R1 Distill Qwen 32B", true),
    model("deepseek/deepseek-v3.1-terminus", "DeepSeek: DeepSeek V3.1 Terminus", true),
    model("deepseek/deepseek-v3.2", "DeepSeek: DeepSeek V3.2", true),
    model("deepseek/deepseek-v3.2-exp", "DeepSeek: DeepSeek V3.2 Exp", true),
    model("deepseek/deepseek-v3.2-speciale", "DeepSeek: DeepSeek V3.2 Speciale", true),
    model("deepseek/deepseek-v4-flash", "DeepSeek: DeepSeek V4 Flash", true),
    model("deepseek/deepseek-v4-pro", "DeepSeek: DeepSeek V4 Pro", true),
    model("essentialai/rnj-1-instruct", "EssentialAI: Rnj 1 Instruct", false),
    model("google/chirp-3", "Google: Chirp 3", false),
    model("google/gemini-2.0-flash-001", "Google: Gemini 2.0 Flash", false),
    model("google/gemini-2.0-flash-lite-001", "Google: Gemini 2.0 Flash Lite", false),
    model("google/gemini-2.5-flash", "Google: Gemini 2.5 Flash", true),
    model("google/gemini-2.5-flash-image", "Google: Nano Banana (Gemini 2.5 Flash Image)", true),
    model("google/gemini-2.5-flash-lite", "Google: Gemini 2.5 Flash Lite", true),
    model("google/gemini-2.5-flash-lite-preview-09-2025", "Google: Gemini 2.5 Flash Lite Preview 09-2025", true),
    model("google/gemini-2.5-pro", "Google: Gemini 2.5 Pro", true),
    model("google/gemini-2.5-pro-preview", "Google: Gemini 2.5 Pro Preview 06-05", true),
    model("google/gemini-2.5-pro-preview-05-06", "Google: Gemini 2.5 Pro Preview 05-06", true),
    model("google/gemini-3-flash-preview", "Google: Gemini 3 Flash Preview", true),
    model("google/gemini-3-pro-image-preview", "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)", true),
    model("google/gemini-3.1-flash-image-preview", "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)", true),
    model("google/gemini-3.1-flash-lite", "Google: Gemini 3.1 Flash Lite", true),
    model("google/gemini-3.1-flash-lite-preview", "Google: Gemini 3.1 Flash Lite Preview", true),
    model("google/gemini-3.1-flash-tts-preview", "Google: Gemini 3.1 Flash TTS Preview", true),
    model("google/gemini-3.1-pro-preview", "Google: Gemini 3.1 Pro Preview", true),
    model("google/gemini-3.1-pro-preview-customtools", "Google: Gemini 3.1 Pro Preview Custom Tools", true),
    model("google/gemini-embedding-001", "Google: Gemini Embedding 001", false),
    model("google/gemini-embedding-2-preview", "Google: Gemini Embedding 2 Preview", false),
    model("google/gemma-2-27b-it", "Google: Gemma 2 27B", false),
    model("google/gemma-3-12b-it", "Google: Gemma 3 12B", false),
    model("google/gemma-3-27b-it", "Google: Gemma 3 27B", false),
    model("google/gemma-3-4b-it", "Google: Gemma 3 4B", false),
    model("google/gemma-3n-e4b-it", "Google: Gemma 3n 4B", false),
    model("google/gemma-4-26b-a4b-it", "Google: Gemma 4 26B A4B", false),
    model("google/gemma-4-31b-it", "Google: Gemma 4 31B", false),
    model("google/lyria-3-clip-preview", "Google: Lyria 3 Clip Preview", false),
    model("google/lyria-3-pro-preview", "Google: Lyria 3 Pro Preview", false),
    model("google/veo-3.1", "Google: Veo 3.1", false),
    model("google/veo-3.1-fast", "Google: Veo 3.1 Fast", false),
    model("google/veo-3.1-lite", "Google: Veo 3.1 Lite", false),
    model("gryphe/mythomax-l2-13b", "MythoMax 13B", false),
    model("hexgrad/kokoro-82m", "hexgrad: Kokoro 82M", false),
    model("ibm-granite/granite-4.0-h-micro", "IBM: Granite 4.0 Micro", false),
    model("ibm-granite/granite-4.1-8b", "IBM: Granite 4.1 8B", false),
    model("inception/mercury-2", "Inception: Mercury 2", false),
    model("inclusionai/ling-2.6-1t", "inclusionAI: Ling-2.6-1T", false),
    model("inclusionai/ling-2.6-flash", "inclusionAI: Ling-2.6-flash", false),
    model("inflection/inflection-3-pi", "Inflection: Inflection 3 Pi", false),
    model("inflection/inflection-3-productivity", "Inflection: Inflection 3 Productivity", false),
    model("intfloat/e5-base-v2", "Intfloat: E5-Base-v2", false),
    model("intfloat/e5-large-v2", "Intfloat: E5-Large-v2", false),
    model("intfloat/multilingual-e5-large", "Intfloat: Multilingual-E5-Large", false),
    model("kwaipilot/kat-coder-pro-v2", "Kwaipilot: KAT-Coder-Pro V2", false),
    model("kwaivgi/kling-v3.0-pro", "Kling: Video v3.0 Pro", false),
    model("kwaivgi/kling-v3.0-std", "Kling: Video v3.0 Standard", false),
    model("kwaivgi/kling-video-o1", "Kling: Video O1", true),
    model("liquid/lfm-2-24b-a2b", "LiquidAI: LFM2-24B-A2B", false),
    model("mancer/weaver", "Mancer: Weaver (alpha)", false),
    model("meta-llama/llama-3-70b-instruct", "Meta: Llama 3 70B Instruct", false),
    model("meta-llama/llama-3-8b-instruct", "Meta: Llama 3 8B Instruct", false),
    model("meta-llama/llama-3.1-70b-instruct", "Meta: Llama 3.1 70B Instruct", false),
    model("meta-llama/llama-3.1-8b-instruct", "Meta: Llama 3.1 8B Instruct", false),
    model("meta-llama/llama-3.2-11b-vision-instruct", "Meta: Llama 3.2 11B Vision Instruct", false),
    model("meta-llama/llama-3.2-1b-instruct", "Meta: Llama 3.2 1B Instruct", false),
    model("meta-llama/llama-3.2-3b-instruct", "Meta: Llama 3.2 3B Instruct", false),
    model("meta-llama/llama-3.3-70b-instruct", "Meta: Llama 3.3 70B Instruct", false),
    model("meta-llama/llama-4-maverick", "Meta: Llama 4 Maverick", false),
    model("meta-llama/llama-4-scout", "Meta: Llama 4 Scout", false),
    model("meta-llama/llama-guard-3-8b", "Llama Guard 3 8B", false),
    model("meta-llama/llama-guard-4-12b", "Meta: Llama Guard 4 12B", false),
    model("microsoft/phi-4", "Microsoft: Phi 4", false),
    model("microsoft/phi-4-mini-instruct", "Microsoft: Phi 4 Mini Instruct", false),
    model("microsoft/wizardlm-2-8x22b", "WizardLM-2 8x22B", false),
    model("minimax/hailuo-2.3", "MiniMax: Hailuo 2.3", false),
    model("minimax/minimax-01", "MiniMax: MiniMax-01", false),
    model("minimax/minimax-m1", "MiniMax: MiniMax M1", false),
    model("minimax/minimax-m2", "MiniMax: MiniMax M2", false),
    model("minimax/minimax-m2-her", "MiniMax: MiniMax M2-her", false),
    model("minimax/minimax-m2.1", "MiniMax: MiniMax M2.1", true),
    model("minimax/minimax-m2.5", "MiniMax: MiniMax M2.5", true),
    model("minimax/minimax-m2.7", "MiniMax: MiniMax M2.7", true),
    model("mistralai/codestral-2508", "Mistral: Codestral 2508", false),
    model("mistralai/codestral-embed-2505", "Mistral: Codestral Embed 2505", false),
    model("mistralai/devstral-2512", "Mistral: Devstral 2 2512", false),
    model("mistralai/devstral-medium", "Mistral: Devstral Medium", false),
    model("mistralai/devstral-small", "Mistral: Devstral Small 1.1", false),
    model("mistralai/ministral-14b-2512", "Mistral: Ministral 3 14B 2512", false),
    model("mistralai/ministral-3b-2512", "Mistral: Ministral 3 3B 2512", false),
    model("mistralai/ministral-8b-2512", "Mistral: Ministral 3 8B 2512", false),
    model("mistralai/mistral-7b-instruct-v0.1", "Mistral: Mistral 7B Instruct v0.1", false),
    model("mistralai/mistral-embed-2312", "Mistral: Mistral Embed 2312", false),
    model("mistralai/mistral-large", "Mistral Large", false),
    model("mistralai/mistral-large-2407", "Mistral Large 2407", false),
    model("mistralai/mistral-large-2411", "Mistral Large 2411", false),
    model("mistralai/mistral-large-2512", "Mistral: Mistral Large 3 2512", false),
    model("mistralai/mistral-medium-3", "Mistral: Mistral Medium 3", false),
    model("mistralai/mistral-medium-3-5", "Mistral: Mistral Medium 3.5", false),
    model("mistralai/mistral-medium-3.1", "Mistral: Mistral Medium 3.1", false),
    model("mistralai/mistral-nemo", "Mistral: Mistral Nemo", false),
    model("mistralai/mistral-saba", "Mistral: Saba", false),
    model("mistralai/mistral-small-24b-instruct-2501", "Mistral: Mistral Small 3", false),
    model("mistralai/mistral-small-2603", "Mistral: Mistral Small 4", false),
    model("mistralai/mistral-small-3.1-24b-instruct", "Mistral: Mistral Small 3.1 24B", false),
    model("mistralai/mistral-small-3.2-24b-instruct", "Mistral: Mistral Small 3.2 24B", false),
    model("mistralai/mixtral-8x22b-instruct", "Mistral: Mixtral 8x22B Instruct", false),
    model("mistralai/pixtral-large-2411", "Mistral: Pixtral Large 2411", false),
    model("mistralai/voxtral-mini-tts-2603", "Mistral: Voxtral Mini TTS", false),
    model("mistralai/voxtral-small-24b-2507", "Mistral: Voxtral Small 24B 2507", false),
    model("moonshotai/kimi-k2", "MoonshotAI: Kimi K2 0711", false),
    model("moonshotai/kimi-k2-0905", "MoonshotAI: Kimi K2 0905", false),
    model("moonshotai/kimi-k2-thinking", "MoonshotAI: Kimi K2 Thinking", true),
    model("moonshotai/kimi-k2.5", "MoonshotAI: Kimi K2.5", true),
    model("moonshotai/kimi-k2.6", "MoonshotAI: Kimi K2.6", true),
    model("morph/morph-v3-fast", "Morph: Morph V3 Fast", false),
    model("morph/morph-v3-large", "Morph: Morph V3 Large", false),
    model("nex-agi/deepseek-v3.1-nex-n1", "Nex AGI: DeepSeek V3.1 Nex N1", true),
    model("nousresearch/hermes-2-pro-llama-3-8b", "NousResearch: Hermes 2 Pro - Llama-3 8B", false),
    model("nousresearch/hermes-3-llama-3.1-405b", "Nous: Hermes 3 405B Instruct", false),
    model("nousresearch/hermes-3-llama-3.1-70b", "Nous: Hermes 3 70B Instruct", false),
    model("nousresearch/hermes-4-405b", "Nous: Hermes 4 405B", false),
    model("nousresearch/hermes-4-70b", "Nous: Hermes 4 70B", false),
    model("nvidia/llama-3.3-nemotron-super-49b-v1.5", "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5", false),
    model("nvidia/nemotron-3-nano-30b-a3b", "NVIDIA: Nemotron 3 Nano 30B A3B", true),
    model("nvidia/nemotron-3-super-120b-a12b", "NVIDIA: Nemotron 3 Super", true),
    model("nvidia/nemotron-nano-9b-v2", "NVIDIA: Nemotron Nano 9B V2", false),
    model("openai/gpt-3.5-turbo", "OpenAI: GPT-3.5 Turbo", false),
    model("openai/gpt-3.5-turbo-0613", "OpenAI: GPT-3.5 Turbo (older v0613)", false),
    model("openai/gpt-3.5-turbo-16k", "OpenAI: GPT-3.5 Turbo 16k", false),
    model("openai/gpt-3.5-turbo-instruct", "OpenAI: GPT-3.5 Turbo Instruct", false),
    model("openai/gpt-4", "OpenAI: GPT-4", false),
    model("openai/gpt-4-0314", "OpenAI: GPT-4 (older v0314)", false),
    model("openai/gpt-4-1106-preview", "OpenAI: GPT-4 Turbo (older v1106)", false),
    model("openai/gpt-4-turbo", "OpenAI: GPT-4 Turbo", false),
    model("openai/gpt-4-turbo-preview", "OpenAI: GPT-4 Turbo Preview", false),
    model("openai/gpt-4.1", "OpenAI: GPT-4.1", false),
    model("openai/gpt-4.1-mini", "OpenAI: GPT-4.1 Mini", false),
    model("openai/gpt-4.1-nano", "OpenAI: GPT-4.1 Nano", false),
    model("openai/gpt-4o", "OpenAI: GPT-4o", false),
    model("openai/gpt-4o-2024-05-13", "OpenAI: GPT-4o (2024-05-13)", false),
    model("openai/gpt-4o-2024-08-06", "OpenAI: GPT-4o (2024-08-06)", false),
    model("openai/gpt-4o-2024-11-20", "OpenAI: GPT-4o (2024-11-20)", false),
    model("openai/gpt-4o-audio-preview", "OpenAI: GPT-4o Audio", false),
    model("openai/gpt-4o-mini", "OpenAI: GPT-4o-mini", false),
    model("openai/gpt-4o-mini-2024-07-18", "OpenAI: GPT-4o-mini (2024-07-18)", false),
    model("openai/gpt-4o-mini-search-preview", "OpenAI: GPT-4o-mini Search Preview", false),
    model("openai/gpt-4o-mini-transcribe", "OpenAI: GPT-4o Mini Transcribe", false),
    model("openai/gpt-4o-mini-tts-2025-12-15", "OpenAI: GPT-4o Mini TTS", false),
    model("openai/gpt-4o-search-preview", "OpenAI: GPT-4o Search Preview", false),
    model("openai/gpt-4o-transcribe", "OpenAI: GPT-4o Transcribe", false),
    model("openai/gpt-5", "OpenAI: GPT-5", true),
    model("openai/gpt-5-chat", "OpenAI: GPT-5 Chat", false),
    model("openai/gpt-5-codex", "OpenAI: GPT-5 Codex", true),
    model("openai/gpt-5-image", "OpenAI: GPT-5 Image", true),
    model("openai/gpt-5-image-mini", "OpenAI: GPT-5 Image Mini", true),
    model("openai/gpt-5-mini", "OpenAI: GPT-5 Mini", true),
    model("openai/gpt-5-nano", "OpenAI: GPT-5 Nano", true),
    model("openai/gpt-5-pro", "OpenAI: GPT-5 Pro", true),
    model("openai/gpt-5.1", "OpenAI: GPT-5.1", true),
    model("openai/gpt-5.1-chat", "OpenAI: GPT-5.1 Chat", true),
    model("openai/gpt-5.1-codex", "OpenAI: GPT-5.1-Codex", true),
    model("openai/gpt-5.1-codex-max", "OpenAI: GPT-5.1-Codex-Max", true),
    model("openai/gpt-5.1-codex-mini", "OpenAI: GPT-5.1-Codex-Mini", true),
    model("openai/gpt-5.2", "OpenAI: GPT-5.2", true),
    model("openai/gpt-5.2-chat", "OpenAI: GPT-5.2 Chat", true),
    model("openai/gpt-5.2-codex", "OpenAI: GPT-5.2-Codex", true),
    model("openai/gpt-5.2-pro", "OpenAI: GPT-5.2 Pro", true),
    model("openai/gpt-5.3-chat", "OpenAI: GPT-5.3 Chat", true),
    model("openai/gpt-5.3-codex", "OpenAI: GPT-5.3-Codex", true),
    model("openai/gpt-5.4", "OpenAI: GPT-5.4", true),
    model("openai/gpt-5.4-image-2", "OpenAI: GPT-5.4 Image 2", true),
    model("openai/gpt-5.4-mini", "OpenAI: GPT-5.4 Mini", true),
    model("openai/gpt-5.4-nano", "OpenAI: GPT-5.4 Nano", true),
    model("openai/gpt-5.4-pro", "OpenAI: GPT-5.4 Pro", true),
    model("openai/gpt-5.5", "OpenAI: GPT-5.5", true),
    model("openai/gpt-5.5-pro", "OpenAI: GPT-5.5 Pro", true),
    model("openai/gpt-audio", "OpenAI: GPT Audio", false),
    model("openai/gpt-audio-mini", "OpenAI: GPT Audio Mini", false),
    model("openai/gpt-chat-latest", "OpenAI: GPT Chat Latest", false),
    model("openai/gpt-oss-120b", "OpenAI: gpt-oss-120b", true),
    model("openai/gpt-oss-20b", "OpenAI: gpt-oss-20b", true),
    model("openai/gpt-oss-safeguard-20b", "OpenAI: gpt-oss-safeguard-20b", true),
    model("openai/o1", "OpenAI: o1", true),
    model("openai/o1-pro", "OpenAI: o1-pro", true),
    model("openai/o3", "OpenAI: o3", true),
    model("openai/o3-deep-research", "OpenAI: o3 Deep Research", true),
    model("openai/o3-mini", "OpenAI: o3 Mini", true),
    model("openai/o3-mini-high", "OpenAI: o3 Mini High", true),
    model("openai/o3-pro", "OpenAI: o3 Pro", true),
    model("openai/o4-mini", "OpenAI: o4 Mini", true),
    model("openai/o4-mini-deep-research", "OpenAI: o4 Mini Deep Research", true),
    model("openai/o4-mini-high", "OpenAI: o4 Mini High", true),
    model("openai/sora-2-pro", "OpenAI: Sora 2 Pro", false),
    model("openai/text-embedding-3-large", "OpenAI: Text Embedding 3 Large", false),
    model("openai/text-embedding-3-small", "OpenAI: Text Embedding 3 Small", false),
    model("openai/text-embedding-ada-002", "OpenAI: Text Embedding Ada 002", false),
    model("openai/whisper-1", "OpenAI: Whisper 1", false),
    model("openai/whisper-large-v3", "OpenAI: Whisper Large V3", false),
    model("openai/whisper-large-v3-turbo", "OpenAI: Whisper Large V3 Turbo", false),
    model("openrouter/owl-alpha", "Owl Alpha", false),
    model("perplexity/pplx-embed-v1-0.6b", "Perplexity: Embed V1 0.6B", false),
    model("perplexity/pplx-embed-v1-4b", "Perplexity: Embed V1 4B", false),
    model("perplexity/sonar", "Perplexity: Sonar", false),
    model("perplexity/sonar-deep-research", "Perplexity: Sonar Deep Research", true),
    model("perplexity/sonar-pro", "Perplexity: Sonar Pro", false),
    model("perplexity/sonar-pro-search", "Perplexity: Sonar Pro Search", false),
    model("perplexity/sonar-reasoning-pro", "Perplexity: Sonar Reasoning Pro", true),
    model("prime-intellect/intellect-3", "Prime Intellect: INTELLECT-3", false),
    model("qwen/qwen-2.5-72b-instruct", "Qwen2.5 72B Instruct", false),
    model("qwen/qwen-2.5-7b-instruct", "Qwen: Qwen2.5 7B Instruct", false),
    model("qwen/qwen-2.5-coder-32b-instruct", "Qwen2.5 Coder 32B Instruct", false),
    model("qwen/qwen-max", "Qwen: Qwen-Max", false),
    model("qwen/qwen-plus", "Qwen: Qwen-Plus", false),
    model("qwen/qwen-plus-2025-07-28", "Qwen: Qwen Plus 0728", false),
    model("qwen/qwen-plus-2025-07-28:thinking", "Qwen: Qwen Plus 0728 (thinking)", false),
    model("qwen/qwen-turbo", "Qwen: Qwen-Turbo", false),
    model("qwen/qwen-vl-max", "Qwen: Qwen VL Max", false),
    model("qwen/qwen-vl-plus", "Qwen: Qwen VL Plus", false),
    model("qwen/qwen2.5-vl-72b-instruct", "Qwen: Qwen2.5 VL 72B Instruct", false),
    model("qwen/qwen3-14b", "Qwen: Qwen3 14B", false),
    model("qwen/qwen3-235b-a22b", "Qwen: Qwen3 235B A22B", false),
    model("qwen/qwen3-235b-a22b-2507", "Qwen: Qwen3 235B A22B Instruct 2507", false),
    model("qwen/qwen3-235b-a22b-thinking-2507", "Qwen: Qwen3 235B A22B Thinking 2507", true),
    model("qwen/qwen3-30b-a3b", "Qwen: Qwen3 30B A3B", false),
    model("qwen/qwen3-30b-a3b-instruct-2507", "Qwen: Qwen3 30B A3B Instruct 2507", false),
    model("qwen/qwen3-30b-a3b-thinking-2507", "Qwen: Qwen3 30B A3B Thinking 2507", true),
    model("qwen/qwen3-32b", "Qwen: Qwen3 32B", false),
    model("qwen/qwen3-8b", "Qwen: Qwen3 8B", false),
    model("qwen/qwen3-coder", "Qwen: Qwen3 Coder 480B A35B", false),
    model("qwen/qwen3-coder-30b-a3b-instruct", "Qwen: Qwen3 Coder 30B A3B Instruct", false),
    model("qwen/qwen3-coder-flash", "Qwen: Qwen3 Coder Flash", false),
    model("qwen/qwen3-coder-next", "Qwen: Qwen3 Coder Next", false),
    model("qwen/qwen3-coder-plus", "Qwen: Qwen3 Coder Plus", false),
    model("qwen/qwen3-embedding-4b", "Qwen: Qwen3 Embedding 4B", false),
    model("qwen/qwen3-embedding-8b", "Qwen: Qwen3 Embedding 8B", false),
    model("qwen/qwen3-max", "Qwen: Qwen3 Max", false),
    model("qwen/qwen3-max-thinking", "Qwen: Qwen3 Max Thinking", true),
    model("qwen/qwen3-next-80b-a3b-instruct", "Qwen: Qwen3 Next 80B A3B Instruct", false),
    model("qwen/qwen3-next-80b-a3b-thinking", "Qwen: Qwen3 Next 80B A3B Thinking", true),
    model("qwen/qwen3-vl-235b-a22b-instruct", "Qwen: Qwen3 VL 235B A22B Instruct", false),
    model("qwen/qwen3-vl-235b-a22b-thinking", "Qwen: Qwen3 VL 235B A22B Thinking", true),
    model("qwen/qwen3-vl-30b-a3b-instruct", "Qwen: Qwen3 VL 30B A3B Instruct", false),
    model("qwen/qwen3-vl-30b-a3b-thinking", "Qwen: Qwen3 VL 30B A3B Thinking", true),
    model("qwen/qwen3-vl-32b-instruct", "Qwen: Qwen3 VL 32B Instruct", false),
    model("qwen/qwen3-vl-8b-instruct", "Qwen: Qwen3 VL 8B Instruct", false),
    model("qwen/qwen3-vl-8b-thinking", "Qwen: Qwen3 VL 8B Thinking", true),
    model("qwen/qwen3.5-122b-a10b", "Qwen: Qwen3.5-122B-A10B", true),
    model("qwen/qwen3.5-27b", "Qwen: Qwen3.5-27B", true),
    model("qwen/qwen3.5-35b-a3b", "Qwen: Qwen3.5-35B-A3B", true),
    model("qwen/qwen3.5-397b-a17b", "Qwen: Qwen3.5 397B A17B", true),
    model("qwen/qwen3.5-9b", "Qwen: Qwen3.5-9B", true),
    model("qwen/qwen3.5-flash-02-23", "Qwen: Qwen3.5-Flash", true),
    model("qwen/qwen3.5-plus-02-15", "Qwen: Qwen3.5 Plus 2026-02-15", true),
    model("qwen/qwen3.5-plus-20260420", "Qwen: Qwen3.5 Plus 2026-04-20", true),
    model("qwen/qwen3.6-27b", "Qwen: Qwen3.6 27B", false),
    model("qwen/qwen3.6-35b-a3b", "Qwen: Qwen3.6 35B A3B", false),
    model("qwen/qwen3.6-flash", "Qwen: Qwen3.6 Flash", false),
    model("qwen/qwen3.6-max-preview", "Qwen: Qwen3.6 Max Preview", false),
    model("qwen/qwen3.6-plus", "Qwen: Qwen3.6 Plus", false),
    model("recraft/recraft-v3", "Recraft: Recraft V3", false),
    model("recraft/recraft-v4", "Recraft: Recraft V4", false),
    model("recraft/recraft-v4-pro", "Recraft: Recraft V4 Pro", false),
    model("rekaai/reka-edge", "Reka Edge", false),
    model("rekaai/reka-flash-3", "Reka Flash 3", false),
    model("relace/relace-apply-3", "Relace: Relace Apply 3", false),
    model("relace/relace-search", "Relace: Relace Search", false),
    model("sao10k/l3-euryale-70b", "Sao10k: Llama 3 Euryale 70B v2.1", false),
    model("sao10k/l3-lunaris-8b", "Sao10K: Llama 3 8B Lunaris", false),
    model("sao10k/l3.1-70b-hanami-x1", "Sao10K: Llama 3.1 70B Hanami x1", false),
    model("sao10k/l3.1-euryale-70b", "Sao10K: Llama 3.1 Euryale 70B v2.2", false),
    model("sao10k/l3.3-euryale-70b", "Sao10K: Llama 3.3 Euryale 70B", false),
    model("sentence-transformers/all-minilm-l12-v2", "Sentence Transformers: all-MiniLM-L12-v2", false),
    model("sentence-transformers/all-minilm-l6-v2", "Sentence Transformers: all-MiniLM-L6-v2", false),
    model("sentence-transformers/all-mpnet-base-v2", "Sentence Transformers: all-mpnet-base-v2", false),
    model(
      "sentence-transformers/multi-qa-mpnet-base-dot-v1",
      "Sentence Transformers: multi-qa-mpnet-base-dot-v1",
      false,
    ),
    model("sentence-transformers/paraphrase-minilm-l6-v2", "Sentence Transformers: paraphrase-MiniLM-L6-v2", false),
    model("sesame/csm-1b", "Sesame: CSM 1B", false),
    model("sourceful/riverflow-v2-fast", "Sourceful: Riverflow V2 Fast", false),
    model("sourceful/riverflow-v2-fast-preview", "Sourceful: Riverflow V2 Fast Preview", false),
    model("sourceful/riverflow-v2-max-preview", "Sourceful: Riverflow V2 Max Preview", false),
    model("sourceful/riverflow-v2-pro", "Sourceful: Riverflow V2 Pro", false),
    model("sourceful/riverflow-v2-standard-preview", "Sourceful: Riverflow V2 Standard Preview", false),
    model("stepfun/step-3.5-flash", "StepFun: Step 3.5 Flash", false),
    model("switchpoint/router", "Switchpoint Router", false),
    model("tencent/hunyuan-a13b-instruct", "Tencent: Hunyuan A13B Instruct", false),
    model("tencent/hy3-preview", "Tencent: Hy3 preview", false),
    model("thedrummer/cydonia-24b-v4.1", "TheDrummer: Cydonia 24B V4.1", false),
    model("thedrummer/rocinante-12b", "TheDrummer: Rocinante 12B", false),
    model("thedrummer/skyfall-36b-v2", "TheDrummer: Skyfall 36B V2", false),
    model("thedrummer/unslopnemo-12b", "TheDrummer: UnslopNemo 12B", false),
    model("thenlper/gte-base", "Thenlper: GTE-Base", false),
    model("thenlper/gte-large", "Thenlper: GTE-Large", false),
    model("undi95/remm-slerp-l2-13b", "ReMM SLERP 13B", false),
    model("upstage/solar-pro-3", "Upstage: Solar Pro 3", false),
    model("writer/palmyra-x5", "Writer: Palmyra X5", false),
    model("x-ai/grok-3", "xAI: Grok 3", false),
    model("x-ai/grok-3-beta", "xAI: Grok 3 Beta", false),
    model("x-ai/grok-3-mini", "xAI: Grok 3 Mini", false),
    model("x-ai/grok-3-mini-beta", "xAI: Grok 3 Mini Beta", false),
    model("x-ai/grok-4", "xAI: Grok 4", false),
    model("x-ai/grok-4-fast", "xAI: Grok 4 Fast", false),
    model("x-ai/grok-4.1-fast", "xAI: Grok 4.1 Fast", false),
    model("x-ai/grok-4.20", "xAI: Grok 4.20", false),
    model("x-ai/grok-4.20-multi-agent", "xAI: Grok 4.20 Multi-Agent", false),
    model("x-ai/grok-4.3", "xAI: Grok 4.3", false),
    model("x-ai/grok-code-fast-1", "xAI: Grok Code Fast 1", false),
    model("xiaomi/mimo-v2-flash", "Xiaomi: MiMo-V2-Flash", false),
    model("xiaomi/mimo-v2-omni", "Xiaomi: MiMo-V2-Omni", false),
    model("xiaomi/mimo-v2-pro", "Xiaomi: MiMo-V2-Pro", false),
    model("xiaomi/mimo-v2.5", "Xiaomi: MiMo-V2.5", false),
    model("xiaomi/mimo-v2.5-pro", "Xiaomi: MiMo-V2.5-Pro", false),
    model("z-ai/glm-4-32b", "Z.ai: GLM 4 32B", false),
    model("z-ai/glm-4.5", "Z.ai: GLM 4.5", true),
    model("z-ai/glm-4.5-air", "Z.ai: GLM 4.5 Air", true),
    model("z-ai/glm-4.5v", "Z.ai: GLM 4.5V", true),
    model("z-ai/glm-4.6", "Z.ai: GLM 4.6", true),
    model("z-ai/glm-4.6v", "Z.ai: GLM 4.6V", true),
    model("z-ai/glm-4.7", "Z.ai: GLM 4.7", true),
    model("z-ai/glm-4.7-flash", "Z.ai: GLM 4.7 Flash", true),
    model("z-ai/glm-5", "Z.ai: GLM 5", true),
    model("z-ai/glm-5-turbo", "Z.ai: GLM 5 Turbo", true),
    model("z-ai/glm-5.1", "Z.ai: GLM 5.1", true),
    model("z-ai/glm-5v-turbo", "Z.ai: GLM 5V Turbo", true),
    model("zyphra/zonos-v0.1-hybrid", "Zyphra: Zonos v0.1 Hybrid", false),
    model("zyphra/zonos-v0.1-transformer", "Zyphra: Zonos v0.1 Transformer", false),
  ],
}
