import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const NovitaPreset: ProviderPreset = {
  id: "novita",
  name: "Novita AI",
  baseURL: "https://api.novita.ai/v3/openai",
  note: "Seeded from Novita AI official /models catalog (101 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("baichuan/baichuan-m2-32b", "BaiChuan M2 32B", false),
    model("baidu/ernie-4.5-21B-a3b", "ERNIE 4.5 21B A3B", false),
    model("baidu/ernie-4.5-21B-a3b-thinking", "ERNIE-4.5-21B-A3B-Thinking", false),
    model("baidu/ernie-4.5-300b-a47b-paddle", "ERNIE 4.5 300B A47B", false),
    model("baidu/ernie-4.5-vl-28b-a3b", "ERNIE 4.5 VL 28B A3B", false),
    model("baidu/ernie-4.5-vl-28b-a3b-thinking", "ERNIE-4.5-VL-28B-A3B-Thinking", false),
    model("baidu/ernie-4.5-vl-424b-a47b", "ERNIE 4.5 VL 424B A47B", false),
    model("deepseek/deepseek-ocr", "DeepSeek-OCR", false),
    model("deepseek/deepseek-ocr-2", "DeepSeek-OCR 2", false),
    model("deepseek/deepseek-prover-v2-671b", "Deepseek Prover V2 671B", false),
    model("deepseek/deepseek-r1-0528", "DeepSeek R1 0528", true),
    model("deepseek/deepseek-r1-0528-qwen3-8b", "DeepSeek R1 0528 Qwen3 8B", true),
    model("deepseek/deepseek-r1-distill-llama-70b", "DeepSeek R1 Distill LLama 70B", true),
    model("deepseek/deepseek-r1-distill-qwen-14b", "DeepSeek R1 Distill Qwen 14B", true),
    model("deepseek/deepseek-r1-distill-qwen-32b", "DeepSeek R1 Distill Qwen 32B", true),
    model("deepseek/deepseek-r1-turbo", "DeepSeek R1 (Turbo)", true),
    model("deepseek/deepseek-v3-0324", "DeepSeek V3 0324", false),
    model("deepseek/deepseek-v3-turbo", "DeepSeek V3 (Turbo)", false),
    model("deepseek/deepseek-v3.1", "DeepSeek V3.1", true),
    model("deepseek/deepseek-v3.1-terminus", "Deepseek V3.1 Terminus", true),
    model("deepseek/deepseek-v3.2", "Deepseek V3.2", true),
    model("deepseek/deepseek-v3.2-exp", "Deepseek V3.2 Exp", true),
    model("deepseek/deepseek-v4-flash", "Deepseek V4 Flash", true),
    model("deepseek/deepseek-v4-pro", "Deepseek V4 Pro", true),
    model("elephant", "Ling-2.6-flash", false),
    model("google/gemma-3-12b-it", "Gemma3 12B", false),
    model("google/gemma-3-27b-it", "Gemma 3 27B", false),
    model("google/gemma-4-26b-a4b-it", "Gemma 4 26B A4B", false),
    model("google/gemma-4-31b-it", "Gemma 4 31B", false),
    model("gryphe/mythomax-l2-13b", "Mythomax L2 13B", false),
    model("inclusionai/ling-2.6-1t", "Ling-2.6-1T", false),
    model("inclusionai/ling-2.6-flash", "Ling-2.6-flash", false),
    model("kwaipilot/kat-coder-pro", "Kat Coder Pro", false),
    model("meta-llama/llama-3-70b-instruct", "Llama3 70B Instruct", false),
    model("meta-llama/llama-3-8b-instruct", "Llama 3 8B Instruct", false),
    model("meta-llama/llama-3.1-8b-instruct", "Llama 3.1 8B Instruct", false),
    model("meta-llama/llama-3.2-3b-instruct", "Llama 3.2 3B Instruct", false),
    model("meta-llama/llama-3.3-70b-instruct", "Llama 3.3 70B Instruct", false),
    model("meta-llama/llama-4-maverick-17b-128e-instruct-fp8", "Llama 4 Maverick Instruct", false),
    model("meta-llama/llama-4-scout-17b-16e-instruct", "Llama 4 Scout Instruct", false),
    model("microsoft/wizardlm-2-8x22b", "Wizardlm 2 8x22B", false),
    model("minimax/minimax-m2", "MiniMax-M2", false),
    model("minimax/minimax-m2.1", "Minimax M2.1", true),
    model("minimax/minimax-m2.5", "MiniMax M2.5", true),
    model("minimax/minimax-m2.5-highspeed", "MiniMax M2.5-highspeed", true),
    model("minimax/minimax-m2.7", "MiniMax M2.7", true),
    model("minimaxai/minimax-m1-80k", "MiniMax M1", false),
    model("mistralai/mistral-nemo", "Mistral Nemo", false),
    model("moonshotai/kimi-k2-0905", "Kimi K2 0905", false),
    model("moonshotai/kimi-k2-instruct", "Kimi K2 Instruct", false),
    model("moonshotai/kimi-k2-thinking", "Kimi K2 Thinking", true),
    model("moonshotai/kimi-k2.5", "Kimi K2.5", true),
    model("moonshotai/kimi-k2.6", "Kimi K2.6", true),
    model("nousresearch/hermes-2-pro-llama-3-8b", "Hermes 2 Pro Llama 3 8B", false),
    model("openai/gpt-oss-120b", "OpenAI GPT OSS 120B", true),
    model("openai/gpt-oss-20b", "OpenAI: GPT OSS 20B", true),
    model("paddlepaddle/paddleocr-vl", "PaddleOCR-VL", false),
    model("qwen/qwen-2.5-72b-instruct", "Qwen 2.5 72B Instruct", false),
    model("qwen/qwen-mt-plus", "Qwen MT Plus", false),
    model("qwen/qwen2.5-7b-instruct", "Qwen2.5 7B Instruct", false),
    model("qwen/qwen2.5-vl-72b-instruct", "Qwen2.5 VL 72B Instruct", false),
    model("qwen/qwen3-235b-a22b-fp8", "Qwen3 235B A22B", false),
    model("qwen/qwen3-235b-a22b-instruct-2507", "Qwen3 235B A22B Instruct 2507", false),
    model("qwen/qwen3-235b-a22b-thinking-2507", "Qwen3 235B A22b Thinking 2507", true),
    model("qwen/qwen3-30b-a3b-fp8", "Qwen3 30B A3B", false),
    model("qwen/qwen3-32b-fp8", "Qwen3 32B", false),
    model("qwen/qwen3-4b-fp8", "Qwen3 4B", false),
    model("qwen/qwen3-8b-fp8", "Qwen3 8B", false),
    model("qwen/qwen3-coder-30b-a3b-instruct", "Qwen3 Coder 30b A3B Instruct", false),
    model("qwen/qwen3-coder-480b-a35b-instruct", "Qwen3 Coder 480B A35B Instruct", false),
    model("qwen/qwen3-coder-next", "Qwen3 Coder Next", false),
    model("qwen/qwen3-max", "Qwen3 Max", false),
    model("qwen/qwen3-next-80b-a3b-instruct", "Qwen3 Next 80B A3B Instruct", false),
    model("qwen/qwen3-next-80b-a3b-thinking", "Qwen3 Next 80B A3B Thinking", true),
    model("qwen/qwen3-omni-30b-a3b-instruct", "Qwen3 Omni 30B A3B Instruct", false),
    model("qwen/qwen3-omni-30b-a3b-thinking", "Qwen3 Omni 30B A3B Thinking", true),
    model("qwen/qwen3-vl-235b-a22b-instruct", "Qwen3 VL 235B A22B Instruct", false),
    model("qwen/qwen3-vl-235b-a22b-thinking", "Qwen3 VL 235B A22B Thinking", true),
    model("qwen/qwen3-vl-30b-a3b-instruct", "qwen/qwen3-vl-30b-a3b-instruct", false),
    model("qwen/qwen3-vl-30b-a3b-thinking", "qwen/qwen3-vl-30b-a3b-thinking", true),
    model("qwen/qwen3-vl-8b-instruct", "qwen/qwen3-vl-8b-instruct", false),
    model("qwen/qwen3.5-122b-a10b", "Qwen3.5-122B-A10B", true),
    model("qwen/qwen3.5-27b", "Qwen3.5-27B", true),
    model("qwen/qwen3.5-35b-a3b", "Qwen3.5-35B-A3B", true),
    model("qwen/qwen3.5-397b-a17b", "Qwen3.5-397B-A17B", true),
    model("sao10k/l3-70b-euryale-v2.1", "L3 70B Euryale V2.1", false),
    model("sao10k/l3-8b-lunaris", "Sao10k L3 8B Lunaris", false),
    model("Sao10K/L3-8B-Stheno-v3.2", "L3 8B Stheno V3.2", false),
    model("sao10k/l31-70b-euryale-v2.2", "L31 70B Euryale V2.2", false),
    model("xiaomimimo/mimo-v2-flash", "XiaomiMiMo/MiMo-V2-Flash", false),
    model("xiaomimimo/mimo-v2.5-pro", "XiaomiMiMo/MiMo-V2.5-Pro", false),
    model("zai-org/autoglm-phone-9b-multilingual", "AutoGLM-Phone-9B-Multilingual", false),
    model("zai-org/glm-4.5", "GLM-4.5", true),
    model("zai-org/glm-4.5-air", "zai-org/glm-4.5-air", true),
    model("zai-org/glm-4.5v", "GLM 4.5V", true),
    model("zai-org/glm-4.6", "GLM 4.6", true),
    model("zai-org/glm-4.6v", "GLM 4.6V", true),
    model("zai-org/glm-4.7", "GLM-4.7", true),
    model("zai-org/glm-4.7-flash", "GLM-4.7-Flash", true),
    model("zai-org/glm-5", "GLM-5", true),
    model("zai-org/glm-5.1", "GLM-5.1", true),
  ],
}
