import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((effort) => [effort, { reasoning: { effort } }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

const models: ProviderPresetModel[] = [
  model("~anthropic/claude-haiku-latest", "Anthropic Claude Haiku Latest", true),
  model("~anthropic/claude-opus-latest", "Anthropic: Claude Opus Latest", true),
  model("~anthropic/claude-sonnet-latest", "Anthropic Claude Sonnet Latest", true),
  model("~google/gemini-flash-latest", "Google Gemini Flash Latest", true),
  model("~google/gemini-pro-latest", "Google Gemini Pro Latest", true),
  model("~moonshotai/kimi-latest", "MoonshotAI Kimi Latest", true),
  model("~openai/gpt-latest", "OpenAI GPT Latest", true),
  model("~openai/gpt-mini-latest", "OpenAI GPT Mini Latest", true),
  model("ai21/jamba-large-1.7", "AI21: Jamba Large 1.7"),
  model("aion-labs/aion-1.0", "AionLabs: Aion-1.0", true),
  model("aion-labs/aion-1.0-mini", "AionLabs: Aion-1.0-Mini", true),
  model("aion-labs/aion-2.0", "AionLabs: Aion-2.0", true),
  model("aion-labs/aion-rp-llama-3.1-8b", "AionLabs: Aion-RP 1.0 (8B)"),
  model("alfredpros/codellama-7b-instruct-solidity", "AlfredPros: CodeLLaMa 7B Instruct Solidity"),
  model("alibaba/tongyi-deepresearch-30b-a3b", "Tongyi DeepResearch 30B A3B", true),
  model("allenai/olmo-3-32b-think", "AllenAI: Olmo 3 32B Think", true),
  model("alpindale/goliath-120b", "Goliath 120B"),
  model("amazon/nova-2-lite-v1", "Amazon: Nova 2 Lite", true),
  model("amazon/nova-lite-v1", "Amazon: Nova Lite 1.0"),
  model("amazon/nova-micro-v1", "Amazon: Nova Micro 1.0"),
  model("amazon/nova-premier-v1", "Amazon: Nova Premier 1.0"),
  model("amazon/nova-pro-v1", "Amazon: Nova Pro 1.0"),
  model("anthracite-org/magnum-v4-72b", "Magnum v4 72B"),
  model("anthropic/claude-3-haiku", "Anthropic: Claude 3 Haiku"),
  model("anthropic/claude-3.5-haiku", "Anthropic: Claude 3.5 Haiku"),
  model("anthropic/claude-3.7-sonnet", "Anthropic: Claude 3.7 Sonnet", true),
  model("anthropic/claude-3.7-sonnet:thinking", "Anthropic: Claude 3.7 Sonnet (thinking)", true),
  model("anthropic/claude-haiku-4.5", "Anthropic: Claude Haiku 4.5", true),
  model("anthropic/claude-opus-4", "Anthropic: Claude Opus 4", true),
  model("anthropic/claude-opus-4.1", "Anthropic: Claude Opus 4.1", true),
  model("anthropic/claude-opus-4.5", "Anthropic: Claude Opus 4.5", true),
  model("anthropic/claude-opus-4.6", "Anthropic: Claude Opus 4.6", true),
  model("anthropic/claude-opus-4.6-fast", "Anthropic: Claude Opus 4.6 (Fast)", true),
  model("anthropic/claude-opus-4.7", "Anthropic: Claude Opus 4.7", true),
  model("anthropic/claude-sonnet-4", "Anthropic: Claude Sonnet 4", true),
  model("anthropic/claude-sonnet-4.5", "Anthropic: Claude Sonnet 4.5", true),
  model("anthropic/claude-sonnet-4.6", "Anthropic: Claude Sonnet 4.6", true),
  model("arcee-ai/coder-large", "Arcee AI: Coder Large"),
  model("arcee-ai/maestro-reasoning", "Arcee AI: Maestro Reasoning"),
  model("arcee-ai/spotlight", "Arcee AI: Spotlight"),
  model("arcee-ai/trinity-large-preview", "Arcee AI: Trinity Large Preview"),
  model("arcee-ai/trinity-large-thinking", "Arcee AI: Trinity Large Thinking", true),
  model("arcee-ai/trinity-mini", "Arcee AI: Trinity Mini", true),
  model("arcee-ai/virtuoso-large", "Arcee AI: Virtuoso Large"),
  model("baidu/cobuddy:free", "Baidu Qianfan: CoBuddy (free)", true),
  model("baidu/ernie-4.5-21b-a3b", "Baidu: ERNIE 4.5 21B A3B"),
  model("baidu/ernie-4.5-21b-a3b-thinking", "Baidu: ERNIE 4.5 21B A3B Thinking", true),
  model("baidu/ernie-4.5-300b-a47b", "Baidu: ERNIE 4.5 300B A47B"),
  model("baidu/ernie-4.5-vl-28b-a3b", "Baidu: ERNIE 4.5 VL 28B A3B", true),
  model("baidu/ernie-4.5-vl-424b-a47b", "Baidu: ERNIE 4.5 VL 424B A47B", true),
  model("baidu/qianfan-ocr-fast:free", "Baidu: Qianfan-OCR-Fast (free)", true),
  model("bytedance-seed/seed-1.6", "ByteDance Seed: Seed 1.6", true),
  model("bytedance-seed/seed-1.6-flash", "ByteDance Seed: Seed 1.6 Flash", true),
  model("bytedance-seed/seed-2.0-lite", "ByteDance Seed: Seed-2.0-Lite", true),
  model("bytedance-seed/seed-2.0-mini", "ByteDance Seed: Seed-2.0-Mini", true),
  model("bytedance/ui-tars-1.5-7b", "ByteDance: UI-TARS 7B"),
  model("cognitivecomputations/dolphin-mistral-24b-venice-edition:free", "Venice: Uncensored (free)"),
  model("cohere/command-a", "Cohere: Command A"),
  model("cohere/command-r-08-2024", "Cohere: Command R (08-2024)"),
  model("cohere/command-r-plus-08-2024", "Cohere: Command R+ (08-2024)"),
  model("cohere/command-r7b-12-2024", "Cohere: Command R7B (12-2024)"),
  model("deepcogito/cogito-v2.1-671b", "Deep Cogito: Cogito v2.1 671B", true),
  model("deepseek/deepseek-chat", "DeepSeek: DeepSeek V3"),
  model("deepseek/deepseek-chat-v3-0324", "DeepSeek: DeepSeek V3 0324"),
  model("deepseek/deepseek-chat-v3.1", "DeepSeek: DeepSeek V3.1", true),
  model("deepseek/deepseek-r1", "DeepSeek: R1", true),
  model("deepseek/deepseek-r1-0528", "DeepSeek: R1 0528", true),
  model("deepseek/deepseek-r1-distill-llama-70b", "DeepSeek: R1 Distill Llama 70B", true),
  model("deepseek/deepseek-r1-distill-qwen-32b", "DeepSeek: R1 Distill Qwen 32B", true),
  model("deepseek/deepseek-v3.1-terminus", "DeepSeek: DeepSeek V3.1 Terminus", true),
  model("deepseek/deepseek-v3.2", "DeepSeek: DeepSeek V3.2", true),
  model("deepseek/deepseek-v3.2-exp", "DeepSeek: DeepSeek V3.2 Exp", true),
  model("deepseek/deepseek-v3.2-speciale", "DeepSeek: DeepSeek V3.2 Speciale", true),
  model("deepseek/deepseek-v4-flash", "DeepSeek: DeepSeek V4 Flash", true),
  model("deepseek/deepseek-v4-pro", "DeepSeek: DeepSeek V4 Pro", true),
  model("essentialai/rnj-1-instruct", "EssentialAI: Rnj 1 Instruct"),
  model("google/gemini-2.0-flash-001", "Google: Gemini 2.0 Flash"),
  model("google/gemini-2.0-flash-lite-001", "Google: Gemini 2.0 Flash Lite"),
  model("google/gemini-2.5-flash", "Google: Gemini 2.5 Flash", true),
  model("google/gemini-2.5-flash-image", "Google: Nano Banana (Gemini 2.5 Flash Image)", true),
  model("google/gemini-2.5-flash-lite", "Google: Gemini 2.5 Flash Lite", true),
  model("google/gemini-2.5-flash-lite-preview-09-2025", "Google: Gemini 2.5 Flash Lite Preview 09-2025", true),
  model("google/gemini-2.5-pro", "Google: Gemini 2.5 Pro", true),
  model("google/gemini-2.5-pro-preview", "Google: Gemini 2.5 Pro Preview 06-05", true),
  model("google/gemini-2.5-pro-preview-05-06", "Google: Gemini 2.5 Pro Preview 05-06", true),
  model("google/gemini-3-flash-preview", "Google: Gemini 3 Flash Preview", true),
  model("google/gemini-3-pro-image-preview", "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)", true),
  model("google/gemini-3.1-flash-image-preview", "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)", true),
  model("google/gemini-3.1-flash-lite", "Google: Gemini 3.1 Flash Lite", true),
  model("google/gemini-3.1-flash-lite-preview", "Google: Gemini 3.1 Flash Lite Preview", true),
  model("google/gemini-3.1-pro-preview", "Google: Gemini 3.1 Pro Preview", true),
  model("google/gemini-3.1-pro-preview-customtools", "Google: Gemini 3.1 Pro Preview Custom Tools", true),
  model("google/gemma-2-27b-it", "Google: Gemma 2 27B"),
  model("google/gemma-3-12b-it", "Google: Gemma 3 12B"),
  model("google/gemma-3-27b-it", "Google: Gemma 3 27B"),
  model("google/gemma-3-4b-it", "Google: Gemma 3 4B"),
  model("google/gemma-3n-e4b-it", "Google: Gemma 3n 4B"),
  model("google/gemma-4-26b-a4b-it", "Google: Gemma 4 26B A4B", true),
  model("google/gemma-4-26b-a4b-it:free", "Google: Gemma 4 26B A4B  (free)", true),
  model("google/gemma-4-31b-it", "Google: Gemma 4 31B", true),
  model("google/gemma-4-31b-it:free", "Google: Gemma 4 31B (free)", true),
  model("google/lyria-3-clip-preview", "Google: Lyria 3 Clip Preview"),
  model("google/lyria-3-pro-preview", "Google: Lyria 3 Pro Preview"),
  model("gryphe/mythomax-l2-13b", "MythoMax 13B"),
  model("ibm-granite/granite-4.0-h-micro", "IBM: Granite 4.0 Micro"),
  model("ibm-granite/granite-4.1-8b", "IBM: Granite 4.1 8B"),
  model("inception/mercury-2", "Inception: Mercury 2", true),
  model("inclusionai/ling-2.6-1t", "inclusionAI: Ling-2.6-1T"),
  model("inclusionai/ling-2.6-flash", "inclusionAI: Ling-2.6-flash"),
  model("inclusionai/ring-2.6-1t:free", "inclusionAI: Ring-2.6-1T (free)", true),
  model("inflection/inflection-3-pi", "Inflection: Inflection 3 Pi"),
  model("inflection/inflection-3-productivity", "Inflection: Inflection 3 Productivity"),
  model("kwaipilot/kat-coder-pro-v2", "Kwaipilot: KAT-Coder-Pro V2"),
  model("liquid/lfm-2-24b-a2b", "LiquidAI: LFM2-24B-A2B"),
  model("liquid/lfm-2.5-1.2b-instruct:free", "LiquidAI: LFM2.5-1.2B-Instruct (free)"),
  model("liquid/lfm-2.5-1.2b-thinking:free", "LiquidAI: LFM2.5-1.2B-Thinking (free)", true),
  model("mancer/weaver", "Mancer: Weaver (alpha)"),
  model("meta-llama/llama-3-70b-instruct", "Meta: Llama 3 70B Instruct"),
  model("meta-llama/llama-3-8b-instruct", "Meta: Llama 3 8B Instruct"),
  model("meta-llama/llama-3.1-70b-instruct", "Meta: Llama 3.1 70B Instruct"),
  model("meta-llama/llama-3.1-8b-instruct", "Meta: Llama 3.1 8B Instruct"),
  model("meta-llama/llama-3.2-11b-vision-instruct", "Meta: Llama 3.2 11B Vision Instruct"),
  model("meta-llama/llama-3.2-1b-instruct", "Meta: Llama 3.2 1B Instruct"),
  model("meta-llama/llama-3.2-3b-instruct", "Meta: Llama 3.2 3B Instruct"),
  model("meta-llama/llama-3.2-3b-instruct:free", "Meta: Llama 3.2 3B Instruct (free)"),
  model("meta-llama/llama-3.3-70b-instruct", "Meta: Llama 3.3 70B Instruct"),
  model("meta-llama/llama-3.3-70b-instruct:free", "Meta: Llama 3.3 70B Instruct (free)"),
  model("meta-llama/llama-4-maverick", "Meta: Llama 4 Maverick"),
  model("meta-llama/llama-4-scout", "Meta: Llama 4 Scout"),
  model("meta-llama/llama-guard-3-8b", "Llama Guard 3 8B"),
  model("meta-llama/llama-guard-4-12b", "Meta: Llama Guard 4 12B"),
  model("microsoft/phi-4", "Microsoft: Phi 4"),
  model("microsoft/phi-4-mini-instruct", "Microsoft: Phi 4 Mini Instruct"),
  model("microsoft/wizardlm-2-8x22b", "WizardLM-2 8x22B"),
  model("minimax/minimax-01", "MiniMax: MiniMax-01"),
  model("minimax/minimax-m1", "MiniMax: MiniMax M1", true),
  model("minimax/minimax-m2", "MiniMax: MiniMax M2", true),
  model("minimax/minimax-m2-her", "MiniMax: MiniMax M2-her"),
  model("minimax/minimax-m2.1", "MiniMax: MiniMax M2.1", true),
  model("minimax/minimax-m2.5", "MiniMax: MiniMax M2.5", true),
  model("minimax/minimax-m2.5:free", "MiniMax: MiniMax M2.5 (free)", true),
  model("minimax/minimax-m2.7", "MiniMax: MiniMax M2.7", true),
  model("mistralai/codestral-2508", "Mistral: Codestral 2508"),
  model("mistralai/devstral-2512", "Mistral: Devstral 2 2512"),
  model("mistralai/devstral-medium", "Mistral: Devstral Medium"),
  model("mistralai/devstral-small", "Mistral: Devstral Small 1.1"),
  model("mistralai/ministral-14b-2512", "Mistral: Ministral 3 14B 2512"),
  model("mistralai/ministral-3b-2512", "Mistral: Ministral 3 3B 2512"),
  model("mistralai/ministral-8b-2512", "Mistral: Ministral 3 8B 2512"),
  model("mistralai/mistral-7b-instruct-v0.1", "Mistral: Mistral 7B Instruct v0.1"),
  model("mistralai/mistral-large", "Mistral Large"),
  model("mistralai/mistral-large-2407", "Mistral Large 2407"),
  model("mistralai/mistral-large-2411", "Mistral Large 2411"),
  model("mistralai/mistral-large-2512", "Mistral: Mistral Large 3 2512"),
  model("mistralai/mistral-medium-3", "Mistral: Mistral Medium 3"),
  model("mistralai/mistral-medium-3-5", "Mistral: Mistral Medium 3.5", true),
  model("mistralai/mistral-medium-3.1", "Mistral: Mistral Medium 3.1"),
  model("mistralai/mistral-nemo", "Mistral: Mistral Nemo"),
  model("mistralai/mistral-saba", "Mistral: Saba"),
  model("mistralai/mistral-small-24b-instruct-2501", "Mistral: Mistral Small 3"),
  model("mistralai/mistral-small-2603", "Mistral: Mistral Small 4", true),
  model("mistralai/mistral-small-3.1-24b-instruct", "Mistral: Mistral Small 3.1 24B"),
  model("mistralai/mistral-small-3.2-24b-instruct", "Mistral: Mistral Small 3.2 24B"),
  model("mistralai/mixtral-8x22b-instruct", "Mistral: Mixtral 8x22B Instruct"),
  model("mistralai/pixtral-large-2411", "Mistral: Pixtral Large 2411"),
  model("mistralai/voxtral-small-24b-2507", "Mistral: Voxtral Small 24B 2507"),
  model("moonshotai/kimi-k2", "MoonshotAI: Kimi K2 0711"),
  model("moonshotai/kimi-k2-0905", "MoonshotAI: Kimi K2 0905"),
  model("moonshotai/kimi-k2-thinking", "MoonshotAI: Kimi K2 Thinking", true),
  model("moonshotai/kimi-k2.5", "MoonshotAI: Kimi K2.5", true),
  model("moonshotai/kimi-k2.6", "MoonshotAI: Kimi K2.6", true),
  model("morph/morph-v3-fast", "Morph: Morph V3 Fast"),
  model("morph/morph-v3-large", "Morph: Morph V3 Large"),
  model("nex-agi/deepseek-v3.1-nex-n1", "Nex AGI: DeepSeek V3.1 Nex N1", true),
  model("nousresearch/hermes-2-pro-llama-3-8b", "NousResearch: Hermes 2 Pro - Llama-3 8B"),
  model("nousresearch/hermes-3-llama-3.1-405b", "Nous: Hermes 3 405B Instruct"),
  model("nousresearch/hermes-3-llama-3.1-405b:free", "Nous: Hermes 3 405B Instruct (free)"),
  model("nousresearch/hermes-3-llama-3.1-70b", "Nous: Hermes 3 70B Instruct"),
  model("nousresearch/hermes-4-405b", "Nous: Hermes 4 405B", true),
  model("nousresearch/hermes-4-70b", "Nous: Hermes 4 70B", true),
  model("nvidia/llama-3.3-nemotron-super-49b-v1.5", "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5", true),
  model("nvidia/nemotron-3-nano-30b-a3b", "NVIDIA: Nemotron 3 Nano 30B A3B", true),
  model("nvidia/nemotron-3-nano-30b-a3b:free", "NVIDIA: Nemotron 3 Nano 30B A3B (free)", true),
  model("nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", "NVIDIA: Nemotron 3 Nano Omni (free)", true),
  model("nvidia/nemotron-3-super-120b-a12b", "NVIDIA: Nemotron 3 Super", true),
  model("nvidia/nemotron-3-super-120b-a12b:free", "NVIDIA: Nemotron 3 Super (free)", true),
  model("nvidia/nemotron-nano-12b-v2-vl:free", "NVIDIA: Nemotron Nano 12B 2 VL (free)", true),
  model("nvidia/nemotron-nano-9b-v2", "NVIDIA: Nemotron Nano 9B V2", true),
  model("nvidia/nemotron-nano-9b-v2:free", "NVIDIA: Nemotron Nano 9B V2 (free)", true),
  model("openai/gpt-3.5-turbo", "OpenAI: GPT-3.5 Turbo"),
  model("openai/gpt-3.5-turbo-0613", "OpenAI: GPT-3.5 Turbo (older v0613)"),
  model("openai/gpt-3.5-turbo-16k", "OpenAI: GPT-3.5 Turbo 16k"),
  model("openai/gpt-3.5-turbo-instruct", "OpenAI: GPT-3.5 Turbo Instruct"),
  model("openai/gpt-4", "OpenAI: GPT-4"),
  model("openai/gpt-4-0314", "OpenAI: GPT-4 (older v0314)"),
  model("openai/gpt-4-1106-preview", "OpenAI: GPT-4 Turbo (older v1106)"),
  model("openai/gpt-4-turbo", "OpenAI: GPT-4 Turbo"),
  model("openai/gpt-4-turbo-preview", "OpenAI: GPT-4 Turbo Preview"),
  model("openai/gpt-4.1", "OpenAI: GPT-4.1"),
  model("openai/gpt-4.1-mini", "OpenAI: GPT-4.1 Mini"),
  model("openai/gpt-4.1-nano", "OpenAI: GPT-4.1 Nano"),
  model("openai/gpt-4o", "OpenAI: GPT-4o"),
  model("openai/gpt-4o-2024-05-13", "OpenAI: GPT-4o (2024-05-13)"),
  model("openai/gpt-4o-2024-08-06", "OpenAI: GPT-4o (2024-08-06)"),
  model("openai/gpt-4o-2024-11-20", "OpenAI: GPT-4o (2024-11-20)"),
  model("openai/gpt-4o-audio-preview", "OpenAI: GPT-4o Audio"),
  model("openai/gpt-4o-mini", "OpenAI: GPT-4o-mini"),
  model("openai/gpt-4o-mini-2024-07-18", "OpenAI: GPT-4o-mini (2024-07-18)"),
  model("openai/gpt-4o-mini-search-preview", "OpenAI: GPT-4o-mini Search Preview"),
  model("openai/gpt-4o-search-preview", "OpenAI: GPT-4o Search Preview"),
  model("openai/gpt-5", "OpenAI: GPT-5", true),
  model("openai/gpt-5-chat", "OpenAI: GPT-5 Chat"),
  model("openai/gpt-5-codex", "OpenAI: GPT-5 Codex", true),
  model("openai/gpt-5-image", "OpenAI: GPT-5 Image", true),
  model("openai/gpt-5-image-mini", "OpenAI: GPT-5 Image Mini", true),
  model("openai/gpt-5-mini", "OpenAI: GPT-5 Mini", true),
  model("openai/gpt-5-nano", "OpenAI: GPT-5 Nano", true),
  model("openai/gpt-5-pro", "OpenAI: GPT-5 Pro", true),
  model("openai/gpt-5.1", "OpenAI: GPT-5.1", true),
  model("openai/gpt-5.1-chat", "OpenAI: GPT-5.1 Chat", true),
  model("openai/gpt-5.1-codex", "OpenAI: GPT-5.1-Codex", true),
  model("openai/gpt-5.1-codex-max", "OpenAI: GPT-5.1-Codex-Max", true),
  model("openai/gpt-5.1-codex-mini", "OpenAI: GPT-5.1-Codex-Mini", true),
  model("openai/gpt-5.2", "OpenAI: GPT-5.2", true),
  model("openai/gpt-5.2-chat", "OpenAI: GPT-5.2 Chat", true),
  model("openai/gpt-5.2-codex", "OpenAI: GPT-5.2-Codex", true),
  model("openai/gpt-5.2-pro", "OpenAI: GPT-5.2 Pro", true),
  model("openai/gpt-5.3-chat", "OpenAI: GPT-5.3 Chat", true),
  model("openai/gpt-5.3-codex", "OpenAI: GPT-5.3-Codex", true),
  model("openai/gpt-5.4", "OpenAI: GPT-5.4", true),
  model("openai/gpt-5.4-image-2", "OpenAI: GPT-5.4 Image 2", true),
  model("openai/gpt-5.4-mini", "OpenAI: GPT-5.4 Mini", true),
  model("openai/gpt-5.4-nano", "OpenAI: GPT-5.4 Nano", true),
  model("openai/gpt-5.4-pro", "OpenAI: GPT-5.4 Pro", true),
  model("openai/gpt-5.5", "OpenAI: GPT-5.5", true),
  model("openai/gpt-5.5-pro", "OpenAI: GPT-5.5 Pro", true),
  model("openai/gpt-audio", "OpenAI: GPT Audio"),
  model("openai/gpt-audio-mini", "OpenAI: GPT Audio Mini"),
  model("openai/gpt-chat-latest", "OpenAI: GPT Chat Latest"),
  model("openai/gpt-oss-120b", "OpenAI: gpt-oss-120b", true),
  model("openai/gpt-oss-120b:free", "OpenAI: gpt-oss-120b (free)", true),
  model("openai/gpt-oss-20b", "OpenAI: gpt-oss-20b", true),
  model("openai/gpt-oss-20b:free", "OpenAI: gpt-oss-20b (free)", true),
  model("openai/gpt-oss-safeguard-20b", "OpenAI: gpt-oss-safeguard-20b", true),
  model("openai/o1", "OpenAI: o1", true),
  model("openai/o1-pro", "OpenAI: o1-pro", true),
  model("openai/o3", "OpenAI: o3", true),
  model("openai/o3-deep-research", "OpenAI: o3 Deep Research", true),
  model("openai/o3-mini", "OpenAI: o3 Mini", true),
  model("openai/o3-mini-high", "OpenAI: o3 Mini High", true),
  model("openai/o3-pro", "OpenAI: o3 Pro", true),
  model("openai/o4-mini", "OpenAI: o4 Mini", true),
  model("openai/o4-mini-deep-research", "OpenAI: o4 Mini Deep Research", true),
  model("openai/o4-mini-high", "OpenAI: o4 Mini High", true),
  model("openrouter/auto", "Auto Router", true),
  model("openrouter/bodybuilder", "Body Builder (beta)"),
  model("openrouter/free", "Free Models Router", true),
  model("openrouter/owl-alpha", "Owl Alpha"),
  model("openrouter/pareto-code", "Pareto Code Router"),
  model("perplexity/sonar", "Perplexity: Sonar"),
  model("perplexity/sonar-deep-research", "Perplexity: Sonar Deep Research", true),
  model("perplexity/sonar-pro", "Perplexity: Sonar Pro"),
  model("perplexity/sonar-pro-search", "Perplexity: Sonar Pro Search", true),
  model("perplexity/sonar-reasoning-pro", "Perplexity: Sonar Reasoning Pro", true),
  model("poolside/laguna-m.1:free", "Poolside: Laguna M.1 (free)", true),
  model("poolside/laguna-xs.2:free", "Poolside: Laguna XS.2 (free)", true),
  model("prime-intellect/intellect-3", "Prime Intellect: INTELLECT-3", true),
  model("qwen/qwen-2.5-72b-instruct", "Qwen2.5 72B Instruct"),
  model("qwen/qwen-2.5-7b-instruct", "Qwen: Qwen2.5 7B Instruct"),
  model("qwen/qwen-2.5-coder-32b-instruct", "Qwen2.5 Coder 32B Instruct"),
  model("qwen/qwen-max", "Qwen: Qwen-Max"),
  model("qwen/qwen-plus", "Qwen: Qwen-Plus"),
  model("qwen/qwen-plus-2025-07-28", "Qwen: Qwen Plus 0728"),
  model("qwen/qwen-plus-2025-07-28:thinking", "Qwen: Qwen Plus 0728 (thinking)", true),
  model("qwen/qwen-turbo", "Qwen: Qwen-Turbo"),
  model("qwen/qwen-vl-max", "Qwen: Qwen VL Max"),
  model("qwen/qwen-vl-plus", "Qwen: Qwen VL Plus"),
  model("qwen/qwen2.5-vl-72b-instruct", "Qwen: Qwen2.5 VL 72B Instruct"),
  model("qwen/qwen3-14b", "Qwen: Qwen3 14B", true),
  model("qwen/qwen3-235b-a22b", "Qwen: Qwen3 235B A22B", true),
  model("qwen/qwen3-235b-a22b-2507", "Qwen: Qwen3 235B A22B Instruct 2507"),
  model("qwen/qwen3-235b-a22b-thinking-2507", "Qwen: Qwen3 235B A22B Thinking 2507", true),
  model("qwen/qwen3-30b-a3b", "Qwen: Qwen3 30B A3B", true),
  model("qwen/qwen3-30b-a3b-instruct-2507", "Qwen: Qwen3 30B A3B Instruct 2507"),
  model("qwen/qwen3-30b-a3b-thinking-2507", "Qwen: Qwen3 30B A3B Thinking 2507", true),
  model("qwen/qwen3-32b", "Qwen: Qwen3 32B", true),
  model("qwen/qwen3-8b", "Qwen: Qwen3 8B", true),
  model("qwen/qwen3-coder", "Qwen: Qwen3 Coder 480B A35B"),
  model("qwen/qwen3-coder-30b-a3b-instruct", "Qwen: Qwen3 Coder 30B A3B Instruct"),
  model("qwen/qwen3-coder-flash", "Qwen: Qwen3 Coder Flash"),
  model("qwen/qwen3-coder-next", "Qwen: Qwen3 Coder Next"),
  model("qwen/qwen3-coder-plus", "Qwen: Qwen3 Coder Plus"),
  model("qwen/qwen3-coder:free", "Qwen: Qwen3 Coder 480B A35B (free)"),
  model("qwen/qwen3-max", "Qwen: Qwen3 Max"),
  model("qwen/qwen3-max-thinking", "Qwen: Qwen3 Max Thinking", true),
  model("qwen/qwen3-next-80b-a3b-instruct", "Qwen: Qwen3 Next 80B A3B Instruct"),
  model("qwen/qwen3-next-80b-a3b-instruct:free", "Qwen: Qwen3 Next 80B A3B Instruct (free)"),
  model("qwen/qwen3-next-80b-a3b-thinking", "Qwen: Qwen3 Next 80B A3B Thinking", true),
  model("qwen/qwen3-vl-235b-a22b-instruct", "Qwen: Qwen3 VL 235B A22B Instruct"),
  model("qwen/qwen3-vl-235b-a22b-thinking", "Qwen: Qwen3 VL 235B A22B Thinking", true),
  model("qwen/qwen3-vl-30b-a3b-instruct", "Qwen: Qwen3 VL 30B A3B Instruct"),
  model("qwen/qwen3-vl-30b-a3b-thinking", "Qwen: Qwen3 VL 30B A3B Thinking", true),
  model("qwen/qwen3-vl-32b-instruct", "Qwen: Qwen3 VL 32B Instruct"),
  model("qwen/qwen3-vl-8b-instruct", "Qwen: Qwen3 VL 8B Instruct"),
  model("qwen/qwen3-vl-8b-thinking", "Qwen: Qwen3 VL 8B Thinking", true),
  model("qwen/qwen3.5-122b-a10b", "Qwen: Qwen3.5-122B-A10B", true),
  model("qwen/qwen3.5-27b", "Qwen: Qwen3.5-27B", true),
  model("qwen/qwen3.5-35b-a3b", "Qwen: Qwen3.5-35B-A3B", true),
  model("qwen/qwen3.5-397b-a17b", "Qwen: Qwen3.5 397B A17B", true),
  model("qwen/qwen3.5-9b", "Qwen: Qwen3.5-9B", true),
  model("qwen/qwen3.5-flash-02-23", "Qwen: Qwen3.5-Flash", true),
  model("qwen/qwen3.5-plus-02-15", "Qwen: Qwen3.5 Plus 2026-02-15", true),
  model("qwen/qwen3.5-plus-20260420", "Qwen: Qwen3.5 Plus 2026-04-20", true),
  model("qwen/qwen3.6-27b", "Qwen: Qwen3.6 27B", true),
  model("qwen/qwen3.6-35b-a3b", "Qwen: Qwen3.6 35B A3B", true),
  model("qwen/qwen3.6-flash", "Qwen: Qwen3.6 Flash", true),
  model("qwen/qwen3.6-max-preview", "Qwen: Qwen3.6 Max Preview", true),
  model("qwen/qwen3.6-plus", "Qwen: Qwen3.6 Plus", true),
  model("rekaai/reka-edge", "Reka Edge"),
  model("rekaai/reka-flash-3", "Reka Flash 3", true),
  model("relace/relace-apply-3", "Relace: Relace Apply 3"),
  model("relace/relace-search", "Relace: Relace Search"),
  model("sao10k/l3-euryale-70b", "Sao10k: Llama 3 Euryale 70B v2.1"),
  model("sao10k/l3-lunaris-8b", "Sao10K: Llama 3 8B Lunaris"),
  model("sao10k/l3.1-70b-hanami-x1", "Sao10K: Llama 3.1 70B Hanami x1"),
  model("sao10k/l3.1-euryale-70b", "Sao10K: Llama 3.1 Euryale 70B v2.2"),
  model("sao10k/l3.3-euryale-70b", "Sao10K: Llama 3.3 Euryale 70B"),
  model("stepfun/step-3.5-flash", "StepFun: Step 3.5 Flash", true),
  model("switchpoint/router", "Switchpoint Router", true),
  model("tencent/hunyuan-a13b-instruct", "Tencent: Hunyuan A13B Instruct", true),
  model("tencent/hy3-preview", "Tencent: Hy3 preview", true),
  model("thedrummer/cydonia-24b-v4.1", "TheDrummer: Cydonia 24B V4.1"),
  model("thedrummer/rocinante-12b", "TheDrummer: Rocinante 12B"),
  model("thedrummer/skyfall-36b-v2", "TheDrummer: Skyfall 36B V2"),
  model("thedrummer/unslopnemo-12b", "TheDrummer: UnslopNemo 12B"),
  model("undi95/remm-slerp-l2-13b", "ReMM SLERP 13B"),
  model("upstage/solar-pro-3", "Upstage: Solar Pro 3", true),
  model("writer/palmyra-x5", "Writer: Palmyra X5"),
  model("x-ai/grok-3", "xAI: Grok 3"),
  model("x-ai/grok-3-beta", "xAI: Grok 3 Beta"),
  model("x-ai/grok-3-mini", "xAI: Grok 3 Mini", true),
  model("x-ai/grok-3-mini-beta", "xAI: Grok 3 Mini Beta", true),
  model("x-ai/grok-4", "xAI: Grok 4", true),
  model("x-ai/grok-4-fast", "xAI: Grok 4 Fast", true),
  model("x-ai/grok-4.1-fast", "xAI: Grok 4.1 Fast", true),
  model("x-ai/grok-4.20", "xAI: Grok 4.20", true),
  model("x-ai/grok-4.20-multi-agent", "xAI: Grok 4.20 Multi-Agent", true),
  model("x-ai/grok-4.3", "xAI: Grok 4.3", true),
  model("x-ai/grok-code-fast-1", "xAI: Grok Code Fast 1", true),
  model("xiaomi/mimo-v2-flash", "Xiaomi: MiMo-V2-Flash", true),
  model("xiaomi/mimo-v2-omni", "Xiaomi: MiMo-V2-Omni", true),
  model("xiaomi/mimo-v2-pro", "Xiaomi: MiMo-V2-Pro", true),
  model("xiaomi/mimo-v2.5", "Xiaomi: MiMo-V2.5", true),
  model("xiaomi/mimo-v2.5-pro", "Xiaomi: MiMo-V2.5-Pro", true),
  model("z-ai/glm-4-32b", "Z.ai: GLM 4 32B"),
  model("z-ai/glm-4.5", "Z.ai: GLM 4.5", true),
  model("z-ai/glm-4.5-air", "Z.ai: GLM 4.5 Air", true),
  model("z-ai/glm-4.5-air:free", "Z.ai: GLM 4.5 Air (free)", true),
  model("z-ai/glm-4.5v", "Z.ai: GLM 4.5V", true),
  model("z-ai/glm-4.6", "Z.ai: GLM 4.6", true),
  model("z-ai/glm-4.6v", "Z.ai: GLM 4.6V", true),
  model("z-ai/glm-4.7", "Z.ai: GLM 4.7", true),
  model("z-ai/glm-4.7-flash", "Z.ai: GLM 4.7 Flash", true),
  model("z-ai/glm-5", "Z.ai: GLM 5", true),
  model("z-ai/glm-5-turbo", "Z.ai: GLM 5 Turbo", true),
  model("z-ai/glm-5.1", "Z.ai: GLM 5.1", true),
  model("z-ai/glm-5v-turbo", "Z.ai: GLM 5V Turbo", true),
]

export const OpenrouterPreset: ProviderPreset = {
  id: "openrouter",
  name: "OpenRouter",
  baseURL: "https://openrouter.ai/api/v1",
  note: "Select from the OpenRouter model catalog shipped with Altru Coder.",
  fetch: false,
  models,
}
