import type { ProviderPreset } from './types'

export const OpenaiPreset: ProviderPreset = {
  id: "openai",
  name: "OpenAI",
  baseURL: "https://api.openai.com/v1",
  note: "Select GPT and Codex models from the built-in Cline registry.",
  fetch: false,
  models: [
    { id: "gpt-5.5", name: "Gpt 5.5", reasoning: true },
    { id: "gpt-5.4", name: "Gpt 5.4", reasoning: true },
    { id: "gpt-5.4-mini", name: "Gpt 5.4 Mini", reasoning: true },
    { id: "gpt-5.4-nano", name: "Gpt 5.4 Nano", reasoning: true },
    { id: "gpt-5.3-codex", name: "Gpt 5.3 Codex", reasoning: true },
    { id: "gpt-5.3-chat-latest", name: "Gpt 5.3 Chat Latest" },
    { id: "gpt-5.2-chat-latest", name: "Gpt 5.2 Chat Latest" },
    { id: "gpt-5.2", name: "Gpt 5.2", reasoning: true },
    { id: "gpt-5.2-codex", name: "Gpt 5.2 Codex", reasoning: true },
    { id: "gpt-5.1-2025-11-13", name: "Gpt 5.1 2025 11 13", reasoning: true },
    { id: "gpt-5.1", name: "Gpt 5.1", reasoning: true },
    { id: "gpt-5.1-codex", name: "Gpt 5.1 Codex", reasoning: true },
    { id: "gpt-5.1-chat-latest", name: "Gpt 5.1 Chat Latest", reasoning: true },
    { id: "gpt-5-2025-08-07", name: "Gpt 5 2025 08 07", reasoning: true },
    { id: "gpt-5-codex", name: "Gpt 5 Codex", reasoning: true },
    { id: "gpt-5-mini-2025-08-07", name: "Gpt 5 Mini 2025 08 07", reasoning: true },
    { id: "gpt-5-nano-2025-08-07", name: "Gpt 5 Nano 2025 08 07", reasoning: true },
    { id: "gpt-5-chat-latest", name: "Gpt 5 Chat Latest", reasoning: true },
    { id: "o3", name: "O3", reasoning: true },
    { id: "o4-mini", name: "O4 Mini", reasoning: true },
    { id: "gpt-4.1", name: "Gpt 4.1" },
    { id: "gpt-4.1-mini", name: "Gpt 4.1 Mini" },
    { id: "gpt-4.1-nano", name: "Gpt 4.1 Nano" },
    { id: "o3-mini", name: "O3 Mini", reasoning: true },
    { id: "o1", name: "O1" },
    { id: "o1-preview", name: "O1 Preview" },
    { id: "o1-mini", name: "O1 Mini" },
    { id: "gpt-4o", name: "Gpt 4o" },
    { id: "gpt-4o-mini", name: "Gpt 4o Mini" },
    { id: "chatgpt-4o-latest", name: "Chatgpt 4o Latest" },
    { id: "gpt-5.1-codex-max", name: "Gpt 5.1 Codex Max", reasoning: true },
    { id: "gpt-5.1-codex-mini", name: "Gpt 5.1 Codex Mini", reasoning: true },
  ],
}
