import type { ProviderPreset } from './types'

export const QwenPreset: ProviderPreset = {
  id: "qwen",
  name: "Qwen International",
  baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
  note: "Select international Qwen models from the built-in Cline registry.",
  fetch: false,
  models: [
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-coder-480b-a35b-instruct", name: "Qwen3 Coder 480b A35b Instruct" },
    { id: "qwen3-235b-a22b", name: "Qwen3 235b A22b", reasoning: true },
    { id: "qwen3-32b", name: "Qwen3 32b", reasoning: true },
    { id: "qwen3-30b-a3b", name: "Qwen3 30b A3b", reasoning: true },
    { id: "qwen3-14b", name: "Qwen3 14b", reasoning: true },
    { id: "qwen3-8b", name: "Qwen3 8b", reasoning: true },
    { id: "qwen3-4b", name: "Qwen3 4b", reasoning: true },
    { id: "qwen3-1.7b", name: "Qwen3 1.7b", reasoning: true },
    { id: "qwen3-0.6b", name: "Qwen3 0.6b", reasoning: true },
    { id: "qwen2.5-coder-32b-instruct", name: "Qwen2.5 Coder 32b Instruct" },
    { id: "qwen2.5-coder-14b-instruct", name: "Qwen2.5 Coder 14b Instruct" },
    { id: "qwen2.5-coder-7b-instruct", name: "Qwen2.5 Coder 7b Instruct" },
    { id: "qwen2.5-coder-3b-instruct", name: "Qwen2.5 Coder 3b Instruct" },
    { id: "qwen2.5-coder-1.5b-instruct", name: "Qwen2.5 Coder 1.5b Instruct" },
    { id: "qwen2.5-coder-0.5b-instruct", name: "Qwen2.5 Coder 0.5b Instruct" },
    { id: "qwen-coder-plus-latest", name: "Qwen Coder Plus Latest" },
    { id: "qwen-plus-latest", name: "Qwen Plus Latest", reasoning: true },
    { id: "qwen-turbo-latest", name: "Qwen Turbo Latest", reasoning: true },
    { id: "qwen-max-latest", name: "Qwen Max Latest" },
    { id: "qwen-coder-plus", name: "Qwen Coder Plus" },
    { id: "qwen-plus", name: "Qwen Plus" },
    { id: "qwen-turbo", name: "Qwen Turbo" },
    { id: "qwen-max", name: "Qwen Max" },
    { id: "deepseek-v3", name: "Deepseek V3" },
    { id: "deepseek-r1", name: "Deepseek R1" },
    { id: "qwen-vl-max", name: "Qwen Vl Max" },
    { id: "qwen-vl-max-latest", name: "Qwen Vl Max Latest" },
    { id: "qwen-vl-plus", name: "Qwen Vl Plus" },
    { id: "qwen-vl-plus-latest", name: "Qwen Vl Plus Latest" },
    { id: "qwen3-coder-flash", name: "Qwen3 Coder Flash" },
  ],
}
