import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const RequestyPreset: ProviderPreset = {
  id: "requesty",
  name: "Requesty",
  baseURL: "https://router.requesty.ai/v1",
  note: "Seeded from Requesty official /models catalog (473 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("alibaba/qwen-max", "alibaba/qwen-max", false),
    model("alibaba/qwen-plus", "alibaba/qwen-plus", false),
    model("alibaba/qwen-turbo", "alibaba/qwen-turbo", false),
    model("alibaba/qwen3-30b-a3b-instruct-2507", "alibaba/qwen3-30b-a3b-instruct-2507", false),
    model("alibaba/qwen3-coder-flash", "alibaba/qwen3-coder-flash", false),
    model("alibaba/qwen3-coder-plus", "alibaba/qwen3-coder-plus", false),
    model("alibaba/qwen3-max", "alibaba/qwen3-max", false),
    model("alibaba/qwen3.5", "alibaba/qwen3.5", true),
    model("anthropic/claude-haiku-4-5", "anthropic/claude-haiku-4-5", true),
    model("anthropic/claude-opus-4", "anthropic/claude-opus-4", true),
    model("anthropic/claude-opus-4-1", "anthropic/claude-opus-4-1", true),
    model("anthropic/claude-opus-4-5", "anthropic/claude-opus-4-5", true),
    model("anthropic/claude-opus-4-6", "anthropic/claude-opus-4-6", true),
    model("anthropic/claude-opus-4-7", "anthropic/claude-opus-4-7", true),
    model("anthropic/claude-sonnet-4", "anthropic/claude-sonnet-4", true),
    model("anthropic/claude-sonnet-4-5", "anthropic/claude-sonnet-4-5", true),
    model("anthropic/claude-sonnet-4-6", "anthropic/claude-sonnet-4-6", true),
    model("azure/gpt-4.1", "azure/gpt-4.1", false),
    model("azure/gpt-4.1-mini", "azure/gpt-4.1-mini", false),
    model("azure/gpt-4.1-mini@eastus2", "azure/gpt-4.1-mini@eastus2", false),
    model("azure/gpt-4.1-mini@francecentral", "azure/gpt-4.1-mini@francecentral", false),
    model("azure/gpt-4.1-mini@uksouth", "azure/gpt-4.1-mini@uksouth", false),
    model("azure/gpt-4.1-mini@westus3", "azure/gpt-4.1-mini@westus3", false),
    model("azure/gpt-4.1-nano", "azure/gpt-4.1-nano", false),
    model("azure/gpt-4.1-nano@eastus2", "azure/gpt-4.1-nano@eastus2", false),
    model("azure/gpt-4.1-nano@francecentral", "azure/gpt-4.1-nano@francecentral", false),
    model("azure/gpt-4.1-nano@swedencentral", "azure/gpt-4.1-nano@swedencentral", false),
    model("azure/gpt-4.1-nano@uksouth", "azure/gpt-4.1-nano@uksouth", false),
    model("azure/gpt-4.1-nano@westus3", "azure/gpt-4.1-nano@westus3", false),
    model("azure/gpt-4.1@eastus2", "azure/gpt-4.1@eastus2", false),
    model("azure/gpt-4.1@francecentral", "azure/gpt-4.1@francecentral", false),
    model("azure/gpt-4.1@swedencentral", "azure/gpt-4.1@swedencentral", false),
    model("azure/gpt-4.1@uksouth", "azure/gpt-4.1@uksouth", false),
    model("azure/gpt-4.1@westus3", "azure/gpt-4.1@westus3", false),
    model("azure/gpt-5", "azure/gpt-5", true),
    model("azure/gpt-5-mini", "azure/gpt-5-mini", true),
    model("azure/gpt-5-mini@eastus2", "azure/gpt-5-mini@eastus2", true),
    model("azure/gpt-5-mini@francecentral", "azure/gpt-5-mini@francecentral", true),
    model("azure/gpt-5-mini@swedencentral", "azure/gpt-5-mini@swedencentral", true),
    model("azure/gpt-5-mini@uksouth", "azure/gpt-5-mini@uksouth", true),
    model("azure/gpt-5-nano", "azure/gpt-5-nano", true),
    model("azure/gpt-5-nano@eastus2", "azure/gpt-5-nano@eastus2", true),
    model("azure/gpt-5-nano@francecentral", "azure/gpt-5-nano@francecentral", true),
    model("azure/gpt-5-nano@swedencentral", "azure/gpt-5-nano@swedencentral", true),
    model("azure/gpt-5.1", "azure/gpt-5.1", true),
    model("azure/gpt-5.1@eastus2", "azure/gpt-5.1@eastus2", true),
    model("azure/gpt-5.1@francecentral", "azure/gpt-5.1@francecentral", true),
    model("azure/gpt-5.1@swedencentral", "azure/gpt-5.1@swedencentral", true),
    model("azure/gpt-5.2", "azure/gpt-5.2", true),
    model("azure/gpt-5.2@eastus2", "azure/gpt-5.2@eastus2", true),
    model("azure/gpt-5.3-codex@eastus2", "azure/gpt-5.3-codex@eastus2", true),
    model("azure/gpt-5.4@eastus2", "azure/gpt-5.4@eastus2", true),
    model("azure/gpt-5.4@francecentral", "azure/gpt-5.4@francecentral", true),
    model("azure/gpt-5.4@swedencentral", "azure/gpt-5.4@swedencentral", true),
    model("azure/gpt-5.5@eastus2", "azure/gpt-5.5@eastus2", true),
    model("azure/gpt-5.5@swedencentral", "azure/gpt-5.5@swedencentral", true),
    model("azure/gpt-5@eastus2", "azure/gpt-5@eastus2", true),
    model("azure/gpt-5@francecentral", "azure/gpt-5@francecentral", true),
    model("azure/gpt-5@swedencentral", "azure/gpt-5@swedencentral", true),
    model("azure/gpt-5@uksouth", "azure/gpt-5@uksouth", true),
    model("azure/o4-mini@eastus2", "azure/o4-mini@eastus2", true),
    model("azure/o4-mini@francecentral", "azure/o4-mini@francecentral", true),
    model("azure/o4-mini@swedencentral", "azure/o4-mini@swedencentral", true),
    model("azure/o4-mini@uksouth", "azure/o4-mini@uksouth", true),
    model("azure/o4-mini@westus3", "azure/o4-mini@westus3", true),
    model("azure/openai-responses/gpt-4.1", "azure/openai-responses/gpt-4.1", false),
    model("azure/openai-responses/gpt-4.1-mini", "azure/openai-responses/gpt-4.1-mini", false),
    model("azure/openai-responses/gpt-4.1-mini@eastus2", "azure/openai-responses/gpt-4.1-mini@eastus2", false),
    model(
      "azure/openai-responses/gpt-4.1-mini@francecentral",
      "azure/openai-responses/gpt-4.1-mini@francecentral",
      false,
    ),
    model("azure/openai-responses/gpt-4.1-mini@westus3", "azure/openai-responses/gpt-4.1-mini@westus3", false),
    model("azure/openai-responses/gpt-4.1-nano", "azure/openai-responses/gpt-4.1-nano", false),
    model("azure/openai-responses/gpt-4.1-nano@eastus2", "azure/openai-responses/gpt-4.1-nano@eastus2", false),
    model(
      "azure/openai-responses/gpt-4.1-nano@francecentral",
      "azure/openai-responses/gpt-4.1-nano@francecentral",
      false,
    ),
    model(
      "azure/openai-responses/gpt-4.1-nano@swedencentral",
      "azure/openai-responses/gpt-4.1-nano@swedencentral",
      false,
    ),
    model("azure/openai-responses/gpt-4.1-nano@westus3", "azure/openai-responses/gpt-4.1-nano@westus3", false),
    model("azure/openai-responses/gpt-4.1@eastus2", "azure/openai-responses/gpt-4.1@eastus2", false),
    model("azure/openai-responses/gpt-4.1@francecentral", "azure/openai-responses/gpt-4.1@francecentral", false),
    model("azure/openai-responses/gpt-4.1@swedencentral", "azure/openai-responses/gpt-4.1@swedencentral", false),
    model("azure/openai-responses/gpt-4.1@westus3", "azure/openai-responses/gpt-4.1@westus3", false),
    model("azure/openai-responses/gpt-5.2-codex@eastus2", "azure/openai-responses/gpt-5.2-codex@eastus2", true),
    model("azure/openai-responses/gpt-5.4-pro@eastus2", "azure/openai-responses/gpt-5.4-pro@eastus2", true),
    model("azure/openai-responses/gpt-5.4@eastus2", "azure/openai-responses/gpt-5.4@eastus2", true),
    model("azure/openai-responses/gpt-5.4@francecentral", "azure/openai-responses/gpt-5.4@francecentral", true),
    model("azure/openai-responses/gpt-5.4@swedencentral", "azure/openai-responses/gpt-5.4@swedencentral", true),
    model("azure/openai-responses/gpt-5.5@eastus2", "azure/openai-responses/gpt-5.5@eastus2", true),
    model("azure/openai-responses/gpt-5.5@swedencentral", "azure/openai-responses/gpt-5.5@swedencentral", true),
    model("bedrock/claude-3-7-sonnet", "bedrock/claude-3-7-sonnet", true),
    model("bedrock/claude-3-7-sonnet@eu-central-1", "bedrock/claude-3-7-sonnet@eu-central-1", true),
    model("bedrock/claude-3-7-sonnet@eu-north-1", "bedrock/claude-3-7-sonnet@eu-north-1", true),
    model("bedrock/claude-3-7-sonnet@eu-west-1", "bedrock/claude-3-7-sonnet@eu-west-1", true),
    model("bedrock/claude-3-7-sonnet@eu-west-3", "bedrock/claude-3-7-sonnet@eu-west-3", true),
    model("bedrock/claude-3-7-sonnet@us-east-1", "bedrock/claude-3-7-sonnet@us-east-1", true),
    model("bedrock/claude-3-7-sonnet@us-east-2", "bedrock/claude-3-7-sonnet@us-east-2", true),
    model("bedrock/claude-3-7-sonnet@us-west-2", "bedrock/claude-3-7-sonnet@us-west-2", true),
    model("bedrock/claude-haiku-4-5", "bedrock/claude-haiku-4-5", true),
    model("bedrock/claude-haiku-4-5@eu-central-1", "bedrock/claude-haiku-4-5@eu-central-1", true),
    model("bedrock/claude-haiku-4-5@eu-north-1", "bedrock/claude-haiku-4-5@eu-north-1", true),
    model("bedrock/claude-haiku-4-5@eu-west-1", "bedrock/claude-haiku-4-5@eu-west-1", true),
    model("bedrock/claude-haiku-4-5@eu-west-3", "bedrock/claude-haiku-4-5@eu-west-3", true),
    model("bedrock/claude-haiku-4-5@us-east-1", "bedrock/claude-haiku-4-5@us-east-1", true),
    model("bedrock/claude-haiku-4-5@us-east-2", "bedrock/claude-haiku-4-5@us-east-2", true),
    model("bedrock/claude-haiku-4-5@us-west-2", "bedrock/claude-haiku-4-5@us-west-2", true),
    model("bedrock/claude-opus-4-5", "bedrock/claude-opus-4-5", true),
    model("bedrock/claude-opus-4-5@eu-central-1", "bedrock/claude-opus-4-5@eu-central-1", true),
    model("bedrock/claude-opus-4-5@eu-north-1", "bedrock/claude-opus-4-5@eu-north-1", true),
    model("bedrock/claude-opus-4-5@eu-west-1", "bedrock/claude-opus-4-5@eu-west-1", true),
    model("bedrock/claude-opus-4-5@eu-west-3", "bedrock/claude-opus-4-5@eu-west-3", true),
    model("bedrock/claude-opus-4-5@us-east-1", "bedrock/claude-opus-4-5@us-east-1", true),
    model("bedrock/claude-opus-4-5@us-east-2", "bedrock/claude-opus-4-5@us-east-2", true),
    model("bedrock/claude-opus-4-5@us-west-2", "bedrock/claude-opus-4-5@us-west-2", true),
    model("bedrock/claude-opus-4-6", "bedrock/claude-opus-4-6", true),
    model("bedrock/claude-opus-4-7", "bedrock/claude-opus-4-7", true),
    model("bedrock/claude-opus-4-7@eu-central-1", "bedrock/claude-opus-4-7@eu-central-1", true),
    model("bedrock/claude-opus-4-7@eu-north-1", "bedrock/claude-opus-4-7@eu-north-1", true),
    model("bedrock/claude-opus-4-7@eu-west-1", "bedrock/claude-opus-4-7@eu-west-1", true),
    model("bedrock/claude-opus-4-7@eu-west-3", "bedrock/claude-opus-4-7@eu-west-3", true),
    model("bedrock/claude-sonnet-4", "bedrock/claude-sonnet-4", true),
    model("bedrock/claude-sonnet-4-5", "bedrock/claude-sonnet-4-5", true),
    model("bedrock/claude-sonnet-4-5@eu-central-1", "bedrock/claude-sonnet-4-5@eu-central-1", true),
    model("bedrock/claude-sonnet-4-5@eu-north-1", "bedrock/claude-sonnet-4-5@eu-north-1", true),
    model("bedrock/claude-sonnet-4-5@eu-west-1", "bedrock/claude-sonnet-4-5@eu-west-1", true),
    model("bedrock/claude-sonnet-4-5@eu-west-3", "bedrock/claude-sonnet-4-5@eu-west-3", true),
    model("bedrock/claude-sonnet-4-5@us-east-1", "bedrock/claude-sonnet-4-5@us-east-1", true),
    model("bedrock/claude-sonnet-4-5@us-east-2", "bedrock/claude-sonnet-4-5@us-east-2", true),
    model("bedrock/claude-sonnet-4-5@us-west-2", "bedrock/claude-sonnet-4-5@us-west-2", true),
    model("bedrock/claude-sonnet-4-6", "bedrock/claude-sonnet-4-6", true),
    model("bedrock/claude-sonnet-4-6@eu-central-1", "bedrock/claude-sonnet-4-6@eu-central-1", true),
    model("bedrock/claude-sonnet-4-6@eu-north-1", "bedrock/claude-sonnet-4-6@eu-north-1", true),
    model("bedrock/claude-sonnet-4-6@eu-west-1", "bedrock/claude-sonnet-4-6@eu-west-1", true),
    model("bedrock/claude-sonnet-4-6@eu-west-3", "bedrock/claude-sonnet-4-6@eu-west-3", true),
    model("bedrock/claude-sonnet-4-6@us-east-1", "bedrock/claude-sonnet-4-6@us-east-1", true),
    model("bedrock/claude-sonnet-4-6@us-east-2", "bedrock/claude-sonnet-4-6@us-east-2", true),
    model("bedrock/claude-sonnet-4-6@us-west-2", "bedrock/claude-sonnet-4-6@us-west-2", true),
    model("bedrock/claude-sonnet-4@eu-central-1", "bedrock/claude-sonnet-4@eu-central-1", true),
    model("bedrock/claude-sonnet-4@eu-north-1", "bedrock/claude-sonnet-4@eu-north-1", true),
    model("bedrock/claude-sonnet-4@eu-west-1", "bedrock/claude-sonnet-4@eu-west-1", true),
    model("bedrock/claude-sonnet-4@eu-west-3", "bedrock/claude-sonnet-4@eu-west-3", true),
    model("bedrock/claude-sonnet-4@us-east-1", "bedrock/claude-sonnet-4@us-east-1", true),
    model("bedrock/claude-sonnet-4@us-east-2", "bedrock/claude-sonnet-4@us-east-2", true),
    model("bedrock/claude-sonnet-4@us-west-2", "bedrock/claude-sonnet-4@us-west-2", true),
    model("bedrock/kimi-k2.5@eu-north-1", "bedrock/kimi-k2.5@eu-north-1", true),
    model("bedrock/kimi-k2.5@eu-west-2", "bedrock/kimi-k2.5@eu-west-2", true),
    model("bedrock/kimi-k2.5@us-east-1", "bedrock/kimi-k2.5@us-east-1", true),
    model("bedrock/kimi-k2.5@us-east-2", "bedrock/kimi-k2.5@us-east-2", true),
    model("bedrock/kimi-k2.5@us-west-2", "bedrock/kimi-k2.5@us-west-2", true),
    model("coding/claude-opus-4-20250514", "coding/claude-opus-4-20250514", true),
    model("coding/claude-sonnet-4-20250514", "coding/claude-sonnet-4-20250514", true),
    model("coding/gemini-2.5-flash", "coding/gemini-2.5-flash", true),
    model("coding/gemini-2.5-flash@europe-central2", "coding/gemini-2.5-flash@europe-central2", true),
    model("coding/gemini-2.5-flash@europe-north1", "coding/gemini-2.5-flash@europe-north1", true),
    model("coding/gemini-2.5-flash@europe-west1", "coding/gemini-2.5-flash@europe-west1", true),
    model("coding/gemini-2.5-flash@europe-west4", "coding/gemini-2.5-flash@europe-west4", true),
    model("coding/gemini-2.5-flash@europe-west8", "coding/gemini-2.5-flash@europe-west8", true),
    model("coding/gemini-2.5-flash@us-central1", "coding/gemini-2.5-flash@us-central1", true),
    model("coding/gemini-2.5-flash@us-east1", "coding/gemini-2.5-flash@us-east1", true),
    model("coding/gemini-2.5-flash@us-east5", "coding/gemini-2.5-flash@us-east5", true),
    model("coding/gemini-2.5-flash@us-south1", "coding/gemini-2.5-flash@us-south1", true),
    model("coding/gemini-2.5-flash@us-west1", "coding/gemini-2.5-flash@us-west1", true),
    model("coding/gemini-2.5-pro", "coding/gemini-2.5-pro", true),
    model("coding/gemini-2.5-pro@europe-central2", "coding/gemini-2.5-pro@europe-central2", true),
    model("coding/gemini-2.5-pro@europe-north1", "coding/gemini-2.5-pro@europe-north1", true),
    model("coding/gemini-2.5-pro@europe-west1", "coding/gemini-2.5-pro@europe-west1", true),
    model("coding/gemini-2.5-pro@europe-west4", "coding/gemini-2.5-pro@europe-west4", true),
    model("coding/gemini-2.5-pro@europe-west8", "coding/gemini-2.5-pro@europe-west8", true),
    model("coding/gemini-2.5-pro@us-central1", "coding/gemini-2.5-pro@us-central1", true),
    model("coding/gemini-2.5-pro@us-east1", "coding/gemini-2.5-pro@us-east1", true),
    model("coding/gemini-2.5-pro@us-east5", "coding/gemini-2.5-pro@us-east5", true),
    model("coding/gemini-2.5-pro@us-south1", "coding/gemini-2.5-pro@us-south1", true),
    model("coding/gemini-2.5-pro@us-west1", "coding/gemini-2.5-pro@us-west1", true),
    model("deepinfra/deepseek-ai/DeepSeek-R1", "deepinfra/deepseek-ai/DeepSeek-R1", true),
    model(
      "deepinfra/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
      "deepinfra/deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
      true,
    ),
    model("deepinfra/deepseek-ai/DeepSeek-V3", "deepinfra/deepseek-ai/DeepSeek-V3", false),
    model("deepinfra/deepseek-ai/DeepSeek-V3.1", "deepinfra/deepseek-ai/DeepSeek-V3.1", true),
    model("deepinfra/Kimi K2.5", "deepinfra/Kimi K2.5", false),
    model(
      "deepinfra/meta-llama/Llama-3.2-90B-Vision-Instruct",
      "deepinfra/meta-llama/Llama-3.2-90B-Vision-Instruct",
      false,
    ),
    model("deepinfra/meta-llama/Llama-3.3-70B-Instruct", "deepinfra/meta-llama/Llama-3.3-70B-Instruct", false),
    model(
      "deepinfra/meta-llama/Llama-3.3-70B-Instruct-Turbo",
      "deepinfra/meta-llama/Llama-3.3-70B-Instruct-Turbo",
      false,
    ),
    model(
      "deepinfra/meta-llama/Meta-Llama-3.1-405B-Instruct",
      "deepinfra/meta-llama/Meta-Llama-3.1-405B-Instruct",
      false,
    ),
    model(
      "deepinfra/meta-llama/Meta-Llama-3.1-70B-Instruct",
      "deepinfra/meta-llama/Meta-Llama-3.1-70B-Instruct",
      false,
    ),
    model(
      "deepinfra/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
      "deepinfra/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
      false,
    ),
    model("deepinfra/microsoft/phi-4", "deepinfra/microsoft/phi-4", false),
    model("deepinfra/Qwen/Qwen2.5-72B-Instruct", "deepinfra/Qwen/Qwen2.5-72B-Instruct", false),
    model("deepinfra/Qwen/Qwen2.5-Coder-32B-Instruct", "deepinfra/Qwen/Qwen2.5-Coder-32B-Instruct", false),
    model("deepinfra/Qwen/Qwen3-235B-A22B", "deepinfra/Qwen/Qwen3-235B-A22B", false),
    model("deepinfra/Qwen/Qwen3-32B", "deepinfra/Qwen/Qwen3-32B", false),
    model("deepinfra/Qwen/Qwen3-Coder-480B-A35B-Instruct", "deepinfra/Qwen/Qwen3-Coder-480B-A35B-Instruct", false),
    model("deepinfra/zai-org/GLM-4.5", "deepinfra/zai-org/GLM-4.5", true),
    model("deepinfra/zai-org/GLM-4.5-Air", "deepinfra/zai-org/GLM-4.5-Air", true),
    model("deepseek/deepseek-chat", "deepseek/deepseek-chat", false),
    model("deepseek/deepseek-reasoner", "deepseek/deepseek-reasoner", true),
    model("deepseek/deepseek-v4-flash", "deepseek/deepseek-v4-flash", true),
    model("deepseek/deepseek-v4-pro", "deepseek/deepseek-v4-pro", true),
    model("fireworks/deepseek-v3.2", "fireworks/deepseek-v3.2", true),
    model("fireworks/deepseek-v4-pro", "fireworks/deepseek-v4-pro", true),
    model("fireworks/glm-5", "fireworks/glm-5", true),
    model("fireworks/glm-5.1", "fireworks/glm-5.1", true),
    model("fireworks/kimi-k2.5", "fireworks/kimi-k2.5", true),
    model("fireworks/kimi-k2.6", "fireworks/kimi-k2.6", true),
    model("fireworks/minimax-m2.5", "fireworks/minimax-m2.5", true),
    model("fireworks/minimax-m2.7", "fireworks/minimax-m2.7", true),
    model("fireworks/qwen3.6-plus", "fireworks/qwen3.6-plus", false),
    model("google/gemini-2.0-flash-001", "google/gemini-2.0-flash-001", false),
    model("google/gemini-2.5-flash", "google/gemini-2.5-flash", true),
    model("google/gemini-2.5-flash-lite", "google/gemini-2.5-flash-lite", true),
    model("google/gemini-2.5-pro", "google/gemini-2.5-pro", true),
    model("google/gemini-3-flash-preview", "google/gemini-3-flash-preview", true),
    model("google/gemini-3-pro-preview", "google/gemini-3-pro-preview", true),
    model("google/gemini-3.1-flash-image-preview", "google/gemini-3.1-flash-image-preview", true),
    model(
      "google/gemini-3.1-flash-image-preview@europe-central2",
      "google/gemini-3.1-flash-image-preview@europe-central2",
      true,
    ),
    model(
      "google/gemini-3.1-flash-image-preview@europe-north1",
      "google/gemini-3.1-flash-image-preview@europe-north1",
      true,
    ),
    model(
      "google/gemini-3.1-flash-image-preview@europe-west1",
      "google/gemini-3.1-flash-image-preview@europe-west1",
      true,
    ),
    model(
      "google/gemini-3.1-flash-image-preview@europe-west4",
      "google/gemini-3.1-flash-image-preview@europe-west4",
      true,
    ),
    model(
      "google/gemini-3.1-flash-image-preview@europe-west8",
      "google/gemini-3.1-flash-image-preview@europe-west8",
      true,
    ),
    model(
      "google/gemini-3.1-flash-image-preview@us-central1",
      "google/gemini-3.1-flash-image-preview@us-central1",
      true,
    ),
    model("google/gemini-3.1-flash-image-preview@us-east1", "google/gemini-3.1-flash-image-preview@us-east1", true),
    model("google/gemini-3.1-flash-image-preview@us-east5", "google/gemini-3.1-flash-image-preview@us-east5", true),
    model("google/gemini-3.1-flash-image-preview@us-south1", "google/gemini-3.1-flash-image-preview@us-south1", true),
    model("google/gemini-3.1-flash-image-preview@us-west1", "google/gemini-3.1-flash-image-preview@us-west1", true),
    model("google/gemini-3.1-flash-lite-preview", "google/gemini-3.1-flash-lite-preview", true),
    model("google/gemini-3.1-pro-preview", "google/gemini-3.1-pro-preview", true),
    model("groq/openai/gpt-oss-120b", "groq/openai/gpt-oss-120b", true),
    model("groq/openai/gpt-oss-20b", "groq/openai/gpt-oss-20b", true),
    model("inceptron/glm-5.1", "inceptron/glm-5.1", true),
    model("inceptron/kimi-k2.6", "inceptron/kimi-k2.6", true),
    model("inceptron/minimax-m2.5", "inceptron/minimax-m2.5", true),
    model("minimaxi/MiniMax-M2", "minimaxi/MiniMax-M2", false),
    model("minimaxi/MiniMax-M2.5", "minimaxi/MiniMax-M2.5", true),
    model("minimaxi/MiniMax-M2.5-highspeed", "minimaxi/MiniMax-M2.5-highspeed", true),
    model("minimaxi/MiniMax-M2.7", "minimaxi/MiniMax-M2.7", true),
    model("minimaxi/MiniMax-M2.7-highspeed", "minimaxi/MiniMax-M2.7-highspeed", true),
    model("mistral/codestral-latest", "mistral/codestral-latest", false),
    model("mistral/devstral-latest", "mistral/devstral-latest", false),
    model("mistral/devstral-medium-2507", "mistral/devstral-medium-2507", false),
    model("mistral/devstral-small-2507", "mistral/devstral-small-2507", false),
    model("mistral/devstral-small-latest", "mistral/devstral-small-latest", false),
    model("mistral/mistral-large-latest", "mistral/mistral-large-latest", false),
    model("mistral/mistral-medium-latest", "mistral/mistral-medium-latest", false),
    model("mistral/mistral-small-2503", "mistral/mistral-small-2503", false),
    model("mistral/mistral-small-2603", "mistral/mistral-small-2603", false),
    model("mistral/mistral-small-latest", "mistral/mistral-small-latest", false),
    model("mistral/open-mistral-7b", "mistral/open-mistral-7b", false),
    model("mistral/pixtral-large-latest", "mistral/pixtral-large-latest", false),
    model("moonshot/kimi-k2-0711-preview", "moonshot/kimi-k2-0711-preview", false),
    model("moonshot/kimi-k2-0905-preview", "moonshot/kimi-k2-0905-preview", false),
    model("moonshot/kimi-k2-thinking", "moonshot/kimi-k2-thinking", true),
    model("moonshot/kimi-k2-thinking-turbo", "moonshot/kimi-k2-thinking-turbo", true),
    model("moonshot/kimi-k2-turbo-preview", "moonshot/kimi-k2-turbo-preview", false),
    model("moonshot/kimi-k2.5", "moonshot/kimi-k2.5", true),
    model("moonshot/kimi-k2.6", "moonshot/kimi-k2.6", true),
    model("nebius/deepseek-ai/DeepSeek-V3.2", "nebius/deepseek-ai/DeepSeek-V3.2", true),
    model("nebius/meta-llama/Llama-3.3-70B-Instruct", "nebius/meta-llama/Llama-3.3-70B-Instruct", false),
    model("nebius/moonshotai/kimi-k2.5", "nebius/moonshotai/kimi-k2.5", true),
    model("nebius/openai/gpt-oss-120b", "nebius/openai/gpt-oss-120b", true),
    model("novita/deepseek/deepseek_v3", "novita/deepseek/deepseek_v3", false),
    model("novita/deepseek/deepseek-prover-v2-671b", "novita/deepseek/deepseek-prover-v2-671b", false),
    model("novita/deepseek/deepseek-r1", "novita/deepseek/deepseek-r1", true),
    model("novita/deepseek/deepseek-r1-distill-llama-70b", "novita/deepseek/deepseek-r1-distill-llama-70b", true),
    model("novita/deepseek/deepseek-r1-distill-qwen-14b", "novita/deepseek/deepseek-r1-distill-qwen-14b", true),
    model("novita/deepseek/deepseek-r1-distill-qwen-32b", "novita/deepseek/deepseek-r1-distill-qwen-32b", true),
    model("novita/deepseek/deepseek-r1-turbo", "novita/deepseek/deepseek-r1-turbo", true),
    model("novita/deepseek/deepseek-v3-0324", "novita/deepseek/deepseek-v3-0324", false),
    model("novita/deepseek/deepseek-v3-turbo", "novita/deepseek/deepseek-v3-turbo", false),
    model("novita/deepseek/deepseek-v3.2", "novita/deepseek/deepseek-v3.2", true),
    model("novita/GLM-5", "novita/GLM-5", true),
    model("novita/gryphe/mythomax-l2-13b", "novita/gryphe/mythomax-l2-13b", false),
    model("novita/meta-llama/llama-3-70b-instruct", "novita/meta-llama/llama-3-70b-instruct", false),
    model("novita/meta-llama/llama-3-8b-instruct", "novita/meta-llama/llama-3-8b-instruct", false),
    model("novita/meta-llama/llama-3.1-8b-instruct", "novita/meta-llama/llama-3.1-8b-instruct", false),
    model("novita/meta-llama/llama-3.2-1b-instruct", "novita/meta-llama/llama-3.2-1b-instruct", false),
    model("novita/meta-llama/llama-3.2-3b-instruct", "novita/meta-llama/llama-3.2-3b-instruct", false),
    model("novita/meta-llama/llama-3.3-70b-instruct", "novita/meta-llama/llama-3.3-70b-instruct", false),
    model(
      "novita/meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
      "novita/meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
      false,
    ),
    model("novita/microsoft/wizardlm-2-8x22b", "novita/microsoft/wizardlm-2-8x22b", false),
    model("novita/minimax/minimax-m2.7", "novita/minimax/minimax-m2.7", true),
    model("novita/mistralai/mistral-nemo", "novita/mistralai/mistral-nemo", false),
    model("novita/moonshotai/kimi-k2-instruct", "novita/moonshotai/kimi-k2-instruct", false),
    model("novita/nousresearch/hermes-2-pro-llama-3-8b", "novita/nousresearch/hermes-2-pro-llama-3-8b", false),
    model("novita/qwen/qwen-2.5-72b-instruct", "novita/qwen/qwen-2.5-72b-instruct", false),
    model("novita/qwen/qwen2.5-vl-72b-instruct", "novita/qwen/qwen2.5-vl-72b-instruct", false),
    model("novita/qwen/qwen3-235b-a22b-fp8", "novita/qwen/qwen3-235b-a22b-fp8", false),
    model("novita/qwen/qwen3.5-397b-a17b", "novita/qwen/qwen3.5-397b-a17b", true),
    model("novita/sao10k/l3-70b-euryale-v2.1", "novita/sao10k/l3-70b-euryale-v2.1", false),
    model("novita/sao10k/l3-8b-lunaris", "novita/sao10k/l3-8b-lunaris", false),
    model("novita/Sao10K/L3-8B-Stheno-v3.2", "novita/Sao10K/L3-8B-Stheno-v3.2", false),
    model("novita/sao10k/l31-70b-euryale-v2.2", "novita/sao10k/l31-70b-euryale-v2.2", false),
    model("novita/zai-org/glm-4.5", "novita/zai-org/glm-4.5", true),
    model("novita/zai-org/glm-4.6", "novita/zai-org/glm-4.6", true),
    model("openai-responses/gpt-4.1", "openai-responses/gpt-4.1", false),
    model("openai-responses/gpt-4.1-mini", "openai-responses/gpt-4.1-mini", false),
    model("openai-responses/gpt-4.1-nano", "openai-responses/gpt-4.1-nano", false),
    model("openai-responses/gpt-5", "openai-responses/gpt-5", true),
    model("openai-responses/gpt-5-codex", "openai-responses/gpt-5-codex", true),
    model("openai-responses/gpt-5-mini", "openai-responses/gpt-5-mini", true),
    model("openai-responses/gpt-5-nano", "openai-responses/gpt-5-nano", true),
    model("openai-responses/gpt-5-pro", "openai-responses/gpt-5-pro", true),
    model("openai-responses/gpt-5.1", "openai-responses/gpt-5.1", true),
    model("openai-responses/gpt-5.1-codex", "openai-responses/gpt-5.1-codex", true),
    model("openai-responses/gpt-5.2", "openai-responses/gpt-5.2", true),
    model("openai-responses/gpt-5.2-codex", "openai-responses/gpt-5.2-codex", true),
    model("openai-responses/gpt-5.3-chat", "openai-responses/gpt-5.3-chat", true),
    model("openai-responses/gpt-5.3-codex", "openai-responses/gpt-5.3-codex", true),
    model("openai-responses/gpt-5.4", "openai-responses/gpt-5.4", true),
    model("openai-responses/gpt-5.4-mini", "openai-responses/gpt-5.4-mini", true),
    model("openai-responses/gpt-5.4-nano", "openai-responses/gpt-5.4-nano", true),
    model("openai-responses/gpt-5.4-pro", "openai-responses/gpt-5.4-pro", true),
    model("openai-responses/gpt-5.5", "openai-responses/gpt-5.5", true),
    model("openai-responses/gpt-5.5-pro", "openai-responses/gpt-5.5-pro", true),
    model("openai-responses/o3-mini", "openai-responses/o3-mini", true),
    model("openai-responses/o3-pro", "openai-responses/o3-pro", true),
    model("openai-responses/o4-mini", "openai-responses/o4-mini", true),
    model("openai/chatgpt-4o", "openai/chatgpt-4o", false),
    model("openai/gpt-4.1", "openai/gpt-4.1", false),
    model("openai/gpt-4.1-mini", "openai/gpt-4.1-mini", false),
    model("openai/gpt-4.1-nano", "openai/gpt-4.1-nano", false),
    model("openai/gpt-4o", "openai/gpt-4o", false),
    model("openai/gpt-4o-2024-05-13", "openai/gpt-4o-2024-05-13", false),
    model("openai/gpt-4o-2024-08-06", "openai/gpt-4o-2024-08-06", false),
    model("openai/gpt-4o-2024-11-20", "openai/gpt-4o-2024-11-20", false),
    model("openai/gpt-4o-mini", "openai/gpt-4o-mini", false),
    model("openai/gpt-5", "openai/gpt-5", true),
    model("openai/gpt-5-chat", "openai/gpt-5-chat", false),
    model("openai/gpt-5-mini", "openai/gpt-5-mini", true),
    model("openai/gpt-5-mini:flex", "openai/gpt-5-mini:flex", true),
    model("openai/gpt-5-mini:priority", "openai/gpt-5-mini:priority", true),
    model("openai/gpt-5-nano", "openai/gpt-5-nano", true),
    model("openai/gpt-5-nano:flex", "openai/gpt-5-nano:flex", true),
    model("openai/gpt-5:flex", "openai/gpt-5:flex", true),
    model("openai/gpt-5:priority", "openai/gpt-5:priority", true),
    model("openai/gpt-5.1", "openai/gpt-5.1", true),
    model("openai/gpt-5.1-chat", "openai/gpt-5.1-chat", true),
    model("openai/gpt-5.2", "openai/gpt-5.2", true),
    model("openai/gpt-5.2-chat", "openai/gpt-5.2-chat", true),
    model("openai/gpt-5.3-chat", "openai/gpt-5.3-chat", true),
    model("openai/gpt-5.4", "openai/gpt-5.4", true),
    model("openai/gpt-5.4-mini", "openai/gpt-5.4-mini", true),
    model("openai/gpt-5.4-nano", "openai/gpt-5.4-nano", true),
    model("openai/gpt-5.4-pro", "openai/gpt-5.4-pro", true),
    model("openai/gpt-5.5", "openai/gpt-5.5", true),
    model("openai/gpt-5.5-pro", "openai/gpt-5.5-pro", true),
    model("openai/o1", "openai/o1", true),
    model("openai/o1-pro", "openai/o1-pro", true),
    model("openai/o1:high", "openai/o1:high", false),
    model("openai/o1:low", "openai/o1:low", false),
    model("openai/o1:medium", "openai/o1:medium", false),
    model("openai/o3", "openai/o3", true),
    model("openai/o3-deep-research", "openai/o3-deep-research", true),
    model("openai/o3-mini", "openai/o3-mini", true),
    model("openai/o3-mini:high", "openai/o3-mini:high", true),
    model("openai/o3-mini:low", "openai/o3-mini:low", true),
    model("openai/o3-mini:medium", "openai/o3-mini:medium", true),
    model("openai/o3:flex", "openai/o3:flex", false),
    model("openai/o4-mini", "openai/o4-mini", true),
    model("openai/o4-mini-deep-research", "openai/o4-mini-deep-research", true),
    model("openai/o4-mini:flex", "openai/o4-mini:flex", true),
    model("openai/o4-mini:high", "openai/o4-mini:high", true),
    model("openai/o4-mini:low", "openai/o4-mini:low", true),
    model("openai/o4-mini:medium", "openai/o4-mini:medium", true),
    model("parasail/Kimi K2.5", "parasail/Kimi K2.5", false),
    model("parasail/parasail-gemma3-27b-it", "parasail/parasail-gemma3-27b-it", false),
    model("parasail/parasail-kimi-k2-instruct", "parasail/parasail-kimi-k2-instruct", false),
    model("parasail/parasail-qwen25-vl-72b-instruct", "parasail/parasail-qwen25-vl-72b-instruct", false),
    model("parasail/parasail-qwen3-235b-a22b-instruct-2507", "parasail/parasail-qwen3-235b-a22b-instruct-2507", false),
    model("perplexity/sonar", "perplexity/sonar", false),
    model("perplexity/sonar-pro", "perplexity/sonar-pro", false),
    model("perplexity/sonar-reasoning-pro", "perplexity/sonar-reasoning-pro", true),
    model("together/deepseek-ai/DeepSeek-R1", "together/deepseek-ai/DeepSeek-R1", true),
    model("together/deepseek-ai/DeepSeek-V3", "together/deepseek-ai/DeepSeek-V3", false),
    model("together/Kimi K2.5", "together/Kimi K2.5", false),
    model("together/meta-llama/Llama-3.2-3B-Instruct-Turbo", "together/meta-llama/Llama-3.2-3B-Instruct-Turbo", false),
    model(
      "together/meta-llama/Llama-3.3-70B-Instruct-Turbo",
      "together/meta-llama/Llama-3.3-70B-Instruct-Turbo",
      false,
    ),
    model("together/meta-llama/LlamaGuard-2-8b", "together/meta-llama/LlamaGuard-2-8b", false),
    model(
      "together/meta-llama/Meta-Llama-3-8B-Instruct-Lite",
      "together/meta-llama/Meta-Llama-3-8B-Instruct-Lite",
      false,
    ),
    model(
      "together/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
      "together/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
      false,
    ),
    model(
      "together/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
      "together/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
      false,
    ),
    model("together/Qwen/Qwen2.5-72B-Instruct-Turbo", "together/Qwen/Qwen2.5-72B-Instruct-Turbo", false),
    model("together/Qwen/Qwen2.5-7B-Instruct-Turbo", "together/Qwen/Qwen2.5-7B-Instruct-Turbo", false),
    model("vertex/claude-3-7-sonnet", "vertex/claude-3-7-sonnet", true),
    model("vertex/claude-3-7-sonnet@europe-west1", "vertex/claude-3-7-sonnet@europe-west1", true),
    model("vertex/claude-3-7-sonnet@us-east5", "vertex/claude-3-7-sonnet@us-east5", true),
    model("vertex/claude-haiku-4-5", "vertex/claude-haiku-4-5", true),
    model("vertex/claude-haiku-4-5@europe-west1", "vertex/claude-haiku-4-5@europe-west1", true),
    model("vertex/claude-haiku-4-5@us-east5", "vertex/claude-haiku-4-5@us-east5", true),
    model("vertex/claude-opus-4", "vertex/claude-opus-4", true),
    model("vertex/claude-opus-4-1", "vertex/claude-opus-4-1", true),
    model("vertex/claude-opus-4-1@europe-west1", "vertex/claude-opus-4-1@europe-west1", true),
    model("vertex/claude-opus-4-1@us-east5", "vertex/claude-opus-4-1@us-east5", true),
    model("vertex/claude-opus-4-5", "vertex/claude-opus-4-5", true),
    model("vertex/claude-opus-4-5@europe-west1", "vertex/claude-opus-4-5@europe-west1", true),
    model("vertex/claude-opus-4-5@us-east5", "vertex/claude-opus-4-5@us-east5", true),
    model("vertex/claude-opus-4-6", "vertex/claude-opus-4-6", true),
    model("vertex/claude-opus-4-6@europe-west1", "vertex/claude-opus-4-6@europe-west1", true),
    model("vertex/claude-opus-4-6@us-east5", "vertex/claude-opus-4-6@us-east5", true),
    model("vertex/claude-opus-4-7", "vertex/claude-opus-4-7", true),
    model("vertex/claude-opus-4-7@europe-west1", "vertex/claude-opus-4-7@europe-west1", true),
    model("vertex/claude-opus-4-7@europe-west2", "vertex/claude-opus-4-7@europe-west2", true),
    model("vertex/claude-opus-4-7@europe-west3", "vertex/claude-opus-4-7@europe-west3", true),
    model("vertex/claude-opus-4-7@europe-west4", "vertex/claude-opus-4-7@europe-west4", true),
    model("vertex/claude-opus-4-7@europe-west6", "vertex/claude-opus-4-7@europe-west6", true),
    model("vertex/claude-opus-4-7@us-central-1", "vertex/claude-opus-4-7@us-central-1", true),
    model("vertex/claude-opus-4-7@us-east1", "vertex/claude-opus-4-7@us-east1", true),
    model("vertex/claude-opus-4-7@us-west-1", "vertex/claude-opus-4-7@us-west-1", true),
    model("vertex/claude-opus-4@europe-west1", "vertex/claude-opus-4@europe-west1", true),
    model("vertex/claude-opus-4@us-east5", "vertex/claude-opus-4@us-east5", true),
    model("vertex/claude-sonnet-4", "vertex/claude-sonnet-4", true),
    model("vertex/claude-sonnet-4-5", "vertex/claude-sonnet-4-5", true),
    model("vertex/claude-sonnet-4-5@europe-west1", "vertex/claude-sonnet-4-5@europe-west1", true),
    model("vertex/claude-sonnet-4-5@us-east5", "vertex/claude-sonnet-4-5@us-east5", true),
    model("vertex/claude-sonnet-4-6", "vertex/claude-sonnet-4-6", true),
    model("vertex/claude-sonnet-4-6@europe-west1", "vertex/claude-sonnet-4-6@europe-west1", true),
    model("vertex/claude-sonnet-4-6@us-east5", "vertex/claude-sonnet-4-6@us-east5", true),
    model("vertex/claude-sonnet-4@europe-west1", "vertex/claude-sonnet-4@europe-west1", true),
    model("vertex/claude-sonnet-4@us-east5", "vertex/claude-sonnet-4@us-east5", true),
    model("vertex/deepseek-v3.2", "vertex/deepseek-v3.2", true),
    model("vertex/gemini-2.5-flash", "vertex/gemini-2.5-flash", true),
    model("vertex/gemini-2.5-flash-image", "vertex/gemini-2.5-flash-image", true),
    model("vertex/gemini-2.5-flash-lite", "vertex/gemini-2.5-flash-lite", true),
    model("vertex/gemini-2.5-flash-lite@europe-central2", "vertex/gemini-2.5-flash-lite@europe-central2", true),
    model("vertex/gemini-2.5-flash-lite@europe-north1", "vertex/gemini-2.5-flash-lite@europe-north1", true),
    model("vertex/gemini-2.5-flash-lite@europe-west1", "vertex/gemini-2.5-flash-lite@europe-west1", true),
    model("vertex/gemini-2.5-flash-lite@europe-west4", "vertex/gemini-2.5-flash-lite@europe-west4", true),
    model("vertex/gemini-2.5-flash-lite@europe-west8", "vertex/gemini-2.5-flash-lite@europe-west8", true),
    model("vertex/gemini-2.5-flash-lite@us-central1", "vertex/gemini-2.5-flash-lite@us-central1", true),
    model("vertex/gemini-2.5-flash-lite@us-east1", "vertex/gemini-2.5-flash-lite@us-east1", true),
    model("vertex/gemini-2.5-flash-lite@us-east5", "vertex/gemini-2.5-flash-lite@us-east5", true),
    model("vertex/gemini-2.5-flash-lite@us-south1", "vertex/gemini-2.5-flash-lite@us-south1", true),
    model("vertex/gemini-2.5-flash-lite@us-west1", "vertex/gemini-2.5-flash-lite@us-west1", true),
    model("vertex/gemini-2.5-flash@europe-central2", "vertex/gemini-2.5-flash@europe-central2", true),
    model("vertex/gemini-2.5-flash@europe-north1", "vertex/gemini-2.5-flash@europe-north1", true),
    model("vertex/gemini-2.5-flash@europe-west1", "vertex/gemini-2.5-flash@europe-west1", true),
    model("vertex/gemini-2.5-flash@europe-west4", "vertex/gemini-2.5-flash@europe-west4", true),
    model("vertex/gemini-2.5-flash@europe-west8", "vertex/gemini-2.5-flash@europe-west8", true),
    model("vertex/gemini-2.5-flash@us-central1", "vertex/gemini-2.5-flash@us-central1", true),
    model("vertex/gemini-2.5-flash@us-east1", "vertex/gemini-2.5-flash@us-east1", true),
    model("vertex/gemini-2.5-flash@us-east5", "vertex/gemini-2.5-flash@us-east5", true),
    model("vertex/gemini-2.5-flash@us-south1", "vertex/gemini-2.5-flash@us-south1", true),
    model("vertex/gemini-2.5-flash@us-west1", "vertex/gemini-2.5-flash@us-west1", true),
    model("vertex/gemini-2.5-pro", "vertex/gemini-2.5-pro", true),
    model("vertex/gemini-2.5-pro@europe-central2", "vertex/gemini-2.5-pro@europe-central2", true),
    model("vertex/gemini-2.5-pro@europe-north1", "vertex/gemini-2.5-pro@europe-north1", true),
    model("vertex/gemini-2.5-pro@europe-west1", "vertex/gemini-2.5-pro@europe-west1", true),
    model("vertex/gemini-2.5-pro@europe-west4", "vertex/gemini-2.5-pro@europe-west4", true),
    model("vertex/gemini-2.5-pro@europe-west8", "vertex/gemini-2.5-pro@europe-west8", true),
    model("vertex/gemini-2.5-pro@us-central1", "vertex/gemini-2.5-pro@us-central1", true),
    model("vertex/gemini-2.5-pro@us-east1", "vertex/gemini-2.5-pro@us-east1", true),
    model("vertex/gemini-2.5-pro@us-east5", "vertex/gemini-2.5-pro@us-east5", true),
    model("vertex/gemini-2.5-pro@us-south1", "vertex/gemini-2.5-pro@us-south1", true),
    model("vertex/gemini-2.5-pro@us-west1", "vertex/gemini-2.5-pro@us-west1", true),
    model("vertex/gemini-3-flash-preview", "vertex/gemini-3-flash-preview", true),
    model("vertex/gemini-3-pro-image-preview", "vertex/gemini-3-pro-image-preview", true),
    model("vertex/gemini-3-pro-preview", "vertex/gemini-3-pro-preview", true),
    model("vertex/gemini-3.1-flash-image-preview", "vertex/gemini-3.1-flash-image-preview", true),
    model("vertex/gemini-3.1-flash-lite", "vertex/gemini-3.1-flash-lite", true),
    model("vertex/gemini-3.1-flash-lite-preview", "vertex/gemini-3.1-flash-lite-preview", true),
    model("vertex/gemini-3.1-pro-preview", "vertex/gemini-3.1-pro-preview", true),
    model("vertex/kimi-k2", "vertex/kimi-k2", false),
    model("xai/grok-2-1212", "xai/grok-2-1212", false),
    model("xai/grok-3", "xai/grok-3", false),
    model("xai/grok-3-mini", "xai/grok-3-mini", false),
    model("xai/grok-3-mini:high", "xai/grok-3-mini:high", false),
    model("xai/grok-3-mini:low", "xai/grok-3-mini:low", false),
    model("xai/grok-4", "xai/grok-4", false),
    model("xai/grok-4-1-fast-non-reasoning", "xai/grok-4-1-fast-non-reasoning", false),
    model("xai/grok-4-1-fast-reasoning", "xai/grok-4-1-fast-reasoning", true),
    model("xai/grok-4-fast", "xai/grok-4-fast", false),
    model("xai/grok-4-fast-non-reasoning", "xai/grok-4-fast-non-reasoning", false),
    model("xai/grok-4.2-beta", "xai/grok-4.2-beta", false),
    model("xai/grok-4.3", "xai/grok-4.3", false),
    model("xai/grok-code-fast-1", "xai/grok-code-fast-1", false),
    model("zai/GLM-4.5", "zai/GLM-4.5", true),
    model("zai/GLM-4.6", "zai/GLM-4.6", true),
    model("zai/GLM-4.7", "zai/GLM-4.7", true),
    model("zai/GLM-5", "zai/GLM-5", true),
    model("zai/GLM-5.1", "zai/GLM-5.1", true),
  ],
}
