import type { ProviderPreset } from './types'

export const SapaicorePreset: ProviderPreset = {
  id: "sapaicore",
  name: "SAP AI Core",
  baseURL: "https://api.ai.prod.eu-central-1.aws.ml.hana.ondemand.com",
  note: "Select SAP AI Core model IDs copied from Cline local model data.",
  fetch: false,
  models: [
    { id: "anthropic--claude-4.5-haiku", name: "Anthropic  Claude 4.5 Haiku" },
    { id: "anthropic--claude-4.6-sonnet", name: "Anthropic  Claude 4.6 Sonnet" },
    { id: "anthropic--claude-4.5-sonnet", name: "Anthropic  Claude 4.5 Sonnet" },
    { id: "anthropic--claude-4-sonnet", name: "Anthropic  Claude 4 Sonnet" },
    { id: "anthropic--claude-4.5-opus", name: "Anthropic  Claude 4.5 Opus" },
    { id: "anthropic--claude-4-opus", name: "Anthropic  Claude 4 Opus" },
    { id: "anthropic--claude-3.7-sonnet", name: "Anthropic  Claude 3.7 Sonnet" },
    { id: "anthropic--claude-3.5-sonnet", name: "Anthropic  Claude 3.5 Sonnet" },
    { id: "anthropic--claude-3-sonnet", name: "Anthropic  Claude 3 Sonnet" },
    { id: "anthropic--claude-3-haiku", name: "Anthropic  Claude 3 Haiku" },
    { id: "anthropic--claude-3-opus", name: "Anthropic  Claude 3 Opus" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", reasoning: true },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", reasoning: true },
    { id: "gpt-4", name: "Gpt 4" },
    { id: "gpt-4o", name: "Gpt 4o" },
    { id: "gpt-4o-mini", name: "Gpt 4o Mini" },
    { id: "gpt-4.1", name: "Gpt 4.1" },
    { id: "gpt-4.1-nano", name: "Gpt 4.1 Nano" },
    { id: "gpt-5", name: "Gpt 5" },
    { id: "gpt-5-nano", name: "Gpt 5 Nano" },
    { id: "gpt-5-mini", name: "Gpt 5 Mini" },
    { id: "gpt-5.2", name: "Gpt 5.2" },
    { id: "gpt-5.4", name: "Gpt 5.4" },
    { id: "gpt-5.4-nano", name: "Gpt 5.4 Nano" },
    { id: "o1", name: "O1" },
    { id: "o3", name: "O3" },
    { id: "o3-mini", name: "O3 Mini" },
    { id: "o4-mini", name: "O4 Mini" },
    { id: "sonar", name: "Sonar" },
    { id: "sonar-pro", name: "Sonar Pro" },
  ],
}
