import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const VenicePreset: ProviderPreset = {
  id: "venice",
  name: "Venice",
  baseURL: "https://api.venice.ai/api/v1",
  note: "Seeded from Venice official /models catalog (75 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("aion-labs-aion-2-0", "aion-labs-aion-2-0", false),
    model("arcee-trinity-large-thinking", "arcee-trinity-large-thinking", false),
    model("claude-opus-4-5", "claude-opus-4-5", true),
    model("claude-opus-4-6", "claude-opus-4-6", true),
    model("claude-opus-4-6-fast", "claude-opus-4-6-fast", true),
    model("claude-opus-4-7", "claude-opus-4-7", true),
    model("claude-sonnet-4-5", "claude-sonnet-4-5", true),
    model("claude-sonnet-4-6", "claude-sonnet-4-6", true),
    model("deepseek-v3.2", "deepseek-v3.2", true),
    model("deepseek-v4-flash", "deepseek-v4-flash", true),
    model("deepseek-v4-pro", "deepseek-v4-pro", true),
    model("e2ee-gemma-3-27b-p", "e2ee-gemma-3-27b-p", false),
    model("e2ee-glm-4-7-flash-p", "e2ee-glm-4-7-flash-p", false),
    model("e2ee-glm-4-7-p", "e2ee-glm-4-7-p", false),
    model("e2ee-glm-5-1", "e2ee-glm-5-1", true),
    model("e2ee-gpt-oss-120b-p", "e2ee-gpt-oss-120b-p", true),
    model("e2ee-gpt-oss-20b-p", "e2ee-gpt-oss-20b-p", true),
    model("e2ee-qwen-2-5-7b-p", "e2ee-qwen-2-5-7b-p", false),
    model("e2ee-qwen3-30b-a3b-p", "e2ee-qwen3-30b-a3b-p", false),
    model("e2ee-qwen3-5-122b-a10b", "e2ee-qwen3-5-122b-a10b", false),
    model("e2ee-qwen3-vl-30b-a3b-p", "e2ee-qwen3-vl-30b-a3b-p", false),
    model("e2ee-venice-uncensored-24b-p", "e2ee-venice-uncensored-24b-p", false),
    model("gemini-3-1-pro-preview", "gemini-3-1-pro-preview", true),
    model("gemini-3-flash-preview", "gemini-3-flash-preview", true),
    model("gemma-4-uncensored", "gemma-4-uncensored", false),
    model("google-gemma-3-27b-it", "google-gemma-3-27b-it", false),
    model("google-gemma-4-26b-a4b-it", "google-gemma-4-26b-a4b-it", false),
    model("google-gemma-4-31b-it", "google-gemma-4-31b-it", false),
    model("grok-4-20", "grok-4-20", false),
    model("grok-4-20-multi-agent", "grok-4-20-multi-agent", false),
    model("grok-4-3", "grok-4-3", false),
    model("grok-41-fast", "grok-41-fast", false),
    model("hermes-3-llama-3.1-405b", "hermes-3-llama-3.1-405b", false),
    model("kimi-k2-5", "kimi-k2-5", false),
    model("kimi-k2-6", "kimi-k2-6", false),
    model("llama-3.2-3b", "llama-3.2-3b", false),
    model("llama-3.3-70b", "llama-3.3-70b", false),
    model("mercury-2", "mercury-2", false),
    model("minimax-m25", "minimax-m25", false),
    model("minimax-m27", "minimax-m27", false),
    model("mistral-small-2603", "mistral-small-2603", false),
    model("mistral-small-3-2-24b-instruct", "mistral-small-3-2-24b-instruct", false),
    model("nvidia-nemotron-3-nano-30b-a3b", "nvidia-nemotron-3-nano-30b-a3b", true),
    model("nvidia-nemotron-cascade-2-30b-a3b", "nvidia-nemotron-cascade-2-30b-a3b", false),
    model("olafangensan-glm-4.7-flash-heretic", "olafangensan-glm-4.7-flash-heretic", true),
    model("openai-gpt-4o-2024-11-20", "openai-gpt-4o-2024-11-20", false),
    model("openai-gpt-4o-mini-2024-07-18", "openai-gpt-4o-mini-2024-07-18", false),
    model("openai-gpt-52", "openai-gpt-52", false),
    model("openai-gpt-52-codex", "openai-gpt-52-codex", false),
    model("openai-gpt-53-codex", "openai-gpt-53-codex", false),
    model("openai-gpt-54", "openai-gpt-54", false),
    model("openai-gpt-54-mini", "openai-gpt-54-mini", false),
    model("openai-gpt-54-pro", "openai-gpt-54-pro", false),
    model("openai-gpt-55", "openai-gpt-55", false),
    model("openai-gpt-55-pro", "openai-gpt-55-pro", false),
    model("openai-gpt-oss-120b", "openai-gpt-oss-120b", true),
    model("qwen-3-6-plus", "qwen-3-6-plus", false),
    model("qwen3-235b-a22b-instruct-2507", "qwen3-235b-a22b-instruct-2507", false),
    model("qwen3-235b-a22b-thinking-2507", "qwen3-235b-a22b-thinking-2507", true),
    model("qwen3-5-35b-a3b", "qwen3-5-35b-a3b", false),
    model("qwen3-5-397b-a17b", "qwen3-5-397b-a17b", false),
    model("qwen3-5-9b", "qwen3-5-9b", false),
    model("qwen3-6-27b", "qwen3-6-27b", false),
    model("qwen3-coder-480b-a35b-instruct-turbo", "qwen3-coder-480b-a35b-instruct-turbo", false),
    model("qwen3-next-80b", "qwen3-next-80b", false),
    model("qwen3-vl-235b-a22b", "qwen3-vl-235b-a22b", false),
    model("venice-uncensored-1-2", "venice-uncensored-1-2", false),
    model("venice-uncensored-role-play", "venice-uncensored-role-play", false),
    model("z-ai-glm-5-turbo", "z-ai-glm-5-turbo", true),
    model("z-ai-glm-5v-turbo", "z-ai-glm-5v-turbo", true),
    model("zai-org-glm-4.6", "zai-org-glm-4.6", true),
    model("zai-org-glm-4.7", "zai-org-glm-4.7", true),
    model("zai-org-glm-4.7-flash", "zai-org-glm-4.7-flash", true),
    model("zai-org-glm-5", "zai-org-glm-5", true),
    model("zai-org-glm-5-1", "zai-org-glm-5-1", true),
  ],
}
