import type { ProviderPreset, ProviderPresetModel } from "./types"

const variants = Object.fromEntries(
  ["low", "medium", "high", "xhigh"].map((reasoningEffort) => [reasoningEffort, { reasoningEffort }]),
)

function model(id: string, name: string, reasoning = false): ProviderPresetModel {
  if (!reasoning) return { id, name }
  return { id, name, reasoning, variants }
}

export const VercelAiGatewayPreset: ProviderPreset = {
  id: "vercel-ai-gateway",
  name: "Vercel AI Gateway",
  baseURL: "https://ai-gateway.vercel.sh/v1",
  note: "Seeded from Vercel AI Gateway official /models catalog (276 models). Use Refresh after entering an API key if the provider changes it.",
  fetch: true,
  models: [
    model("alibaba/qwen-3-14b", "Qwen3-14B", false),
    model("alibaba/qwen-3-235b", "Qwen3 235B A22b Instruct 2507", false),
    model("alibaba/qwen-3-30b", "Qwen3-30B-A3B", false),
    model("alibaba/qwen-3-32b", "Qwen 3 32B", false),
    model("alibaba/qwen-3.6-max-preview", "Qwen 3.6 Max Preview", false),
    model("alibaba/qwen3-235b-a22b-thinking", "Qwen3 VL 235B A22B Thinking", true),
    model("alibaba/qwen3-coder", "Qwen3 Coder 480B A35B Instruct", false),
    model("alibaba/qwen3-coder-30b-a3b", "Qwen 3 Coder 30B A3B Instruct", false),
    model("alibaba/qwen3-coder-next", "Qwen3 Coder Next", false),
    model("alibaba/qwen3-coder-plus", "Qwen3 Coder Plus", false),
    model("alibaba/qwen3-embedding-0.6b", "Qwen3 Embedding 0.6B", false),
    model("alibaba/qwen3-embedding-4b", "Qwen3 Embedding 4B", false),
    model("alibaba/qwen3-embedding-8b", "Qwen3 Embedding 8B", false),
    model("alibaba/qwen3-max", "Qwen3 Max", false),
    model("alibaba/qwen3-max-preview", "Qwen3 Max Preview", false),
    model("alibaba/qwen3-max-thinking", "Qwen 3 Max Thinking", true),
    model("alibaba/qwen3-next-80b-a3b-instruct", "Qwen3 Next 80B A3B Instruct", false),
    model("alibaba/qwen3-next-80b-a3b-thinking", "Qwen3 Next 80B A3B Thinking", true),
    model("alibaba/qwen3-vl-235b-a22b-instruct", "Qwen3 VL 235B A22B Instruct", false),
    model("alibaba/qwen3-vl-instruct", "Qwen3 VL 235B A22B Instruct", false),
    model("alibaba/qwen3-vl-thinking", "Qwen3 VL 235B A22B Thinking", true),
    model("alibaba/qwen3.5-flash", "Qwen 3.5 Flash", true),
    model("alibaba/qwen3.5-plus", "Qwen 3.5 Plus", true),
    model("alibaba/qwen3.6-27b", "Qwen 3.6 27B", false),
    model("alibaba/qwen3.6-plus", "Qwen 3.6 Plus", false),
    model("alibaba/wan-v2.5-t2v-preview", "Wan v2.5 Text-to-Video Preview", false),
    model("alibaba/wan-v2.6-i2v", "Wan v2.6 Image-to-Video", false),
    model("alibaba/wan-v2.6-i2v-flash", "Wan v2.6 Image-to-Video Flash", false),
    model("alibaba/wan-v2.6-r2v", "Wan v2.6 Reference-to-Video", false),
    model("alibaba/wan-v2.6-r2v-flash", "Wan v2.6 Reference-to-Video Flash", false),
    model("alibaba/wan-v2.6-t2v", "Wan v2.6 Text-to-Video", false),
    model("amazon/nova-2-lite", "Nova 2 Lite", false),
    model("amazon/nova-lite", "Nova Lite", false),
    model("amazon/nova-micro", "Nova Micro", false),
    model("amazon/nova-pro", "Nova Pro", false),
    model("amazon/titan-embed-text-v2", "Titan Text Embeddings V2", false),
    model("anthropic/claude-3-haiku", "Claude 3 Haiku", false),
    model("anthropic/claude-3.5-haiku", "Claude 3.5 Haiku", false),
    model("anthropic/claude-3.7-sonnet", "Claude 3.7 Sonnet", true),
    model("anthropic/claude-haiku-4.5", "Claude Haiku 4.5", true),
    model("anthropic/claude-opus-4", "Claude Opus 4", true),
    model("anthropic/claude-opus-4.1", "Claude Opus 4.1", true),
    model("anthropic/claude-opus-4.5", "Claude Opus 4.5", true),
    model("anthropic/claude-opus-4.6", "Claude Opus 4.6", true),
    model("anthropic/claude-opus-4.7", "Claude Opus 4.7", true),
    model("anthropic/claude-sonnet-4", "Claude Sonnet 4", true),
    model("anthropic/claude-sonnet-4.5", "Claude Sonnet 4.5", true),
    model("anthropic/claude-sonnet-4.6", "Claude Sonnet 4.6", true),
    model("arcee-ai/trinity-large-preview", "Trinity Large Preview", false),
    model("arcee-ai/trinity-large-thinking", "Trinity Large Thinking", false),
    model("arcee-ai/trinity-mini", "Trinity Mini", false),
    model("bfl/flux-2-flex", "FLUX.2 [flex]", false),
    model("bfl/flux-2-klein-4b", "FLUX.2 [klein] 4B", false),
    model("bfl/flux-2-klein-9b", "FLUX.2 [klein] 9B", false),
    model("bfl/flux-2-max", "FLUX.2 [max]", false),
    model("bfl/flux-2-pro", "FLUX.2 [pro]", false),
    model("bfl/flux-kontext-max", "FLUX.1 Kontext Max", false),
    model("bfl/flux-kontext-pro", "FLUX.1 Kontext Pro", false),
    model("bfl/flux-pro-1.0-fill", "FLUX.1 Fill [pro]", false),
    model("bfl/flux-pro-1.1", "FLUX1.1 [pro]", false),
    model("bfl/flux-pro-1.1-ultra", "FLUX1.1 [pro] Ultra", false),
    model("bytedance/seed-1.6", "Seed 1.6", false),
    model("bytedance/seed-1.8", "Bytedance Seed 1.8", false),
    model("bytedance/seedance-2.0", "Seedance 2.0", false),
    model("bytedance/seedance-2.0-fast", "Seedance 2.0 Fast", false),
    model("bytedance/seedance-v1.0-lite-i2v", "Seedance v1.0 Lite Image-to-Video", false),
    model("bytedance/seedance-v1.0-lite-t2v", "Seedance v1.0 Lite Text-to-Video", false),
    model("bytedance/seedance-v1.0-pro", "Seedance v1.0 Pro", false),
    model("bytedance/seedance-v1.0-pro-fast", "Seedance v1.0 Pro Fast", false),
    model("bytedance/seedance-v1.5-pro", "Seedance v1.5 Pro", false),
    model("bytedance/seedream-4.0", "Seedream 4.0", false),
    model("bytedance/seedream-4.5", "Seedream 4.5", false),
    model("bytedance/seedream-5.0-lite", "Seedream 5.0 Lite", false),
    model("cohere/command-a", "Command A", false),
    model("cohere/embed-v4.0", "Embed v4.0", false),
    model("cohere/rerank-v3.5", "Cohere Rerank 3.5", false),
    model("cohere/rerank-v4-fast", "Cohere Rerank 4 Fast", false),
    model("cohere/rerank-v4-pro", "Cohere Rerank 4 Pro", false),
    model("deepseek/deepseek-r1", "DeepSeek-R1", true),
    model("deepseek/deepseek-v3", "DeepSeek V3 0324", false),
    model("deepseek/deepseek-v3.1", "DeepSeek-V3.1", true),
    model("deepseek/deepseek-v3.1-terminus", "DeepSeek V3.1 Terminus", true),
    model("deepseek/deepseek-v3.2", "DeepSeek V3.2", true),
    model("deepseek/deepseek-v3.2-thinking", "DeepSeek V3.2 Thinking", true),
    model("deepseek/deepseek-v4-flash", "DeepSeek V4 Flash", true),
    model("deepseek/deepseek-v4-pro", "DeepSeek V4 Pro", true),
    model("google/gemini-2.0-flash", "Gemini 2.0 Flash", false),
    model("google/gemini-2.0-flash-lite", "Gemini 2.0 Flash Lite", false),
    model("google/gemini-2.5-flash", "Gemini 2.5 Flash", true),
    model("google/gemini-2.5-flash-image", "Nano Banana (Gemini 2.5 Flash Image)", true),
    model("google/gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite", true),
    model("google/gemini-2.5-pro", "Gemini 2.5 Pro", true),
    model("google/gemini-3-flash", "Gemini 3 Flash", true),
    model("google/gemini-3-pro-image", "Nano Banana Pro (Gemini 3 Pro Image)", true),
    model("google/gemini-3-pro-preview", "Gemini 3 Pro Preview", true),
    model("google/gemini-3.1-flash-image-preview", "Gemini 3.1 Flash Image Preview (Nano Banana 2)", true),
    model("google/gemini-3.1-flash-lite", "Gemini 3.1 Flash Lite", true),
    model("google/gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview", true),
    model("google/gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", true),
    model("google/gemini-embedding-001", "Gemini Embedding 001", false),
    model("google/gemini-embedding-2", "Gemini Embedding 2", false),
    model("google/gemma-4-26b-a4b-it", "Gemma 4 26B A4B IT", false),
    model("google/gemma-4-31b-it", "Gemma 4 31B IT", false),
    model("google/imagen-4.0-fast-generate-001", "Imagen 4 Fast", false),
    model("google/imagen-4.0-generate-001", "Imagen 4", false),
    model("google/imagen-4.0-ultra-generate-001", "Imagen 4 Ultra", false),
    model("google/text-embedding-005", "Text Embedding 005", false),
    model("google/text-multilingual-embedding-002", "Text Multilingual Embedding 002", false),
    model("google/veo-3.0-fast-generate-001", "Veo 3.0 Fast Generate", false),
    model("google/veo-3.0-generate-001", "Veo 3.0", false),
    model("google/veo-3.1-fast-generate-001", "Veo 3.1 Fast Generate", false),
    model("google/veo-3.1-generate-001", "Veo 3.1", false),
    model("inception/mercury-2", "Mercury 2", false),
    model("inception/mercury-coder-small", "Mercury Coder Small Beta", false),
    model("interfaze/interfaze-beta", "Interfaze Beta", false),
    model("klingai/kling-v2.5-turbo-i2v", "Kling v2.5 Turbo Image-to-Video", false),
    model("klingai/kling-v2.5-turbo-t2v", "Kling v2.5 Turbo Text-to-Video", false),
    model("klingai/kling-v2.6-i2v", "Kling v2.6 Image-to-Video", false),
    model("klingai/kling-v2.6-motion-control", "Kling v2.6 Motion Control", false),
    model("klingai/kling-v2.6-t2v", "Kling v2.6 Text-to-Video", false),
    model("klingai/kling-v3.0-i2v", "Kling v3.0 Image-to-Video", false),
    model("klingai/kling-v3.0-t2v", "Kling v3.0 Text-to-Video", false),
    model("kwaipilot/kat-coder-pro-v1", "KAT-Coder-Pro V1", false),
    model("kwaipilot/kat-coder-pro-v2", "Kat Coder Pro V2", false),
    model("meituan/longcat-flash-chat", "LongCat Flash Chat", false),
    model("meituan/longcat-flash-thinking-2601", "LongCat Flash Thinking 2601", false),
    model("meta/llama-3.1-70b", "Llama 3.1 70B Instruct", false),
    model("meta/llama-3.1-8b", "Llama 3.1 8B Instruct", false),
    model("meta/llama-3.2-11b", "Llama 3.2 11B Vision Instruct", false),
    model("meta/llama-3.2-1b", "Llama 3.2 1B Instruct", false),
    model("meta/llama-3.2-3b", "Llama 3.2 3B Instruct", false),
    model("meta/llama-3.2-90b", "Llama 3.2 90B Vision Instruct", false),
    model("meta/llama-3.3-70b", "Llama 3.3 70B Instruct", false),
    model("meta/llama-4-maverick", "Llama 4 Maverick 17B Instruct", false),
    model("meta/llama-4-scout", "Llama 4 Scout 17B Instruct", false),
    model("minimax/minimax-m2", "MiniMax M2", false),
    model("minimax/minimax-m2.1", "MiniMax M2.1", true),
    model("minimax/minimax-m2.1-lightning", "MiniMax M2.1 Lightning", true),
    model("minimax/minimax-m2.5", "MiniMax M2.5", true),
    model("minimax/minimax-m2.5-highspeed", "MiniMax M2.5 High Speed", true),
    model("minimax/minimax-m2.7", "Minimax M2.7", true),
    model("minimax/minimax-m2.7-highspeed", "MiniMax M2.7 High Speed", true),
    model("mistral/codestral", "Mistral Codestral", false),
    model("mistral/codestral-embed", "Codestral Embed", false),
    model("mistral/devstral-2", "Devstral 2", false),
    model("mistral/devstral-small", "Devstral Small 1.1", false),
    model("mistral/devstral-small-2", "Devstral Small 2", false),
    model("mistral/magistral-medium", "Magistral Medium 2509", true),
    model("mistral/magistral-small", "Magistral Small 2509", true),
    model("mistral/ministral-14b", "Ministral 14B", false),
    model("mistral/ministral-3b", "Ministral 3B", false),
    model("mistral/ministral-8b", "Ministral 8B", false),
    model("mistral/mistral-embed", "Mistral Embed", false),
    model("mistral/mistral-large-3", "Mistral Large 3", false),
    model("mistral/mistral-medium", "Mistral Medium 3.1", false),
    model("mistral/mistral-nemo", "Mistral Nemo 12B", false),
    model("mistral/mistral-small", "Mistral Small", false),
    model("mistral/pixtral-12b", "Pixtral 12B 2409", false),
    model("mistral/pixtral-large", "Pixtral Large", false),
    model("moonshotai/kimi-k2", "Kimi K2 Instruct", false),
    model("moonshotai/kimi-k2-thinking", "Kimi K2 Thinking", true),
    model("moonshotai/kimi-k2-thinking-turbo", "Kimi K2 Thinking Turbo", true),
    model("moonshotai/kimi-k2-turbo", "Kimi K2 Turbo", false),
    model("moonshotai/kimi-k2.5", "Kimi K2.5", true),
    model("moonshotai/kimi-k2.6", "Kimi K2.6", true),
    model("morph/morph-v3-fast", "Morph V3 Fast", false),
    model("morph/morph-v3-large", "Morph V3 Large", false),
    model("nvidia/nemotron-3-nano-30b-a3b", "Nemotron 3 Nano 30B A3B", true),
    model("nvidia/nemotron-3-super-120b-a12b", "NVIDIA Nemotron 3 Super 120B A12B", true),
    model("nvidia/nemotron-nano-12b-v2-vl", "Nvidia Nemotron Nano 12B V2 VL", false),
    model("nvidia/nemotron-nano-9b-v2", "Nvidia Nemotron Nano 9B V2", false),
    model("openai/gpt-3.5-turbo", "GPT-3.5 Turbo", false),
    model("openai/gpt-3.5-turbo-instruct", "GPT-3.5 Turbo Instruct", false),
    model("openai/gpt-4-turbo", "GPT-4 Turbo", false),
    model("openai/gpt-4.1", "GPT-4.1", false),
    model("openai/gpt-4.1-mini", "GPT-4.1 mini", false),
    model("openai/gpt-4.1-nano", "GPT-4.1 nano", false),
    model("openai/gpt-4o", "GPT-4o", false),
    model("openai/gpt-4o-mini", "GPT-4o mini", false),
    model("openai/gpt-4o-mini-search-preview", "GPT 4o Mini Search Preview", false),
    model("openai/gpt-5", "GPT-5", true),
    model("openai/gpt-5-chat", "GPT 5 Chat", false),
    model("openai/gpt-5-codex", "GPT-5-Codex", true),
    model("openai/gpt-5-mini", "GPT-5 mini", true),
    model("openai/gpt-5-nano", "GPT-5 nano", true),
    model("openai/gpt-5-pro", "GPT-5 pro", true),
    model("openai/gpt-5.1-codex", "GPT-5.1-Codex", true),
    model("openai/gpt-5.1-codex-max", "GPT 5.1 Codex Max", true),
    model("openai/gpt-5.1-codex-mini", "GPT 5.1 Codex Mini", true),
    model("openai/gpt-5.1-instant", "GPT-5.1 Instant", true),
    model("openai/gpt-5.1-thinking", "GPT 5.1 Thinking", true),
    model("openai/gpt-5.2", "GPT 5.2", true),
    model("openai/gpt-5.2-chat", "GPT 5.2 Chat", true),
    model("openai/gpt-5.2-codex", "GPT 5.2 Codex", true),
    model("openai/gpt-5.2-pro", "GPT 5.2", true),
    model("openai/gpt-5.3-chat", "GPT-5.3 Chat", true),
    model("openai/gpt-5.3-codex", "GPT 5.3 Codex", true),
    model("openai/gpt-5.4", "GPT 5.4", true),
    model("openai/gpt-5.4-mini", "GPT 5.4 Mini", true),
    model("openai/gpt-5.4-nano", "GPT 5.4 Nano", true),
    model("openai/gpt-5.4-pro", "GPT 5.4 Pro", true),
    model("openai/gpt-5.5", "GPT 5.5", true),
    model("openai/gpt-5.5-pro", "GPT 5.5 Pro", true),
    model("openai/gpt-image-1", "GPT Image 1", false),
    model("openai/gpt-image-1-mini", "GPT Image 1 Mini", false),
    model("openai/gpt-image-1.5", "GPT Image 1.5", false),
    model("openai/gpt-image-2", "GPT Image 2", false),
    model("openai/gpt-oss-120b", "GPT OSS 120B", true),
    model("openai/gpt-oss-20b", "GPT OSS 120B", true),
    model("openai/gpt-oss-safeguard-20b", "GPT OSS Safeguard 20B", true),
    model("openai/o1", "o1", true),
    model("openai/o3", "o3", true),
    model("openai/o3-deep-research", "o3-deep-research", true),
    model("openai/o3-mini", "o3-mini", true),
    model("openai/o3-pro", "o3 Pro", true),
    model("openai/o4-mini", "o4-mini", true),
    model("openai/text-embedding-3-large", "text-embedding-3-large", false),
    model("openai/text-embedding-3-small", "text-embedding-3-small", false),
    model("openai/text-embedding-ada-002", "text-embedding-ada-002", false),
    model("perplexity/sonar", "Sonar", false),
    model("perplexity/sonar-pro", "Sonar Pro", false),
    model("perplexity/sonar-reasoning-pro", "Sonar Reasoning Pro", true),
    model("prodia/flux-fast-schnell", "Flux Schnell", false),
    model("recraft/recraft-v2", "Recraft V2", false),
    model("recraft/recraft-v3", "Recraft V3", false),
    model("recraft/recraft-v4", "Recraft V4", false),
    model("recraft/recraft-v4-pro", "Recraft V4 Pro", false),
    model("voyage/rerank-2.5", "Voyage Rerank 2.5", false),
    model("voyage/rerank-2.5-lite", "Voyage Rerank 2.5 Lite", false),
    model("voyage/voyage-3-large", "voyage-3-large", false),
    model("voyage/voyage-3.5", "Voyage 3.5", false),
    model("voyage/voyage-3.5-lite", "Voyage 3.5 Lite", false),
    model("voyage/voyage-4", "Voyage 4", false),
    model("voyage/voyage-4-large", "Voyage 4 Large", false),
    model("voyage/voyage-4-lite", "Voyage 4 Lite", false),
    model("voyage/voyage-code-2", "Voyage Code 2", false),
    model("voyage/voyage-code-3", "Voyage Code 3", false),
    model("voyage/voyage-finance-2", "Voyage Finance 2", false),
    model("voyage/voyage-law-2", "Voyage Law 2", false),
    model("xai/grok-3", "Grok 3 Beta", false),
    model("xai/grok-3-fast", "Grok 3 Fast Beta", false),
    model("xai/grok-3-mini", "Grok 3 Mini Beta", false),
    model("xai/grok-3-mini-fast", "Grok 3 Mini Fast Beta", false),
    model("xai/grok-4", "Grok 4", false),
    model("xai/grok-4-fast-non-reasoning", "Grok 4 Fast Non-Reasoning", false),
    model("xai/grok-4-fast-reasoning", "Grok 4 Fast Reasoning", true),
    model("xai/grok-4.1-fast-non-reasoning", "Grok 4.1 Fast Non-Reasoning", false),
    model("xai/grok-4.1-fast-reasoning", "Grok 4.1 Fast Reasoning", true),
    model("xai/grok-4.20-multi-agent", "Grok 4.20 Multi-Agent", false),
    model("xai/grok-4.20-multi-agent-beta", "Grok 4.20 Multi Agent Beta", false),
    model("xai/grok-4.20-non-reasoning", "Grok 4.20 Non-Reasoning", false),
    model("xai/grok-4.20-non-reasoning-beta", "Grok 4.20 Beta Non-Reasoning", false),
    model("xai/grok-4.20-reasoning", "Grok 4.20 Reasoning", true),
    model("xai/grok-4.20-reasoning-beta", "Grok 4.20 Beta Reasoning", true),
    model("xai/grok-4.3", "Grok 4.3", false),
    model("xai/grok-code-fast-1", "Grok Code Fast 1", false),
    model("xai/grok-imagine-image", "Grok Imagine Image", false),
    model("xai/grok-imagine-image-pro", "Grok Imagine Image Pro", false),
    model("xai/grok-imagine-video", "Grok Imagine", false),
    model("xiaomi/mimo-v2-flash", "MiMo V2 Flash", false),
    model("xiaomi/mimo-v2-pro", "MiMo V2 Pro", false),
    model("xiaomi/mimo-v2.5", "MiMo M2.5", false),
    model("xiaomi/mimo-v2.5-pro", "MiMo V2.5 Pro", false),
    model("zai/glm-4.5", "GLM-4.5", true),
    model("zai/glm-4.5-air", "GLM 4.5 Air", true),
    model("zai/glm-4.5v", "GLM 4.5V", true),
    model("zai/glm-4.6", "GLM 4.6", true),
    model("zai/glm-4.6v", "GLM-4.6V", true),
    model("zai/glm-4.6v-flash", "GLM-4.6V-Flash", true),
    model("zai/glm-4.7", "GLM 4.7", true),
    model("zai/glm-4.7-flash", "GLM 4.7 Flash", true),
    model("zai/glm-4.7-flashx", "GLM 4.7 FlashX", true),
    model("zai/glm-5", "GLM 5", true),
    model("zai/glm-5-turbo", "GLM 5 Turbo", true),
    model("zai/glm-5.1", "GLM 5.1", true),
    model("zai/glm-5v-turbo", "GLM 5V Turbo", true),
  ],
}
