import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const ALTRU_CODER_EXPERIMENTAL = truthy("ALTRU_CODER_EXPERIMENTAL")
const ALTRU_CODER_DISABLE_CLAUDE_CODE = truthy("ALTRU_CODER_DISABLE_CLAUDE_CODE")
const ALTRU_CODER_DISABLE_CLAUDE_CODE_SKILLS =
  ALTRU_CODER_DISABLE_CLAUDE_CODE || truthy("ALTRU_CODER_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["ALTRU_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  ALTRU_CODER_AUTO_SHARE: truthy("ALTRU_CODER_AUTO_SHARE"),
  ALTRU_CODER_AUTO_HEAP_SNAPSHOT: truthy("ALTRU_CODER_AUTO_HEAP_SNAPSHOT"),
  ALTRU_CODER_GIT_BASH_PATH: process.env["ALTRU_CODER_GIT_BASH_PATH"],
  ALTRU_CODER_CONFIG: process.env["ALTRU_CODER_CONFIG"],
  ALTRU_CODER_CONFIG_CONTENT: process.env["ALTRU_CODER_CONFIG_CONTENT"],
  ALTRU_CODER_DISABLE_AUTOUPDATE: truthy("ALTRU_CODER_DISABLE_AUTOUPDATE"),
  ALTRU_CODER_ALWAYS_NOTIFY_UPDATE: truthy("ALTRU_CODER_ALWAYS_NOTIFY_UPDATE"),
  ALTRU_CODER_DISABLE_PRUNE: truthy("ALTRU_CODER_DISABLE_PRUNE"),
  ALTRU_CODER_DISABLE_TERMINAL_TITLE: truthy("ALTRU_CODER_DISABLE_TERMINAL_TITLE"),
  ALTRU_CODER_SHOW_TTFD: truthy("ALTRU_CODER_SHOW_TTFD"),
  ALTRU_CODER_PERMISSION: process.env["ALTRU_CODER_PERMISSION"],
  ALTRU_CODER_DISABLE_DEFAULT_PLUGINS: truthy("ALTRU_CODER_DISABLE_DEFAULT_PLUGINS"),
  ALTRU_CODER_DISABLE_LSP_DOWNLOAD: truthy("ALTRU_CODER_DISABLE_LSP_DOWNLOAD"),
  ALTRU_CODER_ENABLE_EXPERIMENTAL_MODELS: truthy("ALTRU_CODER_ENABLE_EXPERIMENTAL_MODELS"),
  ALTRU_CODER_DISABLE_AUTOCOMPACT: truthy("ALTRU_CODER_DISABLE_AUTOCOMPACT"),
  ALTRU_CODER_DISABLE_MODELS_FETCH: truthy("ALTRU_CODER_DISABLE_MODELS_FETCH"),
  ALTRU_CODER_DISABLE_MOUSE: truthy("ALTRU_CODER_DISABLE_MOUSE"),
  ALTRU_CODER_DISABLE_CLAUDE_CODE,
  ALTRU_CODER_DISABLE_CLAUDE_CODE_PROMPT:
    ALTRU_CODER_DISABLE_CLAUDE_CODE || truthy("ALTRU_CODER_DISABLE_CLAUDE_CODE_PROMPT"),
  ALTRU_CODER_DISABLE_CLAUDE_CODE_SKILLS,
  ALTRU_CODER_DISABLE_EXTERNAL_SKILLS:
    ALTRU_CODER_DISABLE_CLAUDE_CODE_SKILLS || truthy("ALTRU_CODER_DISABLE_EXTERNAL_SKILLS"),
  ALTRU_CODER_FAKE_VCS: process.env["ALTRU_CODER_FAKE_VCS"],
  ALTRU_CODER_SERVER_PASSWORD: process.env["ALTRU_CODER_SERVER_PASSWORD"],
  ALTRU_CODER_SERVER_USERNAME: process.env["ALTRU_CODER_SERVER_USERNAME"],
  ALTRU_CODER_ENABLE_QUESTION_TOOL: truthy("ALTRU_CODER_ENABLE_QUESTION_TOOL"),

  // Experimental
  ALTRU_CODER_EXPERIMENTAL,
  ALTRU_CODER_EXPERIMENTAL_FILEWATCHER: Config.boolean("ALTRU_CODER_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ALTRU_CODER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("ALTRU_CODER_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ALTRU_CODER_EXPERIMENTAL_ICON_DISCOVERY:
    ALTRU_CODER_EXPERIMENTAL || truthy("ALTRU_CODER_EXPERIMENTAL_ICON_DISCOVERY"),
  ALTRU_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("ALTRU_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  ALTRU_CODER_ENABLE_EXA:
    truthy("ALTRU_CODER_ENABLE_EXA") || ALTRU_CODER_EXPERIMENTAL || truthy("ALTRU_CODER_EXPERIMENTAL_EXA"),
  ALTRU_CODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("ALTRU_CODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  ALTRU_CODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("ALTRU_CODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  ALTRU_CODER_EXPERIMENTAL_OXFMT: ALTRU_CODER_EXPERIMENTAL || truthy("ALTRU_CODER_EXPERIMENTAL_OXFMT"),
  ALTRU_CODER_EXPERIMENTAL_LSP_TY: truthy("ALTRU_CODER_EXPERIMENTAL_LSP_TY"),
  ALTRU_CODER_EXPERIMENTAL_LSP_TOOL: ALTRU_CODER_EXPERIMENTAL || truthy("ALTRU_CODER_EXPERIMENTAL_LSP_TOOL"),
  ALTRU_CODER_EXPERIMENTAL_PLAN_MODE: ALTRU_CODER_EXPERIMENTAL || truthy("ALTRU_CODER_EXPERIMENTAL_PLAN_MODE"),
  ALTRU_CODER_EXPERIMENTAL_MARKDOWN: !falsy("ALTRU_CODER_EXPERIMENTAL_MARKDOWN"),
  ALTRU_CODER_MODELS_URL: process.env["ALTRU_CODER_MODELS_URL"],
  ALTRU_CODER_MODELS_PATH: process.env["ALTRU_CODER_MODELS_PATH"],
  ALTRU_CODER_DISABLE_EMBEDDED_WEB_UI: truthy("ALTRU_CODER_DISABLE_EMBEDDED_WEB_UI"),
  ALTRU_CODER_DB: process.env["ALTRU_CODER_DB"],
  ALTRU_CODER_DISABLE_CHANNEL_DB: truthy("ALTRU_CODER_DISABLE_CHANNEL_DB"),
  ALTRU_CODER_SKIP_MIGRATIONS: truthy("ALTRU_CODER_SKIP_MIGRATIONS"),
  ALTRU_CODER_STRICT_CONFIG_DEPS: truthy("ALTRU_CODER_STRICT_CONFIG_DEPS"),

  ALTRU_CODER_WORKSPACE_ID: process.env["ALTRU_CODER_WORKSPACE_ID"],
  ALTRU_CODER_EXPERIMENTAL_HTTPAPI: truthy("ALTRU_CODER_EXPERIMENTAL_HTTPAPI"),
  ALTRU_CODER_EXPERIMENTAL_WORKSPACES: ALTRU_CODER_EXPERIMENTAL || truthy("ALTRU_CODER_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get ALTRU_CODER_DISABLE_PROJECT_CONFIG() {
    return truthy("ALTRU_CODER_DISABLE_PROJECT_CONFIG")
  },
  get ALTRU_CODER_TUI_CONFIG() {
    return process.env["ALTRU_CODER_TUI_CONFIG"]
  },
  get ALTRU_CODER_CONFIG_DIR() {
    return process.env["ALTRU_CODER_CONFIG_DIR"]
  },
  get ALTRU_CODER_PURE() {
    return truthy("ALTRU_CODER_PURE")
  },
  get ALTRU_CODER_PLUGIN_META_FILE() {
    return process.env["ALTRU_CODER_PLUGIN_META_FILE"]
  },
  get ALTRU_CODER_CLIENT() {
    return process.env["ALTRU_CODER_CLIENT"] ?? "cli"
  },
  // altrucoder_change start
  get ALTRU_CODER_SESSION_RETRY_LIMIT() {
    return number("ALTRU_CODER_SESSION_RETRY_LIMIT")
  },
  // altrucoder_change end
}
